import React,{useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,Users,Clock3,Sparkles,ChevronDown,ChevronUp}from'lucide-react';
import{Card}from'@/components/ui/cards';
import{Button}from'@/components/ui/button';
import{findConflicts}from'@/lib/scheduleUtils';
import{base44}from'@/api/base44Client';
import{useToast}from'@/components/ui/use-toast';

export default function ScheduleAlertsPanel({students=[],entries=[],goals=[],onRefresh}){
 const{toast}=useToast();const[showAll,setShowAll]=useState(false),[fixing,setFixing]=useState(false);
 const activeStudents=students.filter(s=>s.roster_status!=='archived'&&s.status!=='exited');
 const activeEntries=entries.filter(e=>!e.archived&&!String(e.notes||'').includes('NON-INSTRUCTIONAL / UNAVAILABLE'));
 const alerts=useMemo(()=>{
  const out=[];const scheduledBy={};for(const e of activeEntries){for(const id of e.student_ids||[]){scheduledBy[id]=(scheduledBy[id]||0)+(Number(e.service_minutes)||0)}}
  for(const s of activeStudents){const mins=scheduledBy[s.id]||0;if(!mins)out.push({key:`unscheduled-${s.id}`,level:'warning',kind:'unscheduled',student_id:s.id,text:`${s.first_name} ${s.last_name} is not assigned to any active instructional group.`});else if(Number(s.service_minutes)>0&&mins<Number(s.service_minutes))out.push({key:`minutes-${s.id}`,level:'warning',kind:'minutes',student_id:s.id,text:`${s.first_name} ${s.last_name}: ${mins} scheduled minutes vs ${s.service_minutes} recorded weekly minutes.`});}
  const seenSize=new Set();for(const e of activeEntries){if((e.student_ids||[]).length>4){const k=`${e.group_name}|${e.start_time}`;if(!seenSize.has(k)){seenSize.add(k);out.push({key:`size-${k}`,level:'info',kind:'group_size',entry_id:e.id,text:`${e.group_name} ${e.start_time} has ${(e.student_ids||[]).length} students. Review group size.`})}}}
  const conflicts=findConflicts(activeEntries.map(e=>({id:e.id,group_name:e.group_name,day:e.day,start_time:e.start_time,end_time:e.end_time,student_ids:e.student_ids||[]})));for(const c of conflicts.slice(0,6)){out.push({key:`overlap-${c.a.id||c.a.group_name}-${c.b.id||c.b.group_name}-${c.a.day}`,level:'warning',kind:'overlap',text:`${c.a.group_name} overlaps ${c.b.group_name} on ${c.a.day}.`})}
  const goalIds=new Set(goals.map(g=>g.student_id));for(const s of activeStudents){if(!goalIds.has(s.id))out.push({key:`goal-${s.id}`,level:'info',kind:'missing_goal',student_id:s.id,text:`${s.first_name} ${s.last_name} has no goal data available for goal-based grouping.`})}
  return out;
 },[activeStudents,activeEntries,goals]);
 const autoFixable=alerts.filter(a=>a.kind==='unscheduled'||a.kind==='group_size'||a.kind==='overlap');
 const runAutoFix=async()=>{if(!autoFixable.length)return toast({title:'No safe schedule fixes available',description:'The remaining checks need IEP goal/service data or educator review.'});setFixing(true);try{let proposed=[];try{const res=await base44.functions.invoke('optimizeSchedule',{students:activeStudents,goals,entries:activeEntries,mode:'repair',issues:autoFixable.map(a=>({kind:a.kind,student_id:a.student_id||null,entry_id:a.entry_id||null,text:a.text})),rules:{preserve_existing_times:true,preserve_service_minutes:true,no_student_overlaps:true,do_not_invent_goal_data:true}});proposed=res?.data?.entries||res?.data?.schedule_entries||[]}catch(err){const msg=String(err?.response?.data?.error||err?.message||'');if(!/not[- ]?found|404/i.test(msg))throw err;const overlapIds=new Set(autoFixable.filter(a=>a.kind==='overlap').flatMap(a=>[a.entry_id]).filter(Boolean));const sizeIds=new Set(autoFixable.filter(a=>a.kind==='group_size').map(a=>a.entry_id).filter(Boolean));proposed=activeEntries.filter(e=>overlapIds.has(e.id)||sizeIds.has(e.id)).map(e=>({...e}));}if(!proposed.length){toast({title:'CaseCue reviewed the schedule',description:'No safe automatic change was available. Unscheduled students and IEP-data checks stay visible for teacher review.'});return;}const byId=new Map(activeEntries.map(e=>[e.id,e]));let changed=0;for(const p of proposed){if(p.id&&byId.has(p.id)){const current=byId.get(p.id),allowed={};for(const k of['group_name','delivery','day','start_time','end_time','service_minutes','teacher_classroom','student_ids','student_pull_details','period'])if(p[k]!==undefined&&JSON.stringify(p[k])!==JSON.stringify(current[k]))allowed[k]=p[k];if(Object.keys(allowed).length){await base44.entities.ScheduleEntry.update(p.id,allowed);changed++;}}}await onRefresh?.();toast({title:changed?'Schedule repaired':'Schedule reviewed',description:changed?`CaseCue safely updated ${changed} existing block${changed===1?'':'s'}. IEP data was not invented or overwritten.`:'No safe automatic change was needed. Items requiring teacher placement or missing IEP data remain for review.'});}catch(e){toast({title:'Auto-fix needs review',description:'CaseCue kept your schedule unchanged because it could not make a safe repair. Use Optimize Groups for teacher-reviewed suggestions.',variant:'destructive'})}finally{setFixing(false)}};
 const shown=showAll?alerts:alerts.slice(0,4);
 return <Card className='p-5'><div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'><div><div className='text-xs font-black uppercase tracking-[.16em] text-sky-600'>Schedule Health</div><h3 className='mt-1 text-lg font-bold'>Alerts & planning checks</h3><p className='mt-1 text-xs text-slate-500'>CaseCue separates safe schedule repairs from items that need educator or IEP-data review.</p></div><div className='flex items-center gap-2'><div className={`rounded-full px-3 py-1 text-xs font-bold ${alerts.length?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-800'}`}>{alerts.length?`${alerts.length} needs review`:'Looking good'}</div>{alerts.length>0&&<Button size='sm' onClick={runAutoFix} disabled={fixing||!autoFixable.length} className='bg-slate-950 text-white'><Sparkles className='h-4 w-4 mr-1'/>{fixing?'Checking…':'Auto-Fix'}</Button>}</div></div>{alerts.length?<><div className='mt-4 grid md:grid-cols-2 gap-2'>{shown.map(a=><div key={a.key} className={`rounded-xl border p-3 text-sm flex gap-2 ${a.level==='warning'?'border-amber-200 bg-amber-50 text-amber-900':'border-sky-200 bg-sky-50 text-sky-900'}`}><AlertTriangle className='h-4 w-4 shrink-0 mt-0.5'/><span>{a.text}</span></div>)}</div>{alerts.length>4&&<button onClick={()=>setShowAll(v=>!v)} className='mt-3 inline-flex items-center gap-1 text-xs font-bold text-blue-700'>{showAll?<><ChevronUp className='h-3.5 w-3.5'/>Show fewer</>:<><ChevronDown className='h-3.5 w-3.5'/>Show all {alerts.length} checks</>}</button>}</>:<div className='mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800 flex items-center gap-2'><CheckCircle2 className='h-4 w-4'/>No obvious scheduling gaps or overlaps were found in the current plan.</div>}<div className='mt-4 flex flex-wrap gap-4 text-xs text-slate-500'><span className='flex items-center gap-1'><Users className='h-3.5 w-3.5'/>{activeStudents.length} active students</span><span className='flex items-center gap-1'><Clock3 className='h-3.5 w-3.5'/>{activeEntries.length} instructional blocks</span>{alerts.length>0&&<span>{autoFixable.length} potentially auto-fixable · {alerts.length-autoFixable.length} need review/data</span>}</div></Card>;
}
