import { jsPDF } from "jspdf";

// Shared export pipeline for every generated CaseCue document.
// One HTML builder feeds Print and Word (DOCX); one jsPDF writer feeds PDF;
// a plain-text renderer feeds Email and Share. Every document carries the
// educator-review banner.

export const DEFAULT_BANNER = "DRAFT — Educator Review Required. Generated by CaseCue.";

const esc = (t) => String(t == null ? "" : t)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/\n/g, "<br>");

const safeName = (t) => String(t || "casecue-document").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").slice(0, 60);

export function buildDocHtml({ title, subtitle, sections, banner }) {
  const body = (sections || [])
    .map((s) => `<h2>${esc(s.heading)}</h2><div class="ftext">${esc(s.body) || "<em>—</em>"}</div>`)
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
  body{font-family:Calibri,Arial,sans-serif;color:#1a1a2e;margin:40px;}
  .hdr{background:linear-gradient(135deg,#6d28d9,#2563eb);color:#fff;padding:24px;border-radius:10px;}
  .hdr h1{margin:0 0 6px;font-size:22px;}
  .hdr .meta{font-size:13px;opacity:.92;}
  h2{color:#6d28d9;border-bottom:2px solid #e5e0f5;padding-bottom:4px;font-size:16px;margin-top:26px;}
  .ftext{font-size:13px;line-height:1.55;white-space:pre-wrap;margin-top:6px;}
  .banner{background:#fff7ed;border:1px solid #fdba74;color:#9a3412;padding:10px 14px;border-radius:8px;font-size:12px;margin-top:24px;}
  </style></head><body>
  <div class="hdr"><h1>${esc(title)}</h1>${subtitle ? `<div class="meta">${esc(subtitle)}</div>` : ""}</div>
  ${body}
  <div class="banner">${esc(banner || DEFAULT_BANNER)}</div>
  </body></html>`;
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

// Opens a print-ready window. Returns false when pop-ups are blocked.
export function printDoc(opts) {
  const w = window.open("", "_blank");
  if (!w) return false;
  w.document.write(buildDocHtml(opts));
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
  return true;
}

// Word-compatible DOCX (HTML-based, same approach as Lesson Studio exports).
export function exportDocDocx(opts) {
  downloadBlob(new Blob(["\ufeff", buildDocHtml(opts)], { type: "application/msword" }), `${safeName(opts.filename)}.doc`);
}

// PDF: normalize to base-14-safe ASCII so nothing renders as gaps or
// inconsistent glyphs in the exported file.
const pdfSafe = (t) => String(t == null ? "" : t)
  .replace(/\r\n?/g, "\n")
  .replace(/[\u2018\u2019\u201A\u201B\u2039\u203A]/g, "'")
  .replace(/[\u201C\u201D\u201E\u00AB\u00BB]/g, '"')
  .replace(/[\u2013\u2014\u2015]/g, "-")
  .replace(/\u2026/g, "...")
  .replace(/[\u2192\u21D2\u27A1]/g, "->")
  .replace(/\u2190/g, "<-")
  .replace(/\u2265/g, ">=")
  .replace(/\u2264/g, "<=")
  .replace(/\u2260/g, "!=")
  .replace(/[\u2022\u25CF\u25AA\u00B7]/g, "-")
  .replace(/\u200B/g, "")
  .replace(/[\u00A0\u2007\u2009\u202F]/g, " ")
  .replace(/\t/g, " ")
  .replace(/\*\*/g, "")
  .replace(/^#{1,6}[ \t]+/gm, "")
  .replace(/[ \t]{2,}/g, " ")
  .replace(/[^\n\x20-\x7E\xA1-\xFF]/g, "");

export function exportDocPdf({ title, subtitle, sections, banner, filename }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const PAGE_H = 842;
  const M = 48;
  const CW = 595 - M * 2;

  let y = M;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(60, 40, 120);
  const titleLines = doc.splitTextToSize(pdfSafe(title), CW);
  titleLines.forEach((ln) => { doc.text(ln, M, y + 12); y += 20; });
  y += 14;
  doc.setTextColor(40, 40, 40);

  const write = (text, size = 11, bold = false, color = [40, 40, 40], gap = 6) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(pdfSafe(text ?? "—"), CW);
    for (const line of lines) {
      if (y > PAGE_H - 60) { doc.addPage(); y = M; }
      doc.text(line, M, y);
      y += size * 1.35;
    }
    y += gap;
  };

  if (subtitle) write(subtitle, 10, false, [110, 110, 110], 12);

  for (const s of sections || []) {
    if (y > PAGE_H - 90) { doc.addPage(); y = M; }
    write(s.heading, 12, true, [109, 40, 217], 3);
    write(s.body, 11, false, [40, 40, 40], 10);
  }

  const footer = banner || DEFAULT_BANNER;
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text(pdfSafe(footer), M, PAGE_H - 24);
  }

  doc.save(`${safeName(filename)}.pdf`);
}

function plainText({ title, subtitle, sections }) {
  return [
    title,
    subtitle,
    ...(sections || []).flatMap((s) => [s.heading ? `${s.heading}:` : "", s.body]),
  ]
    .filter((x) => x != null && x !== "")
    .join("\n\n");
}

// Opens the user's email client with the document in the body. Long documents
// are trimmed (mailto limits vary by client); the note points to the full export.
export function emailDoc(opts) {
  const text = plainText(opts);
  const clipped = text.length > 3800;
  const body = encodeURIComponent(
    text.slice(0, 3800) +
      (clipped ? "\n\n— Content trimmed for email. Use Print or PDF in CaseCue for the full document." : "")
  );
  window.location.href = `mailto:?subject=${encodeURIComponent(`${opts.title} — from CaseCue`)}&body=${body}`;
}

// Returns "shared" (OS share sheet), "copied" (no share support), or "failed".
export async function shareDoc(opts) {
  const text = plainText(opts);
  if (navigator.share) {
    try {
      await navigator.share({ title: opts.title, text });
      return "shared";
    } catch {
      return "cancelled";
    }
  }
  try {
    await navigator.clipboard.writeText(text);
    return "copied";
  } catch {
    return "failed";
  }
}