import { jsPDF } from "jspdf";
import logExportAction from "@/lib/exportAudit";

// Shared export pipeline for every generated CaseCue document.
// One HTML builder feeds Print and Word (DOCX); one jsPDF writer feeds PDF;
// a plain-text renderer feeds Email and Share. Every document carries the
// educator-review banner.

export const DEFAULT_BANNER = "DRAFT — Educator Review Required. Generated by CaseCue.";

const esc = (t) => String(t == null ? "" : t)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/\n/g, "<br>");

const safeName = (t) => String(t || "casecue-document").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").slice(0, 60);

export function buildDocHtml({ title, subtitle, sections, banner }) {
  const printed = new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" });
  const body = (sections || [])
    .map((s, index) => {
      const img = s.image
        ? `<div class="imgwrap"><img src="${s.image}" alt="" /></div>`
        : "";
      const text = s.body ? `<div class="ftext">${esc(s.body)}</div>` : "";
      return `<section class="case-section"><div class="section-kicker">SECTION ${String(index + 1).padStart(2, "0")}</div><h2>${esc(s.heading || "Details")}</h2>${img}${text}</section>`;
    })
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
  @page{size:auto;margin:0.55in 0.55in 0.7in;}
  *{box-sizing:border-box}
  body{font-family:Inter,Arial,Helvetica,sans-serif;color:#0f172a;margin:0;background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .page-shell{max-width:900px;margin:0 auto}
  .brandbar{display:flex;align-items:flex-start;justify-content:space-between;gap:22px;border:1px solid #dbeafe;background:linear-gradient(135deg,#07101f,#102b4d);color:#fff;padding:18px 20px;border-radius:14px}
  .brand{font-weight:900;letter-spacing:.14em;text-transform:uppercase;font-size:10px;color:#7dd3fc}
  .hdr h1{margin:5px 0 0;font-size:23px;line-height:1.15;letter-spacing:-.02em}
  .hdr .meta{font-size:10.5px;color:#cbd5e1;margin-top:6px}
  .printmeta{text-align:right;min-width:105px;color:#cbd5e1;font-size:9px;line-height:1.45}
  .printmeta b{display:block;color:#fff;font-size:10px;margin-bottom:2px}
  .case-section{break-inside:avoid;margin-top:16px;border:1px solid #e2e8f0;border-radius:14px;padding:16px 17px;background:#fff;box-shadow:0 1px 0 rgba(15,23,42,.03)}
  .section-kicker{font-size:8px;font-weight:900;letter-spacing:.16em;color:#64748b}
  h2{color:#0f172a;font-size:14px;margin:4px 0 9px;padding-bottom:8px;border-bottom:1px solid #e2e8f0}
  .ftext{font-size:11.25px;line-height:1.58;white-space:pre-wrap;color:#334155}
  .imgwrap{margin-top:8px;border:1px solid #e2e8f0;border-radius:10px;padding:8px;text-align:center}
  .imgwrap img{max-width:100%;height:auto}
  .banner{margin-top:16px;background:#eff6ff;border:1px solid #bfdbfe;color:#1e3a8a;padding:10px 13px;border-radius:10px;font-size:9.5px;font-weight:700}
  .footer{position:fixed;left:0.55in;right:0.55in;bottom:0.22in;display:flex;justify-content:space-between;border-top:1px solid #e2e8f0;padding-top:6px;font-size:8px;color:#64748b}
  @media print{.page-shell{max-width:none}.case-section{box-shadow:none}}
  </style></head><body>
  <div class="page-shell">
   <div class="brandbar"><div class="hdr"><div class="brand">CaseCue</div><h1>${esc(title)}</h1>${subtitle ? `<div class="meta">${esc(subtitle)}</div>` : ""}</div><div class="printmeta"><b>Printed</b>${esc(printed)}</div></div>
   ${body}
   <div class="banner">${esc(banner || DEFAULT_BANNER)}</div>
  </div>
  <div class="footer"><span>CaseCue · getcasecue.com</span><span>Printed ${esc(printed)}</span></div>
  </body></html>`;
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

// Opens a print-ready window. Returns false when pop-ups are blocked.
export function printDoc(opts) {
  const w = window.open("", "_blank");
  if (!w) return false;
  logExportAction("print", opts.title);
  w.document.write(buildDocHtml(opts));
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
  return true;
}

// Word-compatible DOCX (HTML-based, same approach as Lesson Studio exports).
export function exportDocDocx(opts) {
  logExportAction("docx", opts.title);
  downloadBlob(new Blob(["\ufeff", buildDocHtml(opts)], { type: "application/msword" }), `${safeName(opts.filename)}.doc`);
}

// PDF: normalize to base-14-safe ASCII so nothing renders as gaps or
// inconsistent glyphs in the exported file.
const pdfSafe = (t) => String(t == null ? "" : t)
  .replace(/\r\n?/g, "\n")
  .replace(/[\u2018\u2019\u201A\u201B\u2039\u203A]/g, "'")
  .replace(/[\u201C\u201D\u201E\u00AB\u00BB]/g, '"')
  .replace(/[\u2013\u2014\u2015]/g, "-")
  .replace(/\u2026/g, "...")
  .replace(/[\u2192\u21D2\u27A1]/g, "->")
  .replace(/\u2190/g, "<-")
  .replace(/\u2265/g, ">=")
  .replace(/\u2264/g, "<=")
  .replace(/\u2260/g, "!=")
  .replace(/[\u2022\u25CF\u25AA\u00B7]/g, "-")
  .replace(/\u200B/g, "")
  .replace(/[\u00A0\u2007\u2009\u202F]/g, " ")
  .replace(/\t/g, " ")
  .replace(/\*\*/g, "")
  .replace(/^#{1,6}[ \t]+/gm, "")
  .replace(/[ \t]{2,}/g, " ")
  .replace(/[^\n\x20-\x7E\xA1-\xFF]/g, "");

export function exportDocPdf({ title, subtitle, sections, banner, filename }) {
  logExportAction("pdf", title);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const PAGE_H = 842;
  const M = 48;
  const CW = 595 - M * 2;

  let y = M;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(60, 40, 120);
  const titleLines = doc.splitTextToSize(pdfSafe(title), CW);
  titleLines.forEach((ln) => { doc.text(ln, M, y + 12); y += 20; });
  y += 14;
  doc.setTextColor(40, 40, 40);

  const write = (text, size = 11, bold = false, color = [40, 40, 40], gap = 6) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(pdfSafe(text ?? "—"), CW);
    for (const line of lines) {
      if (y > PAGE_H - 60) { doc.addPage(); y = M; }
      doc.text(line, M, y);
      y += size * 1.35;
    }
    y += gap;
  };

  if (subtitle) write(subtitle, 10, false, [110, 110, 110], 12);

  for (const s of sections || []) {
    if (y > PAGE_H - 90) { doc.addPage(); y = M; }
    write(s.heading, 12, true, [109, 40, 217], 3);
    if (s.image && s.imageWidth && s.imageHeight) {
      let imgW = CW;
      let imgH = CW * (s.imageHeight / s.imageWidth);
      const maxH = PAGE_H - M * 2 - 40;
      if (imgH > maxH) { imgH = maxH; imgW = imgH * (s.imageWidth / s.imageHeight); }
      if (y + imgH > PAGE_H - 60) { doc.addPage(); y = M; }
      try { doc.addImage(s.image, "PNG", M, y, imgW, imgH); y += imgH + 8; } catch { /* skip unreadable image */ }
    }
    if (s.body) write(s.body, 11, false, [40, 40, 40], 10);
  }

  const footer = banner || DEFAULT_BANNER;
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text(pdfSafe(footer), M, PAGE_H - 24);
  }

  doc.save(`${safeName(filename)}.pdf`);
}

function plainText({ title, subtitle, sections }) {
  return [
    title,
    subtitle,
    ...(sections || []).flatMap((s) => [s.heading ? `${s.heading}:` : "", s.body]),
  ]
    .filter((x) => x != null && x !== "")
    .join("\n\n");
}

// Opens the user's email client with the document in the body. Long documents
// are trimmed (mailto limits vary by client); the note points to the full export.
export function emailDoc(opts) {
  logExportAction("email", opts.title);
  const text = plainText(opts);
  const clipped = text.length > 3800;
  const body = encodeURIComponent(
    text.slice(0, 3800) +
      (clipped ? "\n\n— Content trimmed for email. Use Print or PDF in CaseCue for the full document." : "")
  );
  window.location.href = `mailto:?subject=${encodeURIComponent(`${opts.title} — from CaseCue`)}&body=${body}`;
}

// Returns "shared" (OS share sheet), "copied" (no share support), or "failed".
export async function shareDoc(opts) {
  const text = plainText(opts);
  if (navigator.share) {
    try {
      await navigator.share({ title: opts.title, text });
      logExportAction("share", opts.title);
      return "shared";
    } catch {
      return "cancelled";
    }
  }
  try {
    await navigator.clipboard.writeText(text);
    logExportAction("share", opts.title);
    return "copied";
  } catch {
    return "failed";
  }
}