import { jsPDF } from "jspdf";
import logExportAction from "@/lib/exportAudit";

// Shared export pipeline for every generated CaseCue document.
// One HTML builder feeds Print and Word (DOCX); one jsPDF writer feeds PDF;
// a plain-text renderer feeds Email and Share. Every document carries the
// educator-review banner.

export const DEFAULT_BANNER = "DRAFT — Educator Review Required. Generated by CaseCue.";

const esc = (t) => String(t == null ? "" : t)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/\n/g, "<br>");

const safeName = (t) => String(t || "casecue-document").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").slice(0, 60);

export function buildDocHtml({ title, subtitle, sections, banner }) {
  const printed = new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" });
  const body = (sections || [])
    .map((s, index) => {
      const img = s.image
        ? `<div class="imgwrap"><img src="${s.image}" alt="" /></div>`
        : "";
      const text = s.body ? `<div class="ftext">${esc(s.body)}</div>` : "";
      return `<section class="case-section"><div class="section-kicker">SECTION ${String(index + 1).padStart(2, "0")}</div><h2>${esc(s.heading || "Details")}</h2>${img}${text}</section>`;
    })
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
  @page{size:auto;margin:0.55in 0.55in 0.7in;}
  *{box-sizing:border-box}
  body{font-family:Inter,Arial,Helvetica,sans-serif;color:#0f172a;margin:0;background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .page-shell{max-width:900px;margin:0 auto}
  .brandbar{display:flex;align-items:flex-start;justify-content:space-between;gap:22px;border:1px solid #dbeafe;background:linear-gradient(135deg,#07101f,#102b4d);color:#fff;padding:18px 20px;border-radius:14px}
  .brand{font-weight:900;letter-spacing:.14em;text-transform:uppercase;font-size:10px;color:#7dd3fc}
  .hdr h1{margin:5px 0 0;font-size:23px;line-height:1.15;letter-spacing:-.02em}
  .hdr .meta{font-size:10.5px;color:#cbd5e1;margin-top:6px}
  .printmeta{text-align:right;min-width:105px;color:#cbd5e1;font-size:9px;line-height:1.45}
  .printmeta b{display:block;color:#fff;font-size:10px;margin-bottom:2px}
  .case-section{break-inside:avoid;margin-top:16px;border:1px solid #e2e8f0;border-radius:14px;padding:16px 17px;background:#fff;box-shadow:0 1px 0 rgba(15,23,42,.03)}
  .section-kicker{font-size:8px;font-weight:900;letter-spacing:.16em;color:#64748b}
  h2{color:#0f172a;font-size:14px;margin:4px 0 9px;padding-bottom:8px;border-bottom:1px solid #e2e8f0}
  .ftext{font-size:11.25px;line-height:1.58;white-space:pre-wrap;color:#334155}
  .imgwrap{margin-top:8px;border:1px solid #e2e8f0;border-radius:10px;padding:8px;text-align:center}
  .imgwrap img{max-width:100%;height:auto}
  .banner{margin-top:16px;background:#eff6ff;border:1px solid #bfdbfe;color:#1e3a8a;padding:10px 13px;border-radius:10px;font-size:9.5px;font-weight:700}
  .footer{position:fixed;left:0.55in;right:0.55in;bottom:0.22in;display:flex;justify-content:space-between;border-top:1px solid #e2e8f0;padding-top:6px;font-size:8px;color:#64748b}
  @media print{.page-shell{max-width:none}.case-section{box-shadow:none}}
  </style></head><body>
  <div class="page-shell">
   <div class="brandbar"><div class="hdr"><div class="brand">CaseCue</div><h1>${esc(title)}</h1>${subtitle ? `<div class="meta">${esc(subtitle)}</div>` : ""}</div><div class="printmeta"><b>Printed</b>${esc(printed)}</div></div>
   ${body}
   <div class="banner">${esc(banner || DEFAULT_BANNER)}</div>
  </div>
  <div class="footer"><span>CaseCue · getcasecue.com</span><span>Printed ${esc(printed)}</span></div>
  </body></html>`;
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

// Opens a print-ready window. Returns false when pop-ups are blocked.
export function printDoc(opts) {
  const w = window.open("", "_blank");
  if (!w) return false;
  logExportAction("print", opts.title);
  w.document.write(buildDocHtml(opts));
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
  return true;
}

// Word-compatible DOCX (HTML-based, same approach as Lesson Studio exports).
export function exportDocDocx(opts) {
  logExportAction("docx", opts.title);
  downloadBlob(new Blob(["\ufeff", buildDocHtml(opts)], { type: "application/msword" }), `${safeName(opts.filename)}.doc`);
}

// PDF: normalize to base-14-safe ASCII so nothing renders as gaps or
// inconsistent glyphs in the exported file.
const pdfSafe = (t) => String(t == null ? "" : t)
  .replace(/\r\n?/g, "\n")
  .replace(/[\u2018\u2019\u201A\u201B\u2039\u203A]/g, "'")
  .replace(/[\u201C\u201D\u201E\u00AB\u00BB]/g, '"')
  .replace(/[\u2013\u2014\u2015]/g, "-")
  .replace(/\u2026/g, "...")
  .replace(/[\u2192\u21D2\u27A1]/g, "->")
  .replace(/\u2190/g, "<-")
  .replace(/\u2265/g, ">=")
  .replace(/\u2264/g, "<=")
  .replace(/\u2260/g, "!=")
  .replace(/[\u2022\u25CF\u25AA\u00B7]/g, "-")
  .replace(/\u200B/g, "")
  .replace(/[\u00A0\u2007\u2009\u202F]/g, " ")
  .replace(/\t/g, " ")
  .replace(/\*\*/g, "")
  .replace(/^#{1,6}[ \t]+/gm, "")
  .replace(/[ \t]{2,}/g, " ")
  .replace(/[^\n\x20-\x7E\xA1-\xFF]/g, "");

export function exportDocPdf({ title, subtitle, sections, banner, filename }) {
  logExportAction("pdf", title);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const PAGE_W = 595;
  const PAGE_H = 842;
  const M = 42;
  const CW = PAGE_W - M * 2;
  const printed = new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" });
  let y = M;

  const newPage = () => { doc.addPage(); y = M; };
  const ensure = (height) => { if (y + height > PAGE_H - 62) newPage(); };

  doc.setFillColor(7, 16, 31);
  doc.roundedRect(M, M, CW, 92, 12, 12, "F");
  doc.setTextColor(125, 211, 252);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("CASECUE", M + 16, M + 18);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  const titleLines = doc.splitTextToSize(pdfSafe(title), CW - 150);
  doc.text(titleLines, M + 16, M + 42);
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(203, 213, 225);
    const sub = doc.splitTextToSize(pdfSafe(subtitle), CW - 150);
    doc.text(sub, M + 16, M + 69);
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text("PRINTED", M + CW - 78, M + 24);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(203, 213, 225);
  doc.text(pdfSafe(printed), M + CW - 78, M + 39);
  y = M + 110;

  const drawSectionHeading = (heading, index) => {
    ensure(34);
    doc.setFillColor(234, 245, 255);
    doc.roundedRect(M, y, 28, 24, 7, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(7, 89, 133);
    doc.text(String(index + 1).padStart(2, "0"), M + 8, y + 15);
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    const h = doc.splitTextToSize(pdfSafe(heading || "Details"), CW - 42);
    doc.text(h, M + 38, y + 15);
    y += Math.max(32, h.length * 13 + 10);
  };

  const writeBody = (body) => {
    if (!body) return;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(pdfSafe(body), CW - 8);
    for (const line of lines) {
      if (y > PAGE_H - 72) {
        newPage();
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text("CaseCue · continued", M, y);
        y += 16;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(51, 65, 85);
      }
      doc.text(line || " ", M + 4, y);
      y += 13.5;
    }
    y += 8;
  };

  (sections || []).forEach((s, index) => {
    drawSectionHeading(s.heading, index);
    if (s.image && s.imageWidth && s.imageHeight) {
      let imgW = CW - 8;
      let imgH = imgW * (s.imageHeight / s.imageWidth);
      const maxH = PAGE_H - M * 2 - 80;
      if (imgH > maxH) { imgH = maxH; imgW = imgH * (s.imageWidth / s.imageHeight); }
      ensure(imgH + 16);
      try { doc.addImage(s.image, "PNG", M + 4, y, imgW, imgH); y += imgH + 10; } catch { /* skip unreadable image */ }
    }
    writeBody(s.body);
    doc.setDrawColor(226, 232, 240);
    doc.line(M, y, M + CW, y);
    y += 12;
  });

  const reviewText = pdfSafe(banner || DEFAULT_BANNER);
  const reviewLines = doc.splitTextToSize(reviewText, CW - 24);
  ensure(reviewLines.length * 11 + 28);
  doc.setFillColor(239, 246, 255);
  doc.setDrawColor(191, 219, 254);
  doc.roundedRect(M, y, CW, reviewLines.length * 11 + 20, 8, 8, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(30, 64, 175);
  doc.text(reviewLines, M + 12, y + 14);

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setDrawColor(226, 232, 240);
    doc.line(M, PAGE_H - 35, PAGE_W - M, PAGE_H - 35);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text("CaseCue · getcasecue.com", M, PAGE_H - 21);
    doc.text(`Printed ${pdfSafe(printed)} · Page ${p} of ${pages}`, PAGE_W - M, PAGE_H - 21, { align: "right" });
  }

  doc.save(`${safeName(filename)}.pdf`);
}

function plainText({ title, subtitle, sections }) {
  return [
    title,
    subtitle,
    ...(sections || []).flatMap((s) => [s.heading ? `${s.heading}:` : "", s.body]),
  ]
    .filter((x) => x != null && x !== "")
    .join("\n\n");
}

// Opens the user's email client with the document in the body. Long documents
// are trimmed (mailto limits vary by client); the note points to the full export.
export function emailDoc(opts) {
  logExportAction("email", opts.title);
  const text = plainText(opts);
  const clipped = text.length > 3800;
  const body = encodeURIComponent(
    text.slice(0, 3800) +
      (clipped ? "\n\n— Content trimmed for email. Use Print or PDF in CaseCue for the full document." : "")
  );
  window.location.href = `mailto:?subject=${encodeURIComponent(`${opts.title} — from CaseCue`)}&body=${body}`;
}

// Returns "shared" (OS share sheet), "copied" (no share support), or "failed".
export async function shareDoc(opts) {
  const text = plainText(opts);
  if (navigator.share) {
    try {
      await navigator.share({ title: opts.title, text });
      logExportAction("share", opts.title);
      return "shared";
    } catch {
      return "cancelled";
    }
  }
  try {
    await navigator.clipboard.writeText(text);
    logExportAction("share", opts.title);
    return "copied";
  } catch {
    return "failed";
  }
}