export const LESSON_HEADER_FIELDS=[{key:'title',label:'Lesson title',type:'input'},{key:'teacher',label:'Teacher',type:'input'},{key:'date',label:'Date',type:'input'},{key:'subject_skill',label:'Subject and skill',type:'input'},{key:'grade_group',label:'Grade or instructional group',type:'input'},{key:'duration',label:'Estimated duration',type:'input'}];
export const SPECIAL_ACCOMMODATION_KEY='accommodations_note';
export const LESSON_GROUPS=[
 {title:'Assignment Alignment',fields:[{key:'assignment_skill_targets',label:'Assignment skill targets',rows:3},{key:'iep_goal_matches',label:'Verified IEP goal matches',rows:4},{key:'lesson_objective',label:'Assignment-aligned measurable objective',rows:3}]},
 {title:'Objectives & Hook',fields:[{key:'iep_objective',label:'IEP-aligned lesson objective',rows:3},{key:'i_can_statement',label:'Student-friendly “I can” statement',rows:2},{key:'essential_question',label:'Essential question (with suggested answer)',rows:2},{key:'standards_rationale',label:'Standards alignment rationale',rows:2},{key:'baseline_connection',label:'Present-level / baseline connection',rows:2},{key:'real_world_connection',label:'Real-world connection',rows:2}]},
 {title:'Materials & Readiness',fields:[{key:'materials',label:'Required materials & preparation',rows:3},{key:'academic_vocabulary',label:'Academic vocabulary',rows:4},{key:'prior_knowledge',label:'Prior knowledge / readiness check',rows:2}]},
 {title:'Opening the Lesson',fields:[{key:'anticipatory_set',label:'Anticipatory set / warm-up (3–5 min)',rows:4},{key:'brain_teasers',label:'Engaging opener questions with suggested answers',rows:3}]},
 {title:'Teach It',fields:[{key:'mini_lecture',label:'Full ready-to-read teacher script',rows:14},{key:'teacher_talk',label:'Keep it simple',rows:5},{key:'i_do',label:'I Do — teacher model (think-aloud)',rows:6}]},
 {title:'Guided & Independent Practice',fields:[{key:'we_do',label:'We Do — guided practice',rows:6},{key:'you_do',label:'You Do — independent practice',rows:6},{key:'checks_for_understanding',label:'Checks for understanding',rows:4},{key:'questioning_plan',label:'Questioning plan with expected answers',rows:4},{key:'example_student_response',label:'Example student response',rows:4},{key:'example_explanation',label:'Teacher explanation of the example',rows:3},{key:'misconceptions',label:'Possible misconceptions & exact corrections',rows:4}]},
 {title:'Support & Differentiation',fields:[{key:'differentiation',label:'Differentiation (emerging / developing / advanced)',rows:5},{key:'small_group_plan',label:'Small-group instructional plan',rows:4},{key:'behavior_engagement_plan',label:'Engagement supports',rows:3}]},
 {title:'Data & Progress Monitoring',fields:[{key:'progress_monitoring',label:'Progress-monitoring / instructional measurement',rows:5},{key:'quantitative_table',label:'Quantitative data-collection table',rows:6},{key:'qualitative_template',label:'Qualitative session-note template',rows:4},{key:'quick_check',label:'Quick check / exit ticket',rows:4},{key:'answer_key',label:'Answer key / scoring guide',rows:6},{key:'mastery_criterion',label:'Mastery / lesson success criterion',rows:3},{key:'reteach_plan',label:'Reteach / extension decision rule',rows:4},{key:'evidence_to_save',label:'Evidence to retain in CaseCue',rows:4},{key:'cm_hub_note',label:'CaseCue Session Tracker note',rows:3}]},
 {title:'Reflection & Next Steps',fields:[{key:'teacher_reflection',label:'Teacher reflection prompts',rows:4},{key:'next_step',label:'Recommended next instructional step',rows:3}]}
];
export const ALL_PLAN_KEYS=[...LESSON_HEADER_FIELDS.map(f=>f.key),...LESSON_GROUPS.flatMap(g=>g.fields.map(f=>f.key)),SPECIAL_ACCOMMODATION_KEY];
export function normalizePlan(plan){const base={};ALL_PLAN_KEYS.forEach(k=>{base[k]=plan?.[k]!=null?String(plan[k]):''});return base;}