import { jsPDF } from "jspdf";

// Shared PDF layout helpers for CaseCue document exports (IEP drafts, progress reports).

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;

function newDoc(title) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(60, 40, 120);
  doc.text(title, MARGIN, MARGIN);
  return doc;
}

function writeBlock(doc, y, text, { size = 11, bold = false, color = [40, 40, 40], gap = 6 } = {}) {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(size);
  doc.setTextColor(...color);
  const lines = doc.splitTextToSize(String(text ?? "—"), CONTENT_W);
  for (const line of lines) {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN; }
    doc.text(line, MARGIN, y);
    y += size * 1.35;
  }
  return y + gap;
}

function addFooter(doc, text) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text(text, MARGIN, PAGE_H - 24);
  }
}

function studentHeader(doc, y, student, subtitle) {
  y = writeBlock(doc, y, `${student.first_name} ${student.last_name}`, { size: 13, bold: true, color: [30, 30, 30], gap: 2 });
  const meta = [
    student.grade ? `Grade ${student.grade}` : null,
    student.eligibility_category,
    subtitle,
  ].filter(Boolean).join(" · ");
  if (meta) y = writeBlock(doc, y, meta, { size: 10, color: [110, 110, 110], gap: 12 });
  return y;
}

export function exportIepPdf(student, goals) {
  const doc = newDoc("Individualized Education Program — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student, [
    student.iep_date ? `IEP date: ${student.iep_date}` : null,
    student.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
    student.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
  ].filter(Boolean).join(" · "));

  const sections = [
    ["Strengths", student.strengths],
    ["Areas of Need", student.areas_of_need],
    ["Present Levels of Academic Achievement & Functional Performance", student.present_levels],
    ["Accommodations", student.accommodations],
    ["Services", Array.isArray(student.services) && student.services.length ? student.services.join(", ") : null],
  ];
  for (const [title, body] of sections) {
    y = writeBlock(doc, y, title, { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, body || "—");
  }

  y = writeBlock(doc, y, "Annual Goals", { size: 12, bold: true, color: [109, 40, 217], gap: 4 });
  const gs = goals && goals.length ? goals : [];
  gs.forEach((g, i) => {
    y = writeBlock(doc, y, `Goal ${i + 1} — ${g.goal_area || "General"} (${g.status || "active"})`, { size: 11, bold: true, color: [30, 30, 30], gap: 2 });
    y = writeBlock(doc, y, g.goal_text || "—", { gap: 2 });
    y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"} · Measured by: ${g.measurement_method || "—"}`, { size: 10, color: [110, 110, 110] });
  });
  if (!gs.length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue.");
  doc.save(`IEP-Draft-${student.first_name}-${student.last_name}.pdf`);
}

export function exportProgressReportPdf(student, report) {
  const doc = newDoc("Progress Report — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student, `Reporting through ${report.generated_at || new Date().toISOString().slice(0, 10)}`);

  const statsByArea = new Map((report.stats || []).map((s) => [s.goal_area, s]));
  for (const gr of report.goal_reports || []) {
    const s = statsByArea.get(gr.goal_area) || {};
    y = writeBlock(doc, y, gr.goal_area, { size: 12, bold: true, color: [109, 40, 217], gap: 2 });
    const statLine = [
      s.baseline ? `Baseline: ${s.baseline}` : null,
      s.target ? `Target: ${s.target}` : null,
      s.latest_percentage != null ? `Latest: ${s.latest_percentage}% (${s.latest_date || ""})` : null,
      s.average_percentage != null ? `Average: ${s.average_percentage}%` : null,
      `Data points: ${s.data_points ?? 0}`,
    ].filter(Boolean).join(" · ");
    y = writeBlock(doc, y, statLine, { size: 10, color: [110, 110, 110], gap: 3 });
    y = writeBlock(doc, y, gr.statement);
  }
  if (!report.goal_reports?.length) y = writeBlock(doc, y, "No goal reports in this draft.", { size: 10, color: [110, 110, 110] });

  if (report.teacher_notes) {
    y = writeBlock(doc, y, "Teacher Notes", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, report.teacher_notes, { size: 10, color: [90, 90, 90] });
  }

  y = writeBlock(doc, y, "Overall Summary", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, report.overall_summary || "—");

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from your recorded data.");
  doc.save(`Progress-Report-${student.first_name}-${student.last_name}.pdf`);
}

function csvEscape(v) {
  const s = String(v ?? "").replace(/\r?\n/g, " ");
  return `"${s.replace(/"/g, '""')}"`;
}

function latestReportByStudent(reports) {
  const byStudent = new Map();
  for (const r of reports || []) {
    if (!byStudent.has(r.student_id)) byStudent.set(r.student_id, r);
  }
  return byStudent;
}

// Bulk export: one CSV row per student/goal with IEP data + latest saved progress report.
export function exportBulkCsv(students, goals, reports) {
  const goalsByStudent = new Map();
  for (const g of goals || []) {
    if (!goalsByStudent.has(g.student_id)) goalsByStudent.set(g.student_id, []);
    goalsByStudent.get(g.student_id).push(g);
  }
  const reportsByStudent = latestReportByStudent(reports);

  const header = [
    "Student", "Grade", "Eligibility", "IEP Date", "Annual Review Due", "Reevaluation Due",
    "Present Levels", "Accommodations", "Services",
    "Goal Area", "Goal Text", "Baseline", "Target", "Criterion", "Measurement Method", "Goal Status",
    "Latest Progress Report Date", "Latest Report Overall Summary",
  ];
  const rows = [];
  for (const s of students || []) {
    const svcs = Array.isArray(s.services) ? s.services.join("; ") : "";
    const base = [
      `${s.first_name} ${s.last_name}`, s.grade, s.eligibility_category, s.iep_date,
      s.annual_review_due, s.reevaluation_due, s.present_levels, s.accommodations, svcs,
    ];
    const report = reportsByStudent.get(s.id);
    const reportCells = [
      report ? (report.created_date || "").slice(0, 10) : "",
      report?.content?.overall_summary || "",
    ];
    const studentGoals = goalsByStudent.get(s.id) || [];
    if (studentGoals.length) {
      for (const g of studentGoals) {
        rows.push([...base, g.goal_area, g.goal_text, g.baseline, g.target, g.criterion, g.measurement_method, g.status, ...reportCells]);
      }
    } else {
      rows.push([...base, "", "", "", "", "", "", "", ...reportCells]);
    }
  }

  const csv = [header, ...rows].map((r) => r.map(csvEscape).join(",")).join("\n");
  const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `CaseCue-Records-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// Bulk export: a single PDF records binder — one section per student with IEP data, goals, and latest saved progress report.
export function exportBulkRecordsPdf(students, goals, reports) {
  const goalsByStudent = new Map();
  for (const g of goals || []) {
    if (!goalsByStudent.has(g.student_id)) goalsByStudent.set(g.student_id, []);
    goalsByStudent.get(g.student_id).push(g);
  }
  const reportsByStudent = latestReportByStudent(reports);

  const doc = newDoc("Caseload Records Export");
  let y = MARGIN + 28;
  y = writeBlock(doc, y, `${(students || []).length} student${(students || []).length === 1 ? "" : "s"} · exported ${new Date().toISOString().slice(0, 10)}`, { size: 10, color: [110, 110, 110], gap: 10 });

  (students || []).forEach((student, idx) => {
    if (idx > 0) { doc.addPage(); y = MARGIN; }
    y = studentHeader(doc, y, student, [
      student.iep_date ? `IEP date: ${student.iep_date}` : null,
      student.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
      student.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
    ].filter(Boolean).join(" · "));

    const sections = [
      ["Present Levels", student.present_levels],
      ["Accommodations", student.accommodations],
      ["Services", Array.isArray(student.services) && student.services.length ? student.services.join(", ") : null],
    ];
    for (const [title, body] of sections) {
      y = writeBlock(doc, y, title, { size: 11, bold: true, color: [109, 40, 217], gap: 3 });
      y = writeBlock(doc, y, body || "—", { size: 10 });
    }

    y = writeBlock(doc, y, "Goals", { size: 11, bold: true, color: [109, 40, 217], gap: 3 });
    const gs = goalsByStudent.get(student.id) || [];
    gs.forEach((g, i) => {
      y = writeBlock(doc, y, `${i + 1}. ${g.goal_area || "General"} (${g.status || "active"}) — ${g.goal_text || "—"}`, { size: 10, gap: 1 });
      y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"}`, { size: 9, color: [110, 110, 110] });
    });
    if (!gs.length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

    const report = reportsByStudent.get(student.id);
    y = writeBlock(doc, y, "Latest Saved Progress Report", { size: 11, bold: true, color: [109, 40, 217], gap: 3 });
    if (report?.content) {
      y = writeBlock(doc, y, `Saved ${(report.created_date || "").slice(0, 10)}`, { size: 9, color: [110, 110, 110], gap: 4 });
      for (const gr of report.content.goal_reports || []) {
        y = writeBlock(doc, y, `${gr.goal_area}`, { size: 10, bold: true, gap: 1 });
        y = writeBlock(doc, y, gr.statement || "—", { size: 10, gap: 3 });
      }
      if (report.content.teacher_notes) {
        y = writeBlock(doc, y, "Teacher notes", { size: 10, bold: true, gap: 1 });
        y = writeBlock(doc, y, report.content.teacher_notes, { size: 10, gap: 3 });
      }
      y = writeBlock(doc, y, report.content.overall_summary || "—", { size: 10 });
    } else {
      y = writeBlock(doc, y, "No saved progress report.", { size: 10, color: [110, 110, 110] });
    }
  });

  addFooter(doc, "Caseload records export — generated by CaseCue from your recorded data. Verify before distribution.");
  doc.save(`CaseCue-Records-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// Meeting packet: agenda, student profile, goals with progress, and discussion notes — one document for an IEP team meeting.
export function exportMeetingPacketPdf(meeting, student, goals = [], progress = []) {
  const doc = newDoc("Meeting Packet — DRAFT");
  let y = MARGIN + 28;

  y = writeBlock(doc, y, meeting.title || "Team Meeting", { size: 12, bold: true, color: [109, 40, 217], gap: 2 });
  const meta = [
    meeting.meeting_type,
    meeting.date,
    meeting.time,
    meeting.status ? `Status: ${meeting.status}` : null,
  ].filter(Boolean).join(" · ");
  if (meta) y = writeBlock(doc, y, meta, { size: 10, color: [110, 110, 110], gap: 12 });

  y = studentHeader(doc, y, student, [
    student?.iep_date ? `IEP date: ${student.iep_date}` : null,
    student?.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
    student?.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
  ].filter(Boolean).join(" · "));

  y = writeBlock(doc, y, "Agenda", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, meeting.agenda || "No agenda recorded.");
  for (const [label, value] of [["Parent concerns", meeting.parent_concerns], ["Teacher concerns", meeting.teacher_concerns]]) {
    if (!value) continue;
    y = writeBlock(doc, y, label, { size: 11, bold: true, color: [109, 40, 217], gap: 2 });
    y = writeBlock(doc, y, value, { size: 10 });
  }

  y = writeBlock(doc, y, "Goals & Progress", { size: 12, bold: true, color: [109, 40, 217], gap: 4 });
  (goals || []).forEach((g, i) => {
    y = writeBlock(doc, y, `Goal ${i + 1} — ${g.goal_area || "General"} (${g.status || "active"})`, { size: 11, bold: true, color: [30, 30, 30], gap: 2 });
    y = writeBlock(doc, y, g.goal_text || "—", { size: 10, gap: 2 });
    y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"}`, { size: 9, color: [110, 110, 110] });
    const points = (progress || []).filter((p) => p.goal_id === g.id).sort((a, b) => (a.date || "").localeCompare(b.date || ""));
    for (const p of points) {
      y = writeBlock(doc, y, `${p.date || "—"}: ${p.percentage != null ? `${p.percentage}%` : (p.correct != null && p.total ? `${p.correct}/${p.total}` : "recorded")}${p.prompting_level && p.prompting_level !== "independent" ? ` · prompting: ${p.prompting_level}` : ""}`, { size: 9, color: [90, 90, 90], gap: 0 });
    }
    if (!points.length) y = writeBlock(doc, y, "No progress data recorded yet.", { size: 9, color: [130, 130, 130], gap: 0 });
    y += 6;
  });
  if (!(goals || []).length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

  y = writeBlock(doc, y, "Accommodations", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, student?.accommodations || "—", { size: 10 });
  y = writeBlock(doc, y, "Services", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, (Array.isArray(student?.services) && student.services.length ? student.services.join(", ") : null) || "—", { size: 10 });
  y = writeBlock(doc, y, "Discussion Notes", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, meeting.notes || "—", { size: 10 });
  if (meeting.follow_up_tasks) {
    y = writeBlock(doc, y, "Follow-Up Tasks", { size: 11, bold: true, color: [109, 40, 217], gap: 2 });
    y = writeBlock(doc, y, meeting.follow_up_tasks, { size: 10 });
  }

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from your recorded data.");
  doc.save(`Meeting-Packet-${student?.first_name || "Sample"}-${student?.last_name || "Student"}.pdf`);
}

// New IEP Workspace draft: full section-by-section draft with citations, goals, accommodations,
// service minutes, placement worksheet, and unresolved team decisions — one exportable draft.
export function exportIepWorkspacePdf(student, draft, placement) {
  const d = draft || {};
  const doc = newDoc("New IEP Draft — CaseCue Workspace");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student || {}, "Generated from the New IEP Workspace");

  for (const s of d.sections || []) {
    y = writeBlock(doc, y, `${s.title || s.key} — ${(s.status || "draft").toUpperCase()}`, { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, s.content || "—", { size: 10 });
    if (Array.isArray(s.citations) && s.citations.length) {
      y = writeBlock(doc, y, `Sources: ${s.citations.join("; ")}`, { size: 9, color: [110, 110, 110], gap: 8 });
    }
  }

  y = writeBlock(doc, y, "Measurable Annual Goals", { size: 12, bold: true, color: [109, 40, 217], gap: 4 });
  (d.goals || []).forEach((g, i) => {
    y = writeBlock(doc, y, `Goal ${i + 1} — ${g.goal_area || "General"} (${g.status || "draft"})`, { size: 11, bold: true, gap: 2 });
    y = writeBlock(doc, y, [g.conditions, g.action, g.target ? `Target: ${g.target}` : null, g.criterion ? `Criterion: ${g.criterion}` : null].filter(Boolean).join(" "), { size: 10, gap: 2 });
    y = writeBlock(doc, y, `Baseline: ${g.baseline || "Needs verification"} · Measured by: ${g.measurement_method || "—"} · Schedule: ${g.data_schedule || "—"}`, { size: 9, color: [110, 110, 110] });
  });
  if (!(d.goals || []).length) y = writeBlock(doc, y, "No goals in this draft.", { size: 10, color: [110, 110, 110] });

  y = writeBlock(doc, y, "Accommodations", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  (d.accommodations || []).forEach((a) => {
    y = writeBlock(doc, y, `${a.accommodation} (${a.change_type || "new"}) — Need: ${a.need_addressed || "—"} · Source: ${a.source || "Needs verification"}`, { size: 10, gap: 2 });
  });
  if (!(d.accommodations || []).length) y = writeBlock(doc, y, "No accommodations in this draft.", { size: 10, color: [110, 110, 110] });

  y = writeBlock(doc, y, "Service Minutes", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  let weeklyTotal = 0;
  (d.services || []).forEach((s) => {
    const weekly = (Number(s.minutes_per_session) || 0) * (Number(s.sessions_per_week) || 0);
    weeklyTotal += weekly;
    y = writeBlock(doc, y, `${s.service} — ${s.delivery || "—"} · ${s.minutes_per_session ?? "?"} min × ${s.sessions_per_week ?? "?"}/wk = ${weekly} min/wk · ${s.service_type || "direct"} · ${s.location || "—"}`, { size: 10, gap: 1 });
    y = writeBlock(doc, y, `Need/Goal: ${s.need_or_goal || "Needs verification"} · Provider: ${s.provider || "Team decision required"}`, { size: 9, color: [110, 110, 110] });
  });
  if (d.services?.length) y = writeBlock(doc, y, `Total: ${weeklyTotal} minutes per week · ${weeklyTotal * 4} minutes per month (approx.)`, { size: 10, bold: true, gap: 8 });
  else y = writeBlock(doc, y, "No services in this draft.", { size: 10, color: [110, 110, 110] });

  if (placement && Number(placement.instructional_minutes_per_day) > 0) {
    const perDay = Number(placement.instructional_minutes_per_day) || 0;
    const days = Number(placement.instructional_days_per_week) || 0;
    const inside = Number(placement.minutes_inside_ge) || 0;
    const outside = Number(placement.minutes_outside_ge) || 0;
    const total = perDay * days;
    y = writeBlock(doc, y, "Placement Percentage — Calculation for Team Verification", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, `Formula: (minutes inside/outside general education ÷ total instructional minutes) × 100`, { size: 9, color: [110, 110, 110], gap: 2 });
    y = writeBlock(doc, y, `Instructional minutes: ${perDay}/day × ${days} days/week = ${total} min/week · Inside GE: ${inside} min (${total ? Math.round((inside / total) * 100) : 0}%) · Outside GE: ${outside} min (${total ? Math.round((outside / total) * 100) : 0}%)`, { size: 10, gap: 2 });
    y = writeBlock(doc, y, "Teacher verification of instructional minutes, schedules, and local calculation rules required.", { size: 9, color: [110, 110, 110], gap: 8 });
  }

  if (Array.isArray(d.unresolved_decisions) && d.unresolved_decisions.length) {
    y = writeBlock(doc, y, "Unresolved Team Decisions", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    d.unresolved_decisions.forEach((u, i) => { y = writeBlock(doc, y, `${i + 1}. ${u}`, { size: 10, gap: 1 }); });
  }

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from uploaded documents and verified records. CaseCue never finalizes an IEP.");
  doc.save(`New-IEP-Draft-${student?.first_name || "Student"}-${student?.last_name || ""}.pdf`);
}

// Source-citation report: every extracted fact with its source document, page, excerpt, confidence, and verification state.
export function exportWorkspaceCitationsPdf(student, analysis) {
  const doc = newDoc("Source-Citation Report — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student || {}, "New IEP Workspace document extraction");

  const a = analysis || {};
  y = writeBlock(doc, y, `Extracted facts: ${(a.facts || []).length} · Gaps: ${(a.gaps || []).length} · Conflicts: ${(a.conflicts || []).length}`, { size: 10, color: [110, 110, 110], gap: 10 });

  (a.facts || []).forEach((f, i) => {
    y = writeBlock(doc, y, `Fact ${i + 1} — ${f.verified ? "VERIFIED" : "NEEDS VERIFICATION"} (${f.confidence || "medium"} confidence)`, { size: 11, bold: true, gap: 2 });
    y = writeBlock(doc, y, f.fact || "—", { size: 10, gap: 2 });
    if (f.excerpt) y = writeBlock(doc, y, `“${f.excerpt}”`, { size: 9, color: [110, 110, 110], gap: 1 });
    y = writeBlock(doc, y, `Source: ${f.source_document || "—"} · p. ${f.page || "—"}${f.category ? ` · ${f.category}` : ""}`, { size: 9, color: [110, 110, 110], gap: 6 });
  });

  if ((a.gaps || []).length) {
    y = writeBlock(doc, y, "Missing or Outdated Information", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    a.gaps.forEach((g, i) => { y = writeBlock(doc, y, `${i + 1}. ${g.issue}${g.detail ? ` — ${g.detail}` : ""}`, { size: 10, gap: 1 }); });
    y += 6;
  }
  if ((a.conflicts || []).length) {
    y = writeBlock(doc, y, "Conflicting Information", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    a.conflicts.forEach((c, i) => { y = writeBlock(doc, y, `${i + 1}. ${c.description}`, { size: 10, gap: 1 }); });
  }

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from uploaded documents.");
  doc.save(`Source-Citations-${student?.first_name || "Student"}-${student?.last_name || ""}.pdf`);
}

// CaseCue Review report: score, category scores, and every finding with its suggested action.
export function exportWorkspaceReviewPdf(student, review) {
  const doc = newDoc("CaseCue Review Report — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student || {}, `Draft review score: ${review?.score != null ? `${Math.round(review.score)}/100` : "—"}`);

  if (review?.category_scores) {
    y = writeBlock(doc, y, Object.entries(review.category_scores).map(([k, v]) => `${k.replace(/_/g, " ")}: ${v != null ? Math.round(v) : "—"}`).join(" · "), { size: 10, color: [110, 110, 110], gap: 10 });
  }

  y = writeBlock(doc, y, "Summary", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, review?.summary || "—", { size: 10, gap: 10 });

  y = writeBlock(doc, y, "Findings", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  (review?.findings || []).forEach((f, i) => {
    y = writeBlock(doc, y, `${i + 1}. [${(f.level || "").toUpperCase()}] ${f.title} (${f.category || "—"})`, { size: 11, bold: true, gap: 2 });
    y = writeBlock(doc, y, f.what_found || "—", { size: 10, gap: 1 });
    if (f.why_flagged) y = writeBlock(doc, y, `Why flagged: ${f.why_flagged}`, { size: 9, color: [110, 110, 110], gap: 1 });
    if (f.suggested_action) y = writeBlock(doc, y, `Suggested action: ${f.suggested_action}`, { size: 9, color: [110, 110, 110], gap: 5 });
  });
  if (!(review?.findings || []).length) y = writeBlock(doc, y, "No findings recorded.", { size: 10, color: [110, 110, 110] });

  addFooter(doc, "Potential issues for educator review only — CaseCue never claims compliance or makes decisions.");
  doc.save(`CaseCue-Review-${student?.first_name || "Student"}-${student?.last_name || ""}.pdf`);
}