import { jsPDF } from "jspdf";

// Shared PDF layout helpers for CaseCue document exports (IEP drafts, progress reports).

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;

function newDoc(title) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(60, 40, 120);
  doc.text(title, MARGIN, MARGIN);
  return doc;
}

function writeBlock(doc, y, text, { size = 11, bold = false, color = [40, 40, 40], gap = 6 } = {}) {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(size);
  doc.setTextColor(...color);
  const lines = doc.splitTextToSize(String(text ?? "—"), CONTENT_W);
  for (const line of lines) {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN; }
    doc.text(line, MARGIN, y);
    y += size * 1.35;
  }
  return y + gap;
}

function addFooter(doc, text) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text(text, MARGIN, PAGE_H - 24);
  }
}

function studentHeader(doc, y, student, subtitle) {
  y = writeBlock(doc, y, `${student.first_name} ${student.last_name}`, { size: 13, bold: true, color: [30, 30, 30], gap: 2 });
  const meta = [
    student.grade ? `Grade ${student.grade}` : null,
    student.eligibility_category,
    subtitle,
  ].filter(Boolean).join(" · ");
  if (meta) y = writeBlock(doc, y, meta, { size: 10, color: [110, 110, 110], gap: 12 });
  return y;
}

export function exportIepPdf(student, goals) {
  const doc = newDoc("Individualized Education Program — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student, [
    student.iep_date ? `IEP date: ${student.iep_date}` : null,
    student.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
    student.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
  ].filter(Boolean).join(" · "));

  const sections = [
    ["Strengths", student.strengths],
    ["Areas of Need", student.areas_of_need],
    ["Present Levels of Academic Achievement & Functional Performance", student.present_levels],
    ["Accommodations", student.accommodations],
    ["Services", Array.isArray(student.services) && student.services.length ? student.services.join(", ") : null],
  ];
  for (const [title, body] of sections) {
    y = writeBlock(doc, y, title, { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, body || "—");
  }

  y = writeBlock(doc, y, "Annual Goals", { size: 12, bold: true, color: [109, 40, 217], gap: 4 });
  const gs = goals && goals.length ? goals : [];
  gs.forEach((g, i) => {
    y = writeBlock(doc, y, `Goal ${i + 1} — ${g.goal_area || "General"} (${g.status || "active"})`, { size: 11, bold: true, color: [30, 30, 30], gap: 2 });
    y = writeBlock(doc, y, g.goal_text || "—", { gap: 2 });
    y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"} · Measured by: ${g.measurement_method || "—"}`, { size: 10, color: [110, 110, 110] });
  });
  if (!gs.length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue.");
  doc.save(`IEP-Draft-${student.first_name}-${student.last_name}.pdf`);
}

export function exportProgressReportPdf(student, report) {
  const doc = newDoc("Progress Report — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student, `Reporting through ${report.generated_at || new Date().toISOString().slice(0, 10)}`);

  const statsByArea = new Map((report.stats || []).map((s) => [s.goal_area, s]));
  for (const gr of report.goal_reports || []) {
    const s = statsByArea.get(gr.goal_area) || {};
    y = writeBlock(doc, y, gr.goal_area, { size: 12, bold: true, color: [109, 40, 217], gap: 2 });
    const statLine = [
      s.baseline ? `Baseline: ${s.baseline}` : null,
      s.target ? `Target: ${s.target}` : null,
      s.latest_percentage != null ? `Latest: ${s.latest_percentage}% (${s.latest_date || ""})` : null,
      s.average_percentage != null ? `Average: ${s.average_percentage}%` : null,
      `Data points: ${s.data_points ?? 0}`,
    ].filter(Boolean).join(" · ");
    y = writeBlock(doc, y, statLine, { size: 10, color: [110, 110, 110], gap: 3 });
    y = writeBlock(doc, y, gr.statement);
  }
  if (!report.goal_reports?.length) y = writeBlock(doc, y, "No goal reports in this draft.", { size: 10, color: [110, 110, 110] });

  if (report.teacher_notes) {
    y = writeBlock(doc, y, "Teacher Notes", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, report.teacher_notes, { size: 10, color: [90, 90, 90] });
  }

  y = writeBlock(doc, y, "Overall Summary", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, report.overall_summary || "—");

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from your recorded data.");
  doc.save(`Progress-Report-${student.first_name}-${student.last_name}.pdf`);
}

function csvEscape(v) {
  const s = String(v ?? "").replace(/\r?\n/g, " ");
  return `"${s.replace(/"/g, '""')}"`;
}

function latestReportByStudent(reports) {
  const byStudent = new Map();
  for (const r of reports || []) {
    if (!byStudent.has(r.student_id)) byStudent.set(r.student_id, r);
  }
  return byStudent;
}

// Bulk export: one CSV row per student/goal with IEP data + latest saved progress report.
export function exportBulkCsv(students, goals, reports) {
  const goalsByStudent = new Map();
  for (const g of goals || []) {
    if (!goalsByStudent.has(g.student_id)) goalsByStudent.set(g.student_id, []);
    goalsByStudent.get(g.student_id).push(g);
  }
  const reportsByStudent = latestReportByStudent(reports);

  const header = [
    "Student", "Grade", "Eligibility", "IEP Date", "Annual Review Due", "Reevaluation Due",
    "Present Levels", "Accommodations", "Services",
    "Goal Area", "Goal Text", "Baseline", "Target", "Criterion", "Measurement Method", "Goal Status",
    "Latest Progress Report Date", "Latest Report Overall Summary",
  ];
  const rows = [];
  for (const s of students || []) {
    const svcs = Array.isArray(s.services) ? s.services.join("; ") : "";
    const base = [
      `${s.first_name} ${s.last_name}`, s.grade, s.eligibility_category, s.iep_date,
      s.annual_review_due, s.reevaluation_due, s.present_levels, s.accommodations, svcs,
    ];
    const report = reportsByStudent.get(s.id);
    const reportCells = [
      report ? (report.created_date || "").slice(0, 10) : "",
      report?.content?.overall_summary || "",
    ];
    const studentGoals = goalsByStudent.get(s.id) || [];
    if (studentGoals.length) {
      for (const g of studentGoals) {
        rows.push([...base, g.goal_area, g.goal_text, g.baseline, g.target, g.criterion, g.measurement_method, g.status, ...reportCells]);
      }
    } else {
      rows.push([...base, "", "", "", "", "", "", "", ...reportCells]);
    }
  }

  const csv = [header, ...rows].map((r) => r.map(csvEscape).join(",")).join("\n");
  const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `CaseCue-Records-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// Bulk export: a single PDF records binder — one section per student with IEP data, goals, and latest saved progress report.
export function exportBulkRecordsPdf(students, goals, reports) {
  const goalsByStudent = new Map();
  for (const g of goals || []) {
    if (!goalsByStudent.has(g.student_id)) goalsByStudent.set(g.student_id, []);
    goalsByStudent.get(g.student_id).push(g);
  }
  const reportsByStudent = latestReportByStudent(reports);

  const doc = newDoc("Caseload Records Export");
  let y = MARGIN + 28;
  y = writeBlock(doc, y, `${(students || []).length} student${(students || []).length === 1 ? "" : "s"} · exported ${new Date().toISOString().slice(0, 10)}`, { size: 10, color: [110, 110, 110], gap: 10 });

  (students || []).forEach((student, idx) => {
    if (idx > 0) { doc.addPage(); y = MARGIN; }
    y = studentHeader(doc, y, student, [
      student.iep_date ? `IEP date: ${student.iep_date}` : null,
      student.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
      student.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
    ].filter(Boolean).join(" · "));

    const sections = [
      ["Present Levels", student.present_levels],
      ["Accommodations", student.accommodations],
      ["Services", Array.isArray(student.services) && student.services.length ? student.services.join(", ") : null],
    ];
    for (const [title, body] of sections) {
      y = writeBlock(doc, y, title, { size: 11, bold: true, color: [109, 40, 217], gap: 3 });
      y = writeBlock(doc, y, body || "—", { size: 10 });
    }

    y = writeBlock(doc, y, "Goals", { size: 11, bold: true, color: [109, 40, 217], gap: 3 });
    const gs = goalsByStudent.get(student.id) || [];
    gs.forEach((g, i) => {
      y = writeBlock(doc, y, `${i + 1}. ${g.goal_area || "General"} (${g.status || "active"}) — ${g.goal_text || "—"}`, { size: 10, gap: 1 });
      y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"}`, { size: 9, color: [110, 110, 110] });
    });
    if (!gs.length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

    const report = reportsByStudent.get(student.id);
    y = writeBlock(doc, y, "Latest Saved Progress Report", { size: 11, bold: true, color: [109, 40, 217], gap: 3 });
    if (report?.content) {
      y = writeBlock(doc, y, `Saved ${(report.created_date || "").slice(0, 10)}`, { size: 9, color: [110, 110, 110], gap: 4 });
      for (const gr of report.content.goal_reports || []) {
        y = writeBlock(doc, y, `${gr.goal_area}`, { size: 10, bold: true, gap: 1 });
        y = writeBlock(doc, y, gr.statement || "—", { size: 10, gap: 3 });
      }
      if (report.content.teacher_notes) {
        y = writeBlock(doc, y, "Teacher notes", { size: 10, bold: true, gap: 1 });
        y = writeBlock(doc, y, report.content.teacher_notes, { size: 10, gap: 3 });
      }
      y = writeBlock(doc, y, report.content.overall_summary || "—", { size: 10 });
    } else {
      y = writeBlock(doc, y, "No saved progress report.", { size: 10, color: [110, 110, 110] });
    }
  });

  addFooter(doc, "Caseload records export — generated by CaseCue from your recorded data. Verify before distribution.");
  doc.save(`CaseCue-Records-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// Meeting packet: agenda, student profile, goals with progress, and discussion notes — one document for an IEP team meeting.
export function exportMeetingPacketPdf(meeting, student, goals = [], progress = []) {
  const doc = newDoc("Meeting Packet — DRAFT");
  let y = MARGIN + 28;

  y = writeBlock(doc, y, meeting.title || "Team Meeting", { size: 12, bold: true, color: [109, 40, 217], gap: 2 });
  const meta = [
    meeting.meeting_type,
    meeting.date,
    meeting.time,
    meeting.status ? `Status: ${meeting.status}` : null,
  ].filter(Boolean).join(" · ");
  if (meta) y = writeBlock(doc, y, meta, { size: 10, color: [110, 110, 110], gap: 12 });

  y = studentHeader(doc, y, student, [
    student?.iep_date ? `IEP date: ${student.iep_date}` : null,
    student?.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
    student?.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
  ].filter(Boolean).join(" · "));

  y = writeBlock(doc, y, "Agenda", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, meeting.agenda || "No agenda recorded.");
  for (const [label, value] of [["Parent concerns", meeting.parent_concerns], ["Teacher concerns", meeting.teacher_concerns]]) {
    if (!value) continue;
    y = writeBlock(doc, y, label, { size: 11, bold: true, color: [109, 40, 217], gap: 2 });
    y = writeBlock(doc, y, value, { size: 10 });
  }

  y = writeBlock(doc, y, "Goals & Progress", { size: 12, bold: true, color: [109, 40, 217], gap: 4 });
  (goals || []).forEach((g, i) => {
    y = writeBlock(doc, y, `Goal ${i + 1} — ${g.goal_area || "General"} (${g.status || "active"})`, { size: 11, bold: true, color: [30, 30, 30], gap: 2 });
    y = writeBlock(doc, y, g.goal_text || "—", { size: 10, gap: 2 });
    y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"}`, { size: 9, color: [110, 110, 110] });
    const points = (progress || []).filter((p) => p.goal_id === g.id).sort((a, b) => (a.date || "").localeCompare(b.date || ""));
    for (const p of points) {
      y = writeBlock(doc, y, `${p.date || "—"}: ${p.percentage != null ? `${p.percentage}%` : (p.correct != null && p.total ? `${p.correct}/${p.total}` : "recorded")}${p.prompting_level && p.prompting_level !== "independent" ? ` · prompting: ${p.prompting_level}` : ""}`, { size: 9, color: [90, 90, 90], gap: 0 });
    }
    if (!points.length) y = writeBlock(doc, y, "No progress data recorded yet.", { size: 9, color: [130, 130, 130], gap: 0 });
    y += 6;
  });
  if (!(goals || []).length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

  y = writeBlock(doc, y, "Accommodations", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, student?.accommodations || "—", { size: 10 });
  y = writeBlock(doc, y, "Services", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, (Array.isArray(student?.services) && student.services.length ? student.services.join(", ") : null) || "—", { size: 10 });
  y = writeBlock(doc, y, "Discussion Notes", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, meeting.notes || "—", { size: 10 });
  if (meeting.follow_up_tasks) {
    y = writeBlock(doc, y, "Follow-Up Tasks", { size: 11, bold: true, color: [109, 40, 217], gap: 2 });
    y = writeBlock(doc, y, meeting.follow_up_tasks, { size: 10 });
  }

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from your recorded data.");
  doc.save(`Meeting-Packet-${student?.first_name || "Sample"}-${student?.last_name || "Student"}.pdf`);
}