import { jsPDF } from "jspdf";

// Shared PDF layout helpers for CaseCue document exports (IEP drafts, progress reports).

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;

function newDoc(title) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(60, 40, 120);
  doc.text(title, MARGIN, MARGIN);
  return doc;
}

function writeBlock(doc, y, text, { size = 11, bold = false, color = [40, 40, 40], gap = 6 } = {}) {
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(size);
  doc.setTextColor(...color);
  const lines = doc.splitTextToSize(String(text ?? "—"), CONTENT_W);
  for (const line of lines) {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN; }
    doc.text(line, MARGIN, y);
    y += size * 1.35;
  }
  return y + gap;
}

function addFooter(doc, text) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text(text, MARGIN, PAGE_H - 24);
  }
}

function studentHeader(doc, y, student, subtitle) {
  y = writeBlock(doc, y, `${student.first_name} ${student.last_name}`, { size: 13, bold: true, color: [30, 30, 30], gap: 2 });
  const meta = [
    student.grade ? `Grade ${student.grade}` : null,
    student.eligibility_category,
    subtitle,
  ].filter(Boolean).join(" · ");
  if (meta) y = writeBlock(doc, y, meta, { size: 10, color: [110, 110, 110], gap: 12 });
  return y;
}

export function exportIepPdf(student, goals) {
  const doc = newDoc("Individualized Education Program — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student, [
    student.iep_date ? `IEP date: ${student.iep_date}` : null,
    student.annual_review_due ? `Annual review due: ${student.annual_review_due}` : null,
    student.reevaluation_due ? `Reevaluation due: ${student.reevaluation_due}` : null,
  ].filter(Boolean).join(" · "));

  const sections = [
    ["Strengths", student.strengths],
    ["Areas of Need", student.areas_of_need],
    ["Present Levels of Academic Achievement & Functional Performance", student.present_levels],
    ["Accommodations", student.accommodations],
    ["Services", Array.isArray(student.services) && student.services.length ? student.services.join(", ") : null],
  ];
  for (const [title, body] of sections) {
    y = writeBlock(doc, y, title, { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
    y = writeBlock(doc, y, body || "—");
  }

  y = writeBlock(doc, y, "Annual Goals", { size: 12, bold: true, color: [109, 40, 217], gap: 4 });
  const gs = goals && goals.length ? goals : [];
  gs.forEach((g, i) => {
    y = writeBlock(doc, y, `Goal ${i + 1} — ${g.goal_area || "General"} (${g.status || "active"})`, { size: 11, bold: true, color: [30, 30, 30], gap: 2 });
    y = writeBlock(doc, y, g.goal_text || "—", { gap: 2 });
    y = writeBlock(doc, y, `Baseline: ${g.baseline || "—"} · Target: ${g.target || "—"} · Criterion: ${g.criterion || "—"} · Measured by: ${g.measurement_method || "—"}`, { size: 10, color: [110, 110, 110] });
  });
  if (!gs.length) y = writeBlock(doc, y, "No goals recorded.", { size: 10, color: [110, 110, 110] });

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue.");
  doc.save(`IEP-Draft-${student.first_name}-${student.last_name}.pdf`);
}

export function exportProgressReportPdf(student, report) {
  const doc = newDoc("Progress Report — DRAFT");
  let y = MARGIN + 28;
  y = studentHeader(doc, y, student, `Reporting through ${report.generated_at || new Date().toISOString().slice(0, 10)}`);

  const statsByArea = new Map((report.stats || []).map((s) => [s.goal_area, s]));
  for (const gr of report.goal_reports || []) {
    const s = statsByArea.get(gr.goal_area) || {};
    y = writeBlock(doc, y, gr.goal_area, { size: 12, bold: true, color: [109, 40, 217], gap: 2 });
    const statLine = [
      s.baseline ? `Baseline: ${s.baseline}` : null,
      s.target ? `Target: ${s.target}` : null,
      s.latest_percentage != null ? `Latest: ${s.latest_percentage}% (${s.latest_date || ""})` : null,
      s.average_percentage != null ? `Average: ${s.average_percentage}%` : null,
      `Data points: ${s.data_points ?? 0}`,
    ].filter(Boolean).join(" · ");
    y = writeBlock(doc, y, statLine, { size: 10, color: [110, 110, 110], gap: 3 });
    y = writeBlock(doc, y, gr.statement);
  }
  if (!report.goal_reports?.length) y = writeBlock(doc, y, "No goal reports in this draft.", { size: 10, color: [110, 110, 110] });

  y = writeBlock(doc, y, "Overall Summary", { size: 12, bold: true, color: [109, 40, 217], gap: 3 });
  y = writeBlock(doc, y, report.overall_summary || "—");

  addFooter(doc, "DRAFT — Educator/IEP Team Review Required. Generated by CaseCue from your recorded data.");
  doc.save(`Progress-Report-${student.first_name}-${student.last_name}.pdf`);
}