const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const lines=v=>String(v||'').split(/\n+/).map(x=>x.replace(/^[-•*\d.)\s]+/,'').trim()).filter(Boolean);
const slide=(title,body,notes='',kind='content')=>({title,body:Array.isArray(body)?body:lines(body).slice(0,6),notes,kind});
export function buildTeachingDeck(plan,analysis={},mode='full'){
 const skill=plan.subject_skill||analysis.subject||'Today’s skill', objective=plan.lesson_objective||plan.i_can_statement||'Learn and practice the target skill.';
 const s=[slide(plan.title||'Today’s Lesson',[skill,plan.grade_group||analysis.grade_level||''],'','title'),slide('What are we learning?',[objective,plan.i_can_statement,plan.essential_question],plan.teacher_talk,'objective'),slide('Why this matters',plan.real_world_connection,plan.mini_lecture,'connection'),slide('Words we need to know',plan.academic_vocabulary,plan.mini_lecture,'vocabulary'),slide('Get ready',plan.prior_knowledge,plan.anticipatory_set,'warmup'),slide('Step-by-step strategy',plan.teacher_talk||plan.mini_lecture,plan.mini_lecture,'strategy'),slide('I Do — Watch the model',plan.i_do,plan.i_do,'model'),slide('We Do — Try it together',plan.we_do,plan.we_do,'guided'),slide('Check for understanding',plan.checks_for_understanding,plan.questioning_plan,'cfu'),slide('Watch out for these mistakes',plan.misconceptions,plan.misconceptions,'mistakes'),slide('You Do — Show what you know',plan.you_do,plan.you_do,'practice'),slide('Exit Ticket',plan.quick_check,plan.quick_check,'exit'),slide('Success check',[plan.mastery_criterion,plan.reteach_plan],plan.progress_monitoring,'success'),slide('Teacher Answer Key',plan.answer_key,plan.answer_key,'teacher')];
 if(mode==='quick')return s.filter((_,i)=>[0,1,5,6,7,10,11,13].includes(i));
 if(mode==='intensive')return [...s.slice(0,7),slide('One more model',plan.example_student_response,plan.example_explanation,'model'),...s.slice(7,10),slide('Small-group support',plan.small_group_plan,plan.differentiation,'support'),...s.slice(10)];
 return s;
}
export function openTeachingDeck(deck,{teacher='Teacher',date='',mode='full'}={}){
 const pages=deck.map((s,i)=>'<section class="slide '+esc(s.kind)+'"><div class="top"><b>CaseCue Teaching Deck</b><span>'+(i+1)+' / '+deck.length+'</span></div><h1>'+esc(s.title)+'</h1><div class="body">'+(s.body||[]).filter(Boolean).map(x=>'<div class="point">'+esc(x)+'</div>').join('')+'</div><div class="notes"><b>Teacher Notes</b><p>'+esc(s.notes||'Use the slide to prompt, model, check understanding, and transition to the next step.')+'</p></div><footer>'+esc(teacher)+' · '+esc(date)+' · '+esc(mode==='intensive'?'Intensive Resource Lesson':mode==='quick'?'Quick Review':'Full Lesson')+'</footer></section>').join('');
 const html='<!doctype html><html><head><meta charset="utf-8"><title>CaseCue Teaching Deck</title><style>*{box-sizing:border-box}body{margin:0;background:#07101f;font-family:Inter,Arial,sans-serif;color:#0f172a}.slide{width:13.333in;height:7.5in;margin:24px auto;background:white;padding:.55in .7in;position:relative;page-break-after:always;overflow:hidden;border-radius:20px}.top{display:flex;justify-content:space-between;color:#2563eb;font-size:14px;text-transform:uppercase;letter-spacing:.12em}h1{font-size:38px;margin:.3in 0 .22in;line-height:1.05}.body{display:grid;gap:12px}.point{font-size:22px;line-height:1.3;padding:12px 16px;background:#f1f5f9;border-left:5px solid #2563eb;border-radius:10px}.title{background:linear-gradient(135deg,#07101f,#123a74);color:white}.title .point{background:#ffffff16;border-color:#7dd3fc}.notes{position:absolute;left:.7in;right:.7in;bottom:.52in;border-top:1px solid #cbd5e1;padding-top:10px;font-size:12px;color:#475569;max-height:1.05in;overflow:hidden}.notes p{margin:4px 0;white-space:pre-line}footer{position:absolute;bottom:.2in;right:.7in;font-size:10px;color:#94a3b8}@media print{body{background:white}.slide{margin:0;border-radius:0}@page{size:13.333in 7.5in;margin:0}}@media(max-width:900px){.slide{width:96vw;height:auto;min-height:72vw;margin:12px auto}.notes{position:static;margin-top:25px}footer{position:static;margin-top:12px}}</style></head><body>'+pages+'</body></html>';
 const w=window.open('','_blank');if(!w)throw new Error('Allow pop-ups to open the teaching deck.');w.document.write(html);w.document.close();
}
