import React,{useMemo,useRef,useState}from'react';
import{Upload,Loader2,CheckCircle2,FileSearch,Trash2,ShieldCheck,BookOpenCheck,Eye,RefreshCw,Wrench}from'lucide-react';
import{base44}from'@/api/base44Client';
import{Card}from'@/components/ui/cards';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{Label}from'@/components/ui/label';
import{Textarea}from'@/components/ui/textarea';
import StudentSelector from'@/components/forms/StudentSelector';
import{useToast}from'@/components/ui/use-toast';
import{useAsync}from'@/lib/useAsync';

const TYPES=['assignment','worksheet','writing_sample','quiz','assessment','classwork','homework','probe','observation','other'];
const freshForm=()=>({title:'',evidence_type:'worksheet',date:new Date().toISOString().slice(0,10),score_possible:'',answer_key:'',rubric:'',teacher_directions:''});
const pct=(e,p)=>Number(p)>0?Math.round(Number(e||0)/Number(p)*1000)/10:0;

export default function WorkEvidencePanel({students=[],goals=[],fixedStudentId='',compact=false}){
 const{toast}=useToast(),inputRef=useRef(null);
 const[studentId,setStudentId]=useState(fixedStudentId||''),[goalId,setGoalId]=useState(''),[file,setFile]=useState(null),[fileUrl,setFileUrl]=useState('');
 const[form,setForm]=useState(freshForm()),[analysis,setAnalysis]=useState(null),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[manualMode,setManualMode]=useState(false),[teacherChecked,setTeacherChecked]=useState(false);
 const{data:evidence,refetch}=useAsync(()=>fixedStudentId?base44.entities.WorkEvidence.filter({student_id:fixedStudentId},'-date',100):base44.entities.WorkEvidence.list('-date',200),[fixedStudentId]);
 const goalsFor=useMemo(()=>goals.filter(g=>g.student_id===studentId&&g.status!=='archived'),[goals,studentId]);

 const choose=f=>{setFile(f||null);setFileUrl('');setAnalysis(null);setManualMode(false);setTeacherChecked(false);if(f)setForm(v=>({...v,title:v.title||f.name.replace(/\.[^.]+$/,'')}))};
 const ensureUpload=async()=>{if(fileUrl)return fileUrl;if(!file)throw new Error('Choose a worksheet or PDF first.');const up=await base44.integrations.Core.UploadPrivateFile({file});setFileUrl(up.file_uri);return up.file_uri};
 const openFile=async()=>{try{if(fileUrl){const s=await base44.integrations.Core.CreateFileSignedUrl({file_uri:fileUrl,expires_in:900});if(s?.signed_url)return window.open(s.signed_url,'_blank','noopener,noreferrer')}if(file){const u=URL.createObjectURL(file);window.open(u,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(u),60000);return}throw new Error('No file selected.')}catch(e){toast({title:'Could not open work',description:e.message,variant:'destructive'})}};

 const analyze=async()=>{if(!studentId||!file){toast({title:'Choose the student and worksheet first',variant:'destructive'});return;}setBusy(true);try{const stored=await ensureUpload();const r=await base44.functions.invoke('analyzeStudentWork',{student_id:studentId,goal_id:goalId,file_uri:stored,score_possible:Number(form.score_possible||0),answer_key:form.answer_key,rubric:form.rubric,teacher_directions:form.teacher_directions});const a=r.data?.analysis||r.analysis;if(!a)throw new Error('CaseCue did not return a review result.');setManualMode(false);setTeacherChecked(false);setAnalysis({...a,question_breakdown:Array.isArray(a.question_breakdown)?a.question_breakdown:[]});setForm(v=>({...v,title:v.title||a.detected_title||file.name,evidence_type:TYPES.includes(a.evidence_type)?a.evidence_type:v.evidence_type,score_possible:a.score_possible>0?String(a.score_possible):v.score_possible}));toast({title:'Worksheet ready for teacher review',description:'Nothing has been posted. Correct anything CaseCue read incorrectly before saving.'})}catch(e){toast({title:'Could not read the worksheet',description:(e?.response?.data?.error||e.message)+' You can use Manual Grade instead.',variant:'destructive'})}finally{setBusy(false)}};

 const startManual=async()=>{if(!studentId||!file){toast({title:'Choose the student and worksheet first',variant:'destructive'});return;}setBusy(true);try{await ensureUpload();setManualMode(true);setTeacherChecked(true);setAnalysis({detected_title:form.title||file.name,evidence_type:form.evidence_type,skills:[],score_earned:0,score_possible:Number(form.score_possible||0),percentage:0,scoring_confidence:'teacher_confirmed',scoring_basis:'Teacher entered the score manually after reviewing the uploaded work.',question_breakdown:[],qualitative_notes:'',error_patterns:[],strengths_observed:[],teacher_observation_draft:'',goal_alignment:goalId?'Teacher selected the IEP goal manually.':'No IEP goal selected.',cautions:[]})}catch(e){toast({title:'Could not prepare manual grading',description:e.message,variant:'destructive'})}finally{setBusy(false)}};

 const updateScore=(earned,possible)=>setAnalysis(a=>({...a,score_earned:Number(earned||0),score_possible:Number(possible||0),percentage:pct(earned,possible),scoring_confidence:'teacher_confirmed'}));
 const updateItem=(i,patch)=>setAnalysis(a=>{const rows=(a.question_breakdown||[]).map((r,n)=>n===i?{...r,...patch}:r);const earned=rows.reduce((n,r)=>n+Number(r.earned||0),0),possible=rows.reduce((n,r)=>n+Number(r.possible||0),0);return{...a,question_breakdown:rows,score_earned:earned,score_possible:possible,percentage:pct(earned,possible),scoring_confidence:'teacher_confirmed'}});

 const save=async()=>{if(!analysis||!studentId)return;setSaving(true);try{
   const user=await base44.auth.me(),organizationId=user?.organization_id||user?.data?.organization_id||'';
   if(!organizationId)throw new Error('Your account is missing an organization.');
   const stored=await ensureUpload(),earned=Number(analysis.score_earned||0),possible=Number(analysis.score_possible||0),percentage=pct(earned,possible),title=form.title||analysis.detected_title||file?.name||'Student work';
   const ev=await base44.entities.WorkEvidence.create({student_id:studentId,organization_id:organizationId,goal_id:goalId,title,evidence_type:TYPES.includes(form.evidence_type)?form.evidence_type:'worksheet',file_url:stored,date:form.date,source:manualMode?'Teacher Manual Grade':'CaseCue Scan + Teacher Review',score_earned:earned,score_possible:possible,percentage,qualitative_notes:analysis.qualitative_notes||'',error_patterns:analysis.error_patterns||[],skills:analysis.skills||[],analysis:{...analysis,teacher_selected_goal_id:goalId,manual_mode:manualMode},teacher_confirmed:true,review_status:'approved',evidence_strength:goalId?'supporting':'classroom_only'});
   let gradebookId='';
   if(possible>0){const g=await base44.entities.GradebookAssignment.create({student_id:studentId,organization_id:organizationId,goal_id:goalId,title,course:analysis.subject||'',assignment_type:form.evidence_type,score_earned:earned,score_possible:possible,current_grade_percent:percentage,notes:analysis.qualitative_notes||'',quantitative_note:`${earned}/${possible} · ${(percentage/100).toFixed(2)} (${percentage}%)`,qualitative_note:analysis.teacher_observation_draft||analysis.qualitative_notes||'',file_url:stored,work_evidence_id:ev.id,source_type:manualMode?'teacher_manual_grade':'student_work_scan',date:form.date});gradebookId=g.id;await base44.entities.WorkEvidence.update(ev.id,{gradebook_assignment_id:g.id});}
   if(goalId&&possible>0){const pd=await base44.entities.ProgressData.create({student_id:studentId,organization_id:organizationId,goal_id:goalId,date:form.date,correct:earned,total:possible,percentage,decimal:percentage/100,qualitative_notes:analysis.qualitative_notes||'',observation_notes:analysis.teacher_observation_draft||'',work_evidence_id:ev.id,record_status:'active',data_basis:'overall_assignment_score'});await base44.entities.WorkEvidence.update(ev.id,{progress_data_id:pd.id});}
   toast({title:'Grade saved',description:goalId&&possible>0?'Saved to Gradebook, Evidence, and the goal you selected.':'Saved to Gradebook/Evidence. No IEP progress was posted unless you selected a goal.'});
   setAnalysis(null);setFile(null);setFileUrl('');setGoalId('');setManualMode(false);setTeacherChecked(false);setForm(freshForm());if(inputRef.current)inputRef.current.value='';refetch();
 }catch(e){toast({title:'Could not save grade',description:e.message,variant:'destructive'})}finally{setSaving(false)}};

 const remove=async x=>{if(!window.confirm(`Delete evidence "${x.title}"?`))return;await base44.entities.WorkEvidence.delete(x.id);refetch()};

 return <div className="space-y-5">
  <Card className="border-blue-100 bg-gradient-to-br from-white to-sky-50/50 p-6">
   <div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-white"><FileSearch className="h-5 w-5"/></div><div><h3 className="text-lg font-black">Easy Grader</h3><p className="mt-1 text-sm text-slate-600">Upload the worksheet, let CaseCue try first, then fix anything it read wrong. You control the student, goal, score, and final record.</p></div></div>
   <div className="mt-5 grid gap-4 md:grid-cols-2">
    {!fixedStudentId&&<StudentSelector students={students} value={studentId} onChange={id=>{setStudentId(id);setGoalId('');setAnalysis(null)}} placeholder="1. Choose student…" noBottomSpace/>}
    <div><Label>2. IEP goal (optional — you choose)</Label><select className="mt-1 h-11 w-full rounded-lg border-2 border-blue-200 bg-white px-3 text-sm font-semibold" value={goalId} onChange={e=>setGoalId(e.target.value)}><option value="">Not IEP goal evidence / choose later</option>{goalsFor.map(g=><option key={g.id} value={g.id}>{g.goal_area||'Goal'} — {(g.goal_text||'').slice(0,130)}</option>)}</select></div>
    <div><Label>Assignment title</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Fractions worksheet"/></div>
    <div><Label>Type</Label><select className="mt-1 h-10 w-full rounded-lg border bg-white px-3 text-sm" value={form.evidence_type} onChange={e=>setForm({...form,evidence_type:e.target.value})}>{TYPES.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></div>
    <div><Label>Date</Label><Input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div>
    <div><Label>Possible points (if you know them)</Label><Input type="number" min="0" value={form.score_possible} onChange={e=>setForm({...form,score_possible:e.target.value})}/></div>
    <div className="md:col-span-2"><Label>Answer key / correct answers (recommended)</Label><Textarea rows={3} value={form.answer_key} onChange={e=>setForm({...form,answer_key:e.target.value})} placeholder="Example: 1) 24  2) 36  3) 18 — paste whatever you have."/></div>
    <div><Label>Rubric (if needed)</Label><Textarea rows={2} value={form.rubric} onChange={e=>setForm({...form,rubric:e.target.value})}/></div>
    <div><Label>Teacher directions / special scoring rule</Label><Textarea rows={2} value={form.teacher_directions} onChange={e=>setForm({...form,teacher_directions:e.target.value})} placeholder="Example: Problems 1–10 only; 1 point each."/></div>
   </div>
   <div className="mt-5 rounded-2xl border-2 border-dashed border-blue-200 bg-white p-6 text-center"><input ref={inputRef} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.docx" className="hidden" onChange={e=>choose(e.target.files?.[0])}/><Upload className="mx-auto h-7 w-7 text-blue-600"/><div className="mt-2 font-semibold">{file?file.name:'3. Upload worksheet / PDF / photo'}</div><div className="mt-1 text-xs text-slate-500">If CaseCue reads it wrong, use Manual Grade. The original file stays attached.</div><div className="mt-3 flex flex-wrap justify-center gap-2"><Button variant="outline" onClick={()=>inputRef.current?.click()}>{file?'Replace file':'Choose file'}</Button>{file&&<Button variant="outline" onClick={openFile}><Eye className="mr-1 h-4 w-4"/>View file</Button>}</div></div>
   <div className="mt-4 flex flex-wrap gap-2"><Button className="bg-blue-700 text-white hover:bg-blue-800" disabled={busy||!studentId||!file} onClick={analyze}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<BookOpenCheck className="mr-2 h-4 w-4"/>}{busy?'Reading worksheet…':'AI Read & Grade'}</Button><Button variant="outline" disabled={busy||!studentId||!file} onClick={startManual}><Wrench className="mr-2 h-4 w-4"/>Manual Grade</Button></div>
  </Card>

  {analysis&&<Card className="border-amber-200 p-6">
   <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-amber-600"/><div><h3 className="font-black">{manualMode?'Manual grade review':'Review & fix the scan'}</h3><p className="text-sm text-slate-600">Nothing posts until you press Save. Change anything CaseCue got wrong.</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={openFile}><Eye className="mr-1 h-4 w-4"/>View worksheet</Button>{!manualMode&&<Button variant="outline" onClick={analyze} disabled={busy}><RefreshCw className="mr-1 h-4 w-4"/>Re-read</Button>}</div></div>

   <div className="mt-5 grid gap-4 md:grid-cols-2">
    <div><Label>Student</Label><StudentSelector students={students} value={studentId} onChange={id=>{setStudentId(id);setGoalId('')}} noBottomSpace/></div>
    <div><Label>IEP goal — final teacher selection</Label><select className="mt-1 h-11 w-full rounded-lg border-2 border-blue-300 bg-white px-3 text-sm font-semibold" value={goalId} onChange={e=>setGoalId(e.target.value)}><option value="">Do not count this as IEP goal progress</option>{goals.filter(g=>g.student_id===studentId&&g.status!=='archived').map(g=><option key={g.id} value={g.id}>{g.goal_area||'Goal'} — {(g.goal_text||'').slice(0,150)}</option>)}</select></div>
    <div className="md:col-span-2"><Label>Assignment title</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div>
    <div><Label>Points earned</Label><Input type="number" min="0" value={analysis.score_earned??0} onChange={e=>updateScore(e.target.value,analysis.score_possible)}/></div>
    <div><Label>Points possible</Label><Input type="number" min="0" value={analysis.score_possible??0} onChange={e=>updateScore(analysis.score_earned,e.target.value)}/></div>
   </div>

   <div className="mt-4 rounded-2xl bg-slate-950 p-4 text-white"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-black uppercase tracking-wider text-slate-400">Final score before saving</div>{!manualMode&&<span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase tracking-wider ${analysis.verification?.status==='verified'?'bg-emerald-400/20 text-emerald-200':'bg-amber-400/20 text-amber-200'}`}>{analysis.verification?.status==='verified'?'Two-pass verified':'Teacher review needed'}</span>}</div><div className="mt-1 text-3xl font-black">{Number(analysis.score_possible)>0?`${analysis.score_earned}/${analysis.score_possible} · ${pct(analysis.score_earned,analysis.score_possible)}%`:'No numeric score yet'}</div><div className="mt-1 text-xs text-sky-300">{manualMode?'Teacher-entered score':`Scanner confidence: ${analysis.scoring_confidence||'review'}`}</div>{analysis.verification&&<div className="mt-2 text-[11px] text-slate-300">Pass 1: {analysis.verification.first_pass?.earned}/{analysis.verification.first_pass?.possible} · Pass 2: {analysis.verification.second_pass?.earned}/{analysis.verification.second_pass?.possible}</div>}</div>

   {(analysis.question_breakdown||[]).length>0&&<div className="mt-5"><div className="font-black">Question-by-question check</div><p className="mt-1 text-xs text-slate-500">Correct any item CaseCue misread. Totals update automatically.</p><div className="mt-3 space-y-2">{analysis.question_breakdown.map((q,i)=><div key={i} className="grid gap-2 rounded-xl border p-3 md:grid-cols-[.45fr_1fr_1fr_.45fr_.45fr_1fr]"><Input value={q.item||''} onChange={e=>updateItem(i,{item:e.target.value})} placeholder="#"/><Input value={q.student_response||''} onChange={e=>updateItem(i,{student_response:e.target.value})} placeholder="Student answer"/><Input value={q.correct_answer||''} onChange={e=>updateItem(i,{correct_answer:e.target.value})} placeholder="Correct answer"/><Input type="number" min="0" value={q.earned??0} onChange={e=>updateItem(i,{earned:Number(e.target.value||0),status:'teacher_reviewed'})}/><Input type="number" min="0" value={q.possible??0} onChange={e=>updateItem(i,{possible:Number(e.target.value||0),status:'teacher_reviewed'})}/><Input value={q.note||q.status||''} onChange={e=>updateItem(i,{note:e.target.value})} placeholder="Note"/></div>)}</div></div>}

   <div className="mt-5 grid gap-3 md:grid-cols-2"><div><Label>What the work shows</Label><Textarea rows={4} value={analysis.qualitative_notes||''} onChange={e=>setAnalysis({...analysis,qualitative_notes:e.target.value})}/></div><div><Label>Teacher observation</Label><Textarea rows={4} value={analysis.teacher_observation_draft||''} onChange={e=>setAnalysis({...analysis,teacher_observation_draft:e.target.value})}/></div></div>
   {analysis.scoring_basis&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>How CaseCue read it:</b> {analysis.scoring_basis}</div>}
   {(analysis.cautions||[]).length>0&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{analysis.cautions.join(' · ')}</div>}
   {!manualMode&&analysis.verification?.status==='needs_teacher_review'&&<label className="mt-4 flex items-start gap-3 rounded-xl border-2 border-amber-200 bg-amber-50 p-4 text-sm"><input type="checkbox" className="mt-1" checked={teacherChecked} onChange={e=>setTeacherChecked(e.target.checked)}/><span><strong>I checked the original worksheet and corrected the score above.</strong><span className="mt-1 block text-xs text-amber-800">Required because the two grading passes did not fully agree.</span></span></label>}
   <Button onClick={save} disabled={saving||(!manualMode&&analysis.verification?.status==='needs_teacher_review'&&!teacherChecked)} className="mt-5 bg-emerald-700 text-white hover:bg-emerald-800"><CheckCircle2 className="mr-2 h-4 w-4"/>{saving?'Saving…':'Save Final Grade'}</Button>
  </Card>}

  {!compact&&<Card className="p-5"><h3 className="mb-3 font-black">Evidence on file</h3><div className="space-y-2">{(evidence||[]).filter(x=>!['auto_filed','rejected','duplicate'].includes(x.review_status)).map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl border p-3"><div className="min-w-0 flex-1"><div className="truncate font-semibold">{x.title}</div><div className="text-xs text-slate-500">{x.date||'No date'} · {String(x.evidence_type||'evidence').replaceAll('_',' ')}{x.score_possible>0?` · ${x.score_earned}/${x.score_possible} (${x.percentage}%)`:''}</div></div><Button variant="ghost" size="icon" onClick={()=>remove(x)}><Trash2 className="h-4 w-4 text-rose-500"/></Button></div>)}{!(evidence||[]).length&&<div className="py-5 text-center text-sm text-slate-500">No work evidence saved yet.</div>}</div></Card>}
 </div>
}