import React, { useMemo, useRef, useState } from 'react';
import { Upload, Loader2, CheckCircle2, FileSearch, Trash2, ShieldCheck, BookOpenCheck } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Card } from '@/components/ui/cards';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import StudentSelector from '@/components/forms/StudentSelector';
import { useToast } from '@/components/ui/use-toast';
import { useAsync } from '@/lib/useAsync';

const TYPES=['assignment','worksheet','writing_sample','quiz','assessment','classwork','homework','probe','observation','other'];

export default function WorkEvidencePanel({ students=[], goals=[], fixedStudentId='', compact=false }){
  const {toast}=useToast(); const inputRef=useRef(null);
  const [studentId,setStudentId]=useState(fixedStudentId||''); const [goalId,setGoalId]=useState(''); const [file,setFile]=useState(null); const [fileUrl,setFileUrl]=useState('');
  const [form,setForm]=useState({title:'',evidence_type:'assignment',date:new Date().toISOString().slice(0,10),score_possible:'',answer_key:'',rubric:'',teacher_directions:''});
  const [analysis,setAnalysis]=useState(null); const [busy,setBusy]=useState(false); const [saving,setSaving]=useState(false);
  const {data:evidence,refetch}=useAsync(()=>fixedStudentId?base44.entities.WorkEvidence.filter({student_id:fixedStudentId},'-date',100):base44.entities.WorkEvidence.list('-date',200),[fixedStudentId]);
  const goalsFor=useMemo(()=>goals.filter(g=>g.student_id===studentId),[goals,studentId]);
  const analyze=async()=>{if(!studentId||!file){toast({title:'Select a student and upload work first',variant:'destructive'});return;}setBusy(true);try{const up=await base44.integrations.Core.UploadFile({file});setFileUrl(up.file_url);const r=await base44.functions.invoke('analyzeStudentWork',{student_id:studentId,goal_id:goalId,file_url:up.file_url,score_possible:Number(form.score_possible||0),answer_key:form.answer_key,rubric:form.rubric,teacher_directions:form.teacher_directions});const a=r.data?.analysis||r.analysis;setAnalysis(a);setForm(v=>({...v,title:v.title||a.detected_title||file.name,evidence_type:TYPES.includes(a.evidence_type)?a.evidence_type:v.evidence_type,score_possible:a.score_possible>0?String(a.score_possible):v.score_possible}));}catch(e){toast({title:'Could not analyze work',description:e?.response?.data?.error||e.message,variant:'destructive'})}finally{setBusy(false)}};
  const save=async()=>{if(!analysis||!studentId||!fileUrl)return;setSaving(true);try{const earned=Number(analysis.score_earned||0), possible=Number(analysis.score_possible||form.score_possible||0);const pct=possible>0?Math.round(earned/possible*1000)/10:0;let gradebookId='';if(possible>0){const g=await base44.entities.GradebookAssignment.create({student_id:studentId,goal_id:goalId,title:form.title||analysis.detected_title||file?.name||'Student work',score_earned:earned,score_possible:possible,notes:analysis.qualitative_notes||'',date:form.date});gradebookId=g.id;if(goalId)await base44.entities.ProgressData.create({student_id:studentId,goal_id:goalId,date:form.date,correct:earned,total:possible,percentage:pct,decimal:pct/100,qualitative_notes:analysis.qualitative_notes||'',observation_notes:analysis.teacher_observation_draft||'',prompting_level:'independent'});}await base44.entities.WorkEvidence.create({student_id:studentId,goal_id:goalId,title:form.title||analysis.detected_title||file?.name||'Student work',evidence_type:form.evidence_type,file_url:fileUrl,date:form.date,source:'Teacher Upload',score_earned:earned,score_possible:possible,percentage:pct,qualitative_notes:analysis.qualitative_notes||'',error_patterns:analysis.error_patterns||[],skills:analysis.skills||[],analysis,teacher_confirmed:true,gradebook_assignment_id:gradebookId});toast({title:'Evidence saved',description:possible>0?'Added to Evidence Vault, Gradebook, and linked progress data.':'Added to Evidence Vault. No score was posted because CaseCue could not verify one.'});setAnalysis(null);setFile(null);setFileUrl('');setGoalId('');setForm({title:'',evidence_type:'assignment',date:new Date().toISOString().slice(0,10),score_possible:'',answer_key:'',rubric:'',teacher_directions:''});if(inputRef.current)inputRef.current.value='';refetch();}catch(e){toast({title:'Could not save evidence',description:e.message,variant:'destructive'})}finally{setSaving(false)}};
  const remove=async x=>{if(!window.confirm(`Delete evidence "${x.title}"? This does not automatically delete a separately-created gradebook row.`))return;await base44.entities.WorkEvidence.delete(x.id);refetch();};
  return <div className='space-y-5'>
    <Card className='p-6 border-blue-100 bg-gradient-to-br from-white to-sky-50/50'>
      <div className='flex items-start gap-3'><div className='h-11 w-11 rounded-2xl bg-slate-950 text-white flex items-center justify-center'><FileSearch className='h-5 w-5'/></div><div><h3 className='font-black text-lg'>Student Work & Evidence Vault</h3><p className='text-sm text-slate-600 mt-1'>Upload student work, let CaseCue analyze what is actually visible, review the suggested score/observation, then approve it into the student file. Verified scores can flow to Gradebook and goal progress.</p></div></div>
      <div className='grid md:grid-cols-2 gap-4 mt-5'>
        {!fixedStudentId&&<StudentSelector students={students} value={studentId} onChange={id=>{setStudentId(id);setGoalId('')}} noBottomSpace/>}
        <div><Label>Link to IEP goal</Label><select className='mt-1 w-full h-10 rounded-lg border bg-white px-3 text-sm' value={goalId} onChange={e=>setGoalId(e.target.value)}><option value=''>No goal selected</option>{goalsFor.map(g=><option key={g.id} value={g.id}>{g.goal_area||'Goal'} — {(g.goal_text||'').slice(0,80)}</option>)}</select></div>
        <div><Label>Evidence title</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder='e.g. Fractions Quiz #2'/></div>
        <div><Label>Evidence type</Label><select className='mt-1 w-full h-10 rounded-lg border bg-white px-3 text-sm' value={form.evidence_type} onChange={e=>setForm({...form,evidence_type:e.target.value})}>{TYPES.map(t=><option key={t} value={t}>{t.replace(/_/g,' ')}</option>)}</select></div>
        <div><Label>Date</Label><Input type='date' value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div>
        <div><Label>Possible points (optional)</Label><Input type='number' min='0' value={form.score_possible} onChange={e=>setForm({...form,score_possible:e.target.value})} placeholder='Leave blank if unknown'/></div>
        <div className='md:col-span-2'><Label>Answer key (optional)</Label><Textarea rows={2} value={form.answer_key} onChange={e=>setForm({...form,answer_key:e.target.value})} placeholder='Paste the answer key if the worksheet does not include one.'/></div>
        <div className='md:col-span-2'><Label>Rubric / teacher directions (optional)</Label><Textarea rows={2} value={form.rubric} onChange={e=>setForm({...form,rubric:e.target.value})} placeholder='Paste rubric criteria for writing or subjective work.'/></div>
      </div>
      <div className='mt-5 rounded-2xl border-2 border-dashed border-blue-200 bg-white p-6 text-center'><input ref={inputRef} type='file' accept='.pdf,.png,.jpg,.jpeg,.webp,.docx' className='hidden' onChange={e=>setFile(e.target.files?.[0]||null)}/><Upload className='h-7 w-7 mx-auto text-blue-600'/><div className='font-semibold mt-2'>{file?file.name:'Upload student work'}</div><div className='text-xs text-slate-500 mt-1'>PDF, image, scan, or DOCX. CaseCue will not post anything until you approve.</div><Button variant='outline' className='mt-3' onClick={()=>inputRef.current?.click()}>Choose file</Button></div>
      <Button className='mt-4 bg-blue-700 hover:bg-blue-800 text-white' disabled={busy||!studentId||!file} onClick={analyze}>{busy?<Loader2 className='h-4 w-4 mr-2 animate-spin'/>:<BookOpenCheck className='h-4 w-4 mr-2'/>}{busy?'Analyzing work…':'Analyze student work'}</Button>
    </Card>
    {analysis&&<Card className='p-6 border-amber-200'><div className='flex items-start gap-3'><ShieldCheck className='h-5 w-5 text-amber-600 mt-0.5'/><div><h3 className='font-black'>Teacher review required</h3><p className='text-sm text-slate-600'>CaseCue has not posted this result yet. Verify the work and score before saving.</p></div></div><div className='grid md:grid-cols-3 gap-3 mt-5'><div className='rounded-xl bg-slate-50 p-4'><div className='text-xs text-slate-500'>Suggested score</div><div className='text-2xl font-black'>{analysis.score_possible>0?`${analysis.score_earned}/${analysis.score_possible}`:'Not scored'}</div><div className='text-xs text-slate-500'>{analysis.scoring_confidence}</div></div><div className='rounded-xl bg-slate-50 p-4 md:col-span-2'><div className='text-xs font-bold text-slate-500'>Scoring basis</div><div className='text-sm mt-1'>{analysis.scoring_basis}</div></div></div><div className='mt-4 grid md:grid-cols-2 gap-3'><div className='rounded-xl border p-4'><div className='text-xs font-bold text-slate-500'>Teacher observation draft</div><div className='text-sm mt-1'>{analysis.teacher_observation_draft}</div></div><div className='rounded-xl border p-4'><div className='text-xs font-bold text-slate-500'>Error patterns / strengths</div><div className='text-sm mt-1'>{[...(analysis.error_patterns||[]),...(analysis.strengths_observed||[])].join(' · ')||'None detected'}</div></div></div>{(analysis.cautions||[]).length>0&&<div className='mt-4 rounded-xl bg-amber-50 border border-amber-200 p-3 text-sm text-amber-900'>{analysis.cautions.join(' · ')}</div>}<Button onClick={save} disabled={saving} className='mt-4 bg-emerald-700 hover:bg-emerald-800 text-white'><CheckCircle2 className='h-4 w-4 mr-2'/>{saving?'Saving…':'Approve & save to student file'}</Button></Card>}
    {!compact&&<Card className='p-5'><h3 className='font-black mb-3'>Evidence on file</h3><div className='space-y-2'>{(evidence||[]).map(x=><div key={x.id} className='rounded-xl border p-3 flex items-center gap-3'><div className='flex-1 min-w-0'><div className='font-semibold truncate'>{x.title}</div><div className='text-xs text-slate-500'>{x.date||'No date'} · {String(x.evidence_type||'evidence').replace(/_/g,' ')}{x.score_possible>0?` · ${x.score_earned}/${x.score_possible} (${x.percentage}%)`:''}</div></div><Button variant='ghost' size='icon' onClick={()=>remove(x)}><Trash2 className='h-4 w-4 text-rose-500'/></Button></div>)}{!(evidence||[]).length&&<div className='text-sm text-slate-500 py-5 text-center'>No work evidence saved yet.</div>}</div></Card>}
  </div>;
}
