import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';

const DATE_SCHEMA={type:'object',properties:{iep_date:{type:'object',properties:{date:{type:'string'},confidence:{type:'string',enum:['high','medium','low','missing']},evidence:{type:'string'},page:{type:'number'}}},annual_review_due:{type:'object',properties:{date:{type:'string'},confidence:{type:'string',enum:['high','medium','low','missing']},evidence:{type:'string'},page:{type:'number'}}},reevaluation_due:{type:'object',properties:{date:{type:'string'},confidence:{type:'string',enum:['high','medium','low','missing']},evidence:{type:'string'},page:{type:'number'}}},last_evaluation_date:{type:'object',properties:{date:{type:'string'},confidence:{type:'string',enum:['high','medium','low','missing']},evidence:{type:'string'},page:{type:'number'}}},conflicts:{type:'array',items:{type:'string'}}},required:['iep_date','annual_review_due','reevaluation_due','last_evaluation_date','conflicts']};
const valid=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''));

export default async function(req){
 try{
  const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized'},{status:401});
  const body=await req.json().catch(()=>({}));if(!body.student_id)return Response.json({error:'Student is required.'},{status:400});
  const svc=base44.asServiceRole;const student=await svc.entities.Student.get(body.student_id);if(!student)return Response.json({error:'Student not found.'},{status:404});
  const org=user.organization_id||user.data?.organization_id||'';if(student.organization_id&&org&&student.organization_id!==org)return Response.json({error:'Not authorized for this student.'},{status:403});
  let doc=null;if(body.document_id)doc=await svc.entities.Document.get(body.document_id);else{const docs=await svc.entities.Document.filter({student_id:student.id});doc=(docs||[]).filter(d=>d.document_type==='IEP'&&['current','final'].includes(d.iep_role)&&d.extraction_status==='processed').sort((a,b)=>String(b.date_uploaded||b.updated_date||'').localeCompare(String(a.date_uploaded||a.updated_date||'')))[0]||null;}
  if(!doc)return Response.json({error:'No processed current/final IEP is available to verify dates.'},{status:404});
  if(doc.student_id!==student.id)return Response.json({error:'That document is not attached to this student.'},{status:400});
  if(doc.document_type!=='IEP')return Response.json({error:'Date verification requires an IEP source document.'},{status:400});
  if(!['current','final'].includes(doc.iep_role)){await svc.entities.Student.update(student.id,{date_verification_status:'needs_review',date_verification_note:`${doc.filename||'IEP'} is marked ${doc.iep_role||'unknown'}, so CaseCue did not replace current IEP/evaluation dates.`,date_verification_source_document_id:doc.id});return Response.json({verified:false,needs_review:true,reason:'historical_or_draft'});}
  if(doc.extraction_status!=='processed'||!doc.processing_results)return Response.json({error:'Process this IEP before verifying dates.'},{status:400});
  const context=JSON.stringify(doc.processing_results).slice(0,70000);
  const prompt=`You are CaseCue Date Verification. Review ONLY the saved extraction from this CURRENT/FINAL IEP and verify four student dates. Never calculate, infer, or assume a date from timelines, legal intervals, age, or another date. Return a date only when it is explicitly printed in this IEP and clearly identifies the requested field.\n\nFields:\n1. iep_date = the current IEP meeting/effective date, only if explicitly labeled or unambiguous.\n2. annual_review_due = the next annual IEP/annual review due date, only if explicitly printed. Do not calculate one year from the IEP date.\n3. reevaluation_due = the next reevaluation/triennial/evaluation due date, only if explicitly printed. Do not calculate three years from an evaluation date.\n4. last_evaluation_date = the most recent completed evaluation/reevaluation date explicitly documented in the IEP.\n\nFor each field return ISO YYYY-MM-DD, confidence, short source evidence, and page number. Use high confidence only when the date and its meaning are explicit. If the document contains conflicting dates for the same field, list the conflict and do not choose one unless the document clearly marks one as current. Missing dates must be returned as empty date with confidence missing.\n\nSAVED IEP EXTRACTION:\n${context}`;
  const r=await svc.integrations.Core.InvokeLLM({prompt,response_json_schema:DATE_SCHEMA,model:'automatic'});const x=typeof r==='object'?r:JSON.parse(r);
  const conflicts=Array.isArray(x.conflicts)?x.conflicts.filter(Boolean):[];const fields=['iep_date','annual_review_due','reevaluation_due','last_evaluation_date'];const patch={};const verified=[];const review=[];
  for(const field of fields){const item=x[field]||{};if(item.confidence==='high'&&valid(item.date)){patch[field]=item.date;verified.push(`${field}: ${item.date}${item.page?` (p.${item.page})`:''}`)}else if(item.date||item.confidence!=='missing'){review.push(`${field}: ${item.date||'unclear'} (${item.confidence||'unclear'})`)}}
  const allRequiredVerified=fields.every((field)=>x[field]?.confidence==='high'&&valid(x[field]?.date));const completeEnough=allRequiredVerified&&!conflicts.length;patch.date_verification_status=completeEnough?'verified':'needs_review';patch.date_verified_at=new Date().toISOString();patch.date_verification_source_document_id=doc.id;patch.date_verification_note=[verified.length?`Verified from ${doc.filename}: ${verified.join('; ')}`:`No high-confidence dates verified from ${doc.filename}.`,review.length?`Review: ${review.join('; ')}`:'',conflicts.length?`Conflicts: ${conflicts.join('; ')}`:''].filter(Boolean).join(' ');
  const updated=await svc.entities.Student.update(student.id,patch);await svc.entities.AuditLog.create({action:'student_dates_verified',entity_type:'Student',entity_id:student.id,details:`Verified IEP/evaluation dates from document ${doc.id}. Status: ${patch.date_verification_status}. Fields updated: ${Object.keys(patch).filter(k=>fields.includes(k)).join(', ')||'none'}.`});
  return Response.json({verified:completeEnough,status:patch.date_verification_status,student:updated,source_document:{id:doc.id,filename:doc.filename,iep_role:doc.iep_role},result:x,updated_fields:Object.keys(patch).filter(k=>fields.includes(k))});
 }catch(e){return Response.json({error:e?.message||'Date verification failed.'},{status:500})}
}
