import React from "react";
import { AlertTriangle } from "lucide-react";

// Standardized AI disclaimer shown on every AI-generated output in CaseCue.
// `extra` adds section-specific review guidance (e.g. FBA scope, amendment rules).
export default function AiDisclaimer({ extra, className }) {
  return (
    <div className={`flex items-start gap-2 rounded-xl bg-amber-50 border border-amber-200 px-4 py-3 text-sm text-amber-800 ${className || ""}`}>
      <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
      <span>
        <strong>AI-GENERATED DRAFT — HUMAN REVIEW REQUIRED.</strong>{" "}
        This content was generated by CaseCue using uploaded records and available student information. Review for accuracy, completeness, compliance, and district requirements. CaseCue does not make educational, eligibility, placement, behavioral, or compliance decisions — final responsibility remains with the educational team.
        {extra && <span className="block mt-1">{extra}</span>}
      </span>
    </div>
  );
}