import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';

const SCHEMA={type:'object',properties:{first_name:{type:'string'},last_name:{type:'string'},grade:{type:'string'},document_type:{type:'string',enum:['IEP','Reevaluation','Evaluation','Eligibility Report','MDT Report','Psychological Report','BIP','FBA','Behavior Log','Discipline Report','504','Progress Report','Assessment Report','Report Card','Teacher Input','Parent Input','Service Provider Report','Medical Report','Transition Assessment','Other']},eligibility_category:{type:'string'},eligibility_categories:{type:'array',items:{type:'string'},maxItems:50},iep_date:{type:'string'},annual_review_due:{type:'string'},reevaluation_due:{type:'string'},confidence_note:{type:'string'}},required:['first_name','last_name','document_type','eligibility_categories']};

export default async function(req){
 try{
  const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:'Unauthorized'},{status:401});
  const body=await req.json().catch(()=>({}));if(!body.file_uri)return Response.json({error:'A student document is required.'},{status:400});
  const svc=base44.asServiceRole;let fileUrl=String(body.file_uri);if(!/^https?:\/\//i.test(fileUrl)){const signed=await svc.integrations.Core.CreateFileSignedUrl({file_uri:fileUrl,expires_in:600});fileUrl=signed.signed_url;}
  const prompt=`You are CaseCue Student Intake. Read the uploaded student record. It may be an IEP, MDT/MET 1/MET 2, evaluation, reevaluation, eligibility report, psychological report, 504, BIP/FBA, progress report, assessment, service-provider report, medical report, transition assessment, report card, teacher/parent input, or another school record.\n\nExtract ONLY facts explicitly printed in the source. Never guess a student's identity, grade, disability, eligibility, or dates. A diagnosis or suspected condition is not automatically an IDEA eligibility category. eligibility_categories must contain every explicitly documented disability/eligibility category found in the record, de-duplicated; do not impose a five- or ten-category cap. Return dates as YYYY-MM-DD only when explicit. Classify the document_type using the closest allowed value. If first or last name is not clearly documented, return an empty string. This intake is used to create a student record, so identity accuracy is critical.`;
  const result=await svc.integrations.Core.InvokeLLM({prompt,file_urls:[fileUrl],response_json_schema:SCHEMA,model:'automatic'});const x=typeof result==='object'?result:JSON.parse(result);
  if(!String(x.first_name||'').trim()||!String(x.last_name||'').trim())return Response.json({error:'CaseCue could not verify the student first and last name from this document. Use manual entry or a clearer student record.'},{status:422});
  const org=user.organization_id||user.data?.organization_id||'';const students=await svc.entities.Student.list('-updated_date',500);const first=String(x.first_name).trim(),last=String(x.last_name).trim(),grade=String(x.grade||'').trim();const exact=(students||[]).filter(s=>String(s.first_name||'').trim().toLowerCase()===first.toLowerCase()&&String(s.last_name||'').trim().toLowerCase()===last.toLowerCase()&&(!grade||!s.grade||String(s.grade).trim().toLowerCase()===grade.toLowerCase()));
  let student,created=false;if(exact.length===1){student=exact[0]}else{student=await svc.entities.Student.create({first_name:first,last_name:last,grade,eligibility_category:String(x.eligibility_category||x.eligibility_categories?.[0]||'').trim(),eligibility_categories:[...new Set((x.eligibility_categories||[]).filter(Boolean))].slice(0,50),iep_date:x.iep_date||'',annual_review_due:x.annual_review_due||'',reevaluation_due:x.reevaluation_due||'',status:'active',roster_status:'active',organization_id:org});created=true;}
  const doc=await svc.entities.Document.create({student_id:student.id,filename:body.filename||'Student record',file_url:body.file_uri,document_type:x.document_type||'Other',iep_role:x.document_type==='IEP'?'current':'supporting',date_uploaded:new Date().toISOString().slice(0,10),extraction_status:'pending',review_status:'none',is_private:true,organization_id:org});
  return Response.json({student,document:doc,created,extracted:x,matched_existing:!created});
 }catch(e){return Response.json({error:e?.message||'Student intake failed.'},{status:500})}
}
