import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { CASECUE_SYSTEM_PROMPT } from '../../shared/casecueContext.ts';

const SCHEMA={type:'object',properties:{items:{type:'array',items:{type:'object',properties:{student_id:{type:'string'},student_name:{type:'string'},student_match_confidence:{type:'string',enum:['high','medium','low','unmatched']},pages:{type:'string'},detected_title:{type:'string'},evidence_type:{type:'string'},subject:{type:'string'},skills:{type:'array',items:{type:'string'}},suggested_goal_id:{type:'string'},goal_match_confidence:{type:'string',enum:['high','medium','low','none']},goal_alignment:{type:'string'},score_earned:{type:'number'},score_possible:{type:'number'},percentage:{type:'number'},scoring_confidence:{type:'string',enum:['high','medium','low','not_scored']},scoring_basis:{type:'string'},qualitative_notes:{type:'string'},teacher_observation_draft:{type:'string'},error_patterns:{type:'array',items:{type:'string'}},strengths_observed:{type:'array',items:{type:'string'}},cautions:{type:'array',items:{type:'string'}}},required:['student_id','student_name','student_match_confidence','detected_title','skills','suggested_goal_id','goal_match_confidence','goal_alignment','score_earned','score_possible','percentage','scoring_confidence','scoring_basis','qualitative_notes','teacher_observation_draft','error_patterns','strengths_observed','cautions']}}},required:['items']};

export default async function(req){
 try{
  const base44=createClientFromRequest(req); const user=await base44.auth.me(); if(!user)return Response.json({error:'Unauthorized'},{status:401});
  const body=await req.json().catch(()=>({})); const fileUri=String(body.file_uri||''); if(!fileUri)return Response.json({error:'A PDF or scanned assignment packet is required.'},{status:400});
  const signed=await base44.asServiceRole.integrations.Core.CreateFileSignedUrl({file_uri:fileUri,expires_in:900});
  const students=await base44.entities.Student.list('-updated_date',300); const goals=await base44.entities.Goal.list('-updated_date',1000);
  const roster=students.map(s=>({id:s.id,name:`${s.first_name} ${s.last_name}`,grade:s.grade||'',goals:goals.filter(g=>g.student_id===s.id).map(g=>({id:g.id,area:g.goal_area||'',text:g.goal_text||''}))}));
  const answerKey=String(body.answer_key||'').slice(0,12000); const rubric=String(body.rubric||'').slice(0,12000); const directions=String(body.teacher_directions||'').slice(0,6000);
  const prompt=`${CASECUE_SYSTEM_PROMPT}\n\nAnalyze this MULTI-STUDENT assignment packet for a special education teacher. Pages may be in random order and may contain work from different students.\n\nCASELOAD AND CURRENT IEP GOALS:\n${JSON.stringify(roster)}\n\nANSWER KEY: ${answerKey||'not provided'}\nRUBRIC: ${rubric||'not provided'}\nTEACHER DIRECTIONS: ${directions||'not provided'}\n\nTASK:\n- Separate the packet into individual student assignments using ONLY visible student names/identifiers and page continuity. Do not guess identity.\n- Match only to the supplied roster. If uncertain, student_id must be empty and confidence low/unmatched.\n- Identify the skill/task. Compare it to ONLY that student's supplied IEP goals and suggest the strongest applicable goal. Never invent or rewrite an IEP goal. If no appropriate goal exists, leave suggested_goal_id empty.\n- Score only when the visible work plus answer key/rubric makes scoring supportable. Never invent answers or a key.\n- Produce quantitative evidence when supportable: correct/total and percentage.\n- qualitative_notes and teacher_observation_draft must describe observable performance, errors, prompting only if visible/provided, and useful next instructional steps without diagnosing the student.\n- A general course grade is context, not proof of IEP goal mastery.\n- Flag illegible pages, uncertain identity, uncertain scoring, mixed pages, or weak goal alignment in cautions.\n- Nothing is final: teacher approval is required before records are saved.\nReturn one item per detected student assignment, JSON matching the schema.`;
  const result=await base44.asServiceRole.integrations.Core.InvokeLLM({prompt,file_urls:[signed.signed_url],response_json_schema:SCHEMA,model:'automatic'}); const data=typeof result==='object'?result:JSON.parse(result);
  for(const x of data.items||[]){if(x.score_possible>0)x.percentage=Math.round((Number(x.score_earned||0)/Number(x.score_possible))*1000)/10;else x.percentage=0; const s=students.find(v=>v.id===x.student_id); if(!s){x.student_id='';x.suggested_goal_id='';x.student_match_confidence='unmatched';} const g=goals.find(v=>v.id===x.suggested_goal_id); if(!g||g.student_id!==x.student_id){x.suggested_goal_id='';x.goal_match_confidence='none';}}
  return Response.json({items:data.items||[]});
 }catch(error){console.error('analyzeBatchStudentWork failed:',error);return Response.json({error:error.message||'Unable to analyze batch work.'},{status:500});}
}
