import React, { useState } from "react";
import { Link } from "react-router-dom";
import { Printer, FileDown, FileText, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";
import ExportGate from "@/components/shared/ExportGate";
import { printDoc, exportDocPdf, exportDocDocx } from "@/lib/docExport";
import { captureElement } from "@/lib/chartExport";

// Per-goal export: Print Graph (chart captured live), PDF, and DOCX report of
// the goal, its trend chart, and every logged data point — plus a link to the
// parent progress report flow.
export default function GoalReportExport({ student, goal, entries, statusLabel, getChartEl }) {
  const { toast } = useToast();
  const [busy, setBusy] = useState(false);

  const buildOpts = async () => {
    setBusy(true);
    try {
      const img = await captureElement(getChartEl?.());
      const rows = entries
        .slice()
        .sort((a, b) => (a.date || "").localeCompare(b.date || ""))
        .map(
          (p, i) =>
            `${i + 1}. ${p.date || "—"} — ${
              p.percentage != null
                ? `${p.percentage}%`
                : p.correct != null && p.total
                ? `${p.correct}/${p.total}`
                : "recorded"
            }${p.prompting_level && p.prompting_level !== "independent" ? ` · prompting: ${p.prompting_level}` : ""}`
        )
        .join("\n");

      return {
        title: `Goal Report — ${student.first_name} ${student.last_name}`,
        subtitle: `${goal.goal_area || "Goal"} · status: ${statusLabel || "—"}`,
        filename: `Goal-Report-${student.first_name}-${student.last_name}-${(goal.goal_area || "Goal").replace(/\s+/g, "-")}`,
        banner: "DRAFT — Educator Review Required. Goal report generated by CaseCue from your recorded data.",
        sections: [
          {
            heading: "Goal",
            body: [
              goal.goal_area && `Area: ${goal.goal_area}`,
              goal.goal_text,
              `Baseline: ${goal.baseline || "—"}`,
              `Target: ${goal.target || "—"}`,
              `Criterion: ${goal.criterion || "—"}`,
              `Measured by: ${goal.measurement_method || "—"}`,
            ]
              .filter(Boolean)
              .join("\n"),
          },
          ...(img
            ? [{ heading: "Progress Graph", body: "", image: img.dataUrl, imageWidth: img.w, imageHeight: img.h }]
            : []),
          { heading: "Progress Data", body: rows || "No progress data logged yet." },
          { heading: "Current Status", body: statusLabel || "—" },
        ],
      };
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="flex flex-wrap items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        disabled={busy}
        onClick={async () => {
          const opts = await buildOpts();
          if (!printDoc(opts)) toast({ title: "Allow pop-ups to print", variant: "destructive" });
        }}
      >
        <Printer className="h-3.5 w-3.5 mr-1" /> Print graph & report
      </Button>
      <ExportGate documentName="Goal report" onExport={async () => exportDocPdf(await buildOpts())}>
        <Button variant="outline" size="sm" disabled={busy}>
          <FileDown className="h-3.5 w-3.5 mr-1" /> PDF
        </Button>
      </ExportGate>
      <ExportGate documentName="Goal report" onExport={async () => exportDocDocx(await buildOpts())}>
        <Button variant="outline" size="sm" disabled={busy}>
          <FileText className="h-3.5 w-3.5 mr-1" /> DOCX
        </Button>
      </ExportGate>
      <Button asChild variant="ghost" size="sm" className="text-primary">
        <Link to="/progress-reports">
          <UsersRound className="h-3.5 w-3.5 mr-1" /> Parent progress report
        </Link>
      </Button>
    </div>
  );
}