import React,{useState}from'react';
import{Brain,FileSearch,Loader2,Sparkles,Save,CheckCircle2,AlertTriangle,Target,Copy}from'lucide-react';
import{base44}from'@/api/base44Client';
import{Card}from'@/components/ui/cards';
import{Button}from'@/components/ui/button';
import{useToast}from'@/components/ui/use-toast';

const SECTION_LABELS=[['student_snapshot','Student Snapshot'],['evaluation_findings','Evaluation / MDT Findings'],['strengths','Strengths'],['areas_of_need','Areas of Need'],['present_levels','Present Levels'],['disability_impact','Educational Impact'],['parent_teacher_input','Parent / Teacher Input'],['eligibility_discussion','Eligibility Discussion'],['assessment_plan_discussion','Assessment / Data Discussion'],['accommodations','Accommodation Considerations'],['sdi','SDI Considerations'],['services_review','Services Review'],['progress_measurement','Progress Measurement'],['lre_discussion','LRE / Participation Discussion'],['transition','Transition Considerations']];
const txt=v=>v?.draft||'';
export default function MetMdtBuilder({student}){
 const{toast}=useToast();const[mode,setMode]=useState('met2'),[busy,setBusy]=useState(false),[packet,setPacket]=useState(null),[saving,setSaving]=useState(false),[goalSaved,setGoalSaved]=useState({});
 const generate=async()=>{setBusy(true);setPacket(null);try{const r=await base44.functions.invoke('generateMetMdtPacket',{student_id:student.id,mode});setPacket(r.data?.packet||r.packet);toast({title:`${mode.toUpperCase()} packet ready`,description:'Review every section before saving anything to the student record.'})}catch(e){toast({title:'Could not build packet',description:e?.response?.data?.error||e.message,variant:'destructive'})}finally{setBusy(false)}};
 const savePresentLevels=async()=>{if(!packet?.present_levels?.draft)return;setSaving(true);try{await base44.entities.Student.update(student.id,{present_levels:packet.present_levels.draft,strengths:packet.strengths?.draft||student.strengths||'',areas_of_need:packet.areas_of_need?.draft||student.areas_of_need||''});toast({title:'Reviewed present levels saved',description:'Present levels, strengths and needs were saved to Student 360. Official IEP team approval is still required.'})}catch(e){toast({title:'Save failed',description:e.message,variant:'destructive'})}finally{setSaving(false)}};
 const saveGoal=async(g,i)=>{try{const user=await base44.auth.me();const org=user?.organization_id||user?.data?.organization_id||'';const created=await base44.entities.Goal.create({student_id:student.id,organization_id:org,goal_area:g.goal_area||'',goal_text:g.goal_text||'',baseline:g.baseline||'',target:g.target||'',condition:g.condition||'',criterion:g.criterion||'',measurement_method:g.measurement_method||'',progress_monitoring_method:g.progress_monitoring_method||'',status:'revision'});setGoalSaved(v=>({...v,[i]:created.id}));toast({title:'Goal saved as revision draft',description:'It is not an active/final IEP goal until reviewed and approved by the IEP team.'})}catch(e){toast({title:'Goal save failed',description:e.message,variant:'destructive'})}};
 const savePacket=async()=>{if(!packet)return;try{const user=await base44.auth.me();await base44.entities.SavedReport.create({student_id:student.id,student_name:`${student.first_name} ${student.last_name}`,report_type:`${mode}_mdt_iep_packet`,organization_id:user?.organization_id||user?.data?.organization_id||'',content:packet});toast({title:'Packet saved to Reports history'})}catch(e){toast({title:'Packet save failed',description:e.message,variant:'destructive'})}};
 return <div className='space-y-5'>
  <Card className='overflow-hidden border-sky-100'><div className='bg-gradient-to-br from-slate-950 via-blue-950 to-sky-900 p-6 text-white'><div className='flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between'><div><div className='text-[10px] font-black uppercase tracking-[.22em] text-sky-300'>MET / MDT → IEP</div><h3 className='mt-1 text-2xl font-black'>Turn the evaluation record into an IEP-ready draft.</h3><p className='mt-2 max-w-3xl text-sm text-slate-300'>CaseCue reads the processed MDT/MET/evaluation record together with current goals, progress data, scanned student work and sessions. It drafts present levels, measurable goal options and the other IEP discussion sections without turning recommendations into team decisions.</p></div><Brain className='h-12 w-12 text-sky-300'/></div></div><div className='p-6'><div className='grid gap-3 md:grid-cols-2'><button onClick={()=>setMode('met1')} className={`rounded-2xl border p-4 text-left ${mode==='met1'?'border-blue-600 bg-blue-50':'hover:bg-slate-50'}`}><div className='font-black'>MET 1 · Existing Data Review</div><p className='mt-1 text-xs text-slate-500'>Organize existing data, current performance, concerns, gaps and evaluation questions. Goal drafts only appear when a real baseline already exists.</p></button><button onClick={()=>setMode('met2')} className={`rounded-2xl border p-4 text-left ${mode==='met2'?'border-blue-600 bg-blue-50':'hover:bg-slate-50'}`}><div className='font-black'>MET 2 · Results → IEP Prep</div><p className='mt-1 text-xs text-slate-500'>Turn completed evaluation findings into present levels, educational impact, goal options, accommodations/SDI and progress-monitoring drafts.</p></button></div><div className='mt-4 flex flex-wrap gap-2'><Button onClick={generate} disabled={busy} className='bg-slate-950 text-white'>{busy?<Loader2 className='mr-2 h-4 w-4 animate-spin'/>:<Sparkles className='mr-2 h-4 w-4'/>}{busy?'Building from records…':`Build ${mode.toUpperCase()} Draft`}</Button>{packet&&<><Button variant='outline' onClick={savePacket}><Save className='mr-2 h-4 w-4'/>Save packet</Button><Button variant='outline' onClick={()=>navigator.clipboard?.writeText(JSON.stringify(packet,null,2))}><Copy className='mr-2 h-4 w-4'/>Copy packet</Button></>}</div></div></Card>
  {busy&&<Card className='p-10 text-center'><Loader2 className='mx-auto h-8 w-8 animate-spin text-blue-600'/><div className='mt-3 font-black'>Reading MDT/MET, evaluation evidence, classroom work and progress data…</div><p className='mt-1 text-sm text-slate-500'>CaseCue is separating source facts from team decisions.</p></Card>}
  {packet&&<><Card className='p-5 border-amber-200 bg-amber-50/50'><div className='flex gap-3'><AlertTriangle className='h-5 w-5 shrink-0 text-amber-700'/><div><div className='font-black'>Educator / IEP Team Review Required</div><p className='text-sm text-slate-600'>Eligibility, placement, services, minutes, LRE and final goals are team decisions. This workspace drafts from the records; it does not finalize them.</p></div></div></Card>
  <div className='grid gap-4 xl:grid-cols-2'>{SECTION_LABELS.map(([key,label])=>{const s=packet[key];if(!s?.draft&&!s?.gaps?.length)return null;return <Card key={key} className={key==='present_levels'?'p-5 border-blue-200 bg-gradient-to-br from-white to-blue-50/50':'p-5'}><div className='flex items-start justify-between gap-3'><div><div className='text-[10px] font-black uppercase tracking-wider text-blue-700'>{label}</div>{s?.draft?<div className='mt-2 whitespace-pre-wrap text-sm leading-6'>{s.draft}</div>:<div className='mt-2 text-sm text-slate-500'>No supported draft yet.</div>}</div>{key==='present_levels'&&s?.draft&&<Button size='sm' onClick={savePresentLevels} disabled={saving}>{saving?'Saving…':'Save reviewed PLAAFP'}</Button>}</div>{s?.sources?.length>0&&<div className='mt-4 rounded-xl bg-slate-50 p-3'><div className='text-[10px] font-black uppercase text-slate-500'>Sources</div>{s.sources.map((x,i)=><div key={i} className='mt-1 text-xs text-slate-600'>• {x}</div>)}</div>}{s?.gaps?.length>0&&<div className='mt-3 rounded-xl bg-amber-50 p-3'><div className='text-[10px] font-black uppercase text-amber-800'>Needs verification</div>{s.gaps.map((x,i)=><div key={i} className='mt-1 text-xs text-amber-900'>• {x}</div>)}</div>}</Card>})}</div>
  <Card className='p-6'><div className='flex items-center gap-2'><Target className='h-5 w-5 text-blue-700'/><h3 className='text-lg font-black'>Evidence-linked goal drafts</h3></div><p className='mt-1 text-sm text-slate-500'>CaseCue only proposes a goal when the records support a measurable need and baseline. Save creates a revision draft, not an active/final goal.</p><div className='mt-4 space-y-3'>{(packet.goals||[]).map((g,i)=><div key={i} className='rounded-2xl border p-4'><div className='flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between'><div className='min-w-0 flex-1'><div className='flex flex-wrap items-center gap-2'><span className='font-black'>{g.goal_area||'Goal'}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${g.confidence==='high'?'bg-emerald-50 text-emerald-700':g.confidence==='medium'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'}`}>{g.confidence} evidence</span></div><p className='mt-2 text-sm font-semibold'>{g.goal_text}</p><div className='mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4 text-xs'><div className='rounded-xl bg-slate-50 p-3'><b>Baseline</b><div className='mt-1'>{g.baseline||'Needs verification'}</div></div><div className='rounded-xl bg-slate-50 p-3'><b>Target</b><div className='mt-1'>{g.target||g.criterion||'Needs verification'}</div></div><div className='rounded-xl bg-slate-50 p-3'><b>Measure</b><div className='mt-1'>{g.measurement_method||'Needs verification'}</div></div><div className='rounded-xl bg-slate-50 p-3'><b>Progress monitoring</b><div className='mt-1'>{g.progress_monitoring_method||'Needs verification'}</div></div></div>{g.rationale&&<p className='mt-3 text-xs text-slate-600'><b>Why this goal:</b> {g.rationale}</p>}{g.source_evidence?.length>0&&<div className='mt-2 text-xs text-blue-700'>{g.source_evidence.join(' · ')}</div>}</div><Button variant={goalSaved[i]?'outline':'default'} disabled={!!goalSaved[i]} onClick={()=>saveGoal(g,i)}>{goalSaved[i]?<><CheckCircle2 className='mr-1 h-4 w-4'/>Saved as revision</>:<>Save goal draft</>}</Button></div></div>)}{!(packet.goals||[]).length&&<div className='rounded-xl border border-dashed p-6 text-center text-sm text-slate-500'>No defensible goal draft yet. CaseCue found that more baseline/evaluation data is needed rather than inventing a goal.</div>}</div></Card>
  <div className='grid gap-4 lg:grid-cols-2'><Card className='p-5'><div className='font-black'>Data gaps before the IEP</div><div className='mt-3 space-y-2'>{(packet.data_gaps||[]).map((x,i)=><div key={i} className='rounded-xl bg-amber-50 px-3 py-2 text-sm'>{x}</div>)}{!(packet.data_gaps||[]).length&&<div className='text-sm text-emerald-700'>No major source gaps identified in this draft.</div>}</div></Card><Card className='p-5'><div className='font-black'>Meeting talking points</div><div className='mt-3 space-y-2'>{(packet.meeting_talking_points||[]).map((x,i)=><div key={i} className='flex gap-2 text-sm'><FileSearch className='mt-0.5 h-4 w-4 shrink-0 text-blue-600'/><span>{x}</span></div>)}</div></Card></div>
  </>}
 </div>
}
