import React,{useMemo,useState}from'react';
import{MapPinned,CheckCircle2,Circle,ArrowRight,FileSearch,ShieldCheck,Sparkles}from'lucide-react';
import{Card}from'@/components/ui/cards';
import{Button}from'@/components/ui/button';
import{base44}from'@/api/base44Client';
import{useAsync}from'@/lib/useAsync';

const NV_STEPS=[
 ['records','Evaluation / MDT Evidence','MDT, evaluation and current/previous IEP records'],
 ['present','Present Levels','Academic, communication, social/emotional, cognitive, health, motor, adaptive and other relevant performance'],
 ['strengths','Strengths, Concerns & Interests','Student strengths, parent concerns, preferences and interests'],
 ['factors','Special Factors','Behavior, assistive technology, language, vision, communication, hearing and SLD/dyslexia considerations'],
 ['goals','Annual Goals','Academic and functional measurable goals with progress measurement'],
 ['progress','Progress Reporting','How progress toward annual goals will be measured and reported'],
 ['supports','SDI, Accommodations & Supports','Specially designed instruction and supplementary aids/services'],
 ['services','Services','Special education and related services for team review'],
 ['assessment','State / District Assessments','Participation and accommodation considerations'],
 ['esy','ESY','Extended School Year consideration'],
 ['review','Final Review','Source check, gaps, compliance review and meeting preparation'],
];
const UNIVERSAL_STEPS=[['records','Source Records','Evaluation, eligibility and IEP evidence'],['present','Present Levels','Current academic and functional performance'],['strengths','Strengths & Concerns','Student and family input'],['factors','Required Considerations','State/federal special factors'],['goals','Measurable Annual Goals','Needs → baseline → measurable goal'],['supports','Supports & Services','SDI, accommodations, services and participation'],['review','Review & Meeting Prep','Source check, gaps and team review']];
const stateFrom=(student,docs)=>{const blob=[student?.state,student?.school_state,student?.address,...(docs||[]).map(d=>`${d.filename||''} ${JSON.stringify(d.processing_results||{}).slice(0,2500)}`)].filter(Boolean).join(' ').toLowerCase();if(/state of nevada|\bnevada\b|\bnv\b/.test(blob))return{code:'NV',name:'Nevada',confidence:'high',source:'uploaded record'};return{code:'US',name:'State not confirmed',confidence:'review',source:'teacher confirmation needed'}};
export default function StateAwareIepFlow({student,onNavigate}){
 const{data:docs}=useAsync(()=>base44.entities.Document.filter({student_id:student.id},'-date_uploaded',100),[student?.id]);
 const detected=useMemo(()=>stateFrom(student,docs),[student,docs]);const[state,setState]=useState('auto');const resolved=state==='auto'?detected.code:state;const steps=resolved==='NV'?NV_STEPS:UNIVERSAL_STEPS;
 const processed=(docs||[]).filter(d=>d.extraction_status==='processed');const evals=processed.filter(d=>['MDT Report','Evaluation','Reevaluation','Psychological Report','Eligibility Report'].includes(d.document_type));const ieps=processed.filter(d=>d.document_type==='IEP');
 const go=(key)=>{if(['records'].includes(key))return onNavigate?.('overview');if(['present','strengths','factors','goals','progress','supports','services','assessment','esy'].includes(key))return onNavigate?.('met-mdt');return onNavigate?.('compliance')};
 return <div className='space-y-5'>
  <Card className='overflow-hidden border-blue-100'><div className='bg-gradient-to-br from-slate-950 via-blue-950 to-blue-700 p-6 text-white'><div className='flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between'><div><div className='flex items-center gap-2 text-[10px] font-black uppercase tracking-[.22em] text-blue-200'><MapPinned className='h-4 w-4'/>State-Aware IEP Blueprint</div><h2 className='mt-2 text-2xl font-black'>{resolved==='NV'?'Nevada IEP Flow':'Universal IEP Flow'}</h2><p className='mt-2 max-w-3xl text-sm text-blue-100'>CaseCue uses the student's uploaded records to choose the workflow, then keeps the student's evidence separate from state-specific structure. The state changes the blueprint — it does not change the student's facts.</p></div><div className='rounded-2xl border border-white/20 bg-white/10 p-4 min-w-64'><div className='text-[10px] font-black uppercase tracking-wider text-blue-200'>Detected jurisdiction</div><div className='mt-1 text-xl font-black'>{detected.name}</div><div className='text-xs text-blue-100'>{detected.confidence==='high'?`High confidence · ${detected.source}`:'Confirm the state before using state-specific guidance.'}</div></div></div></div>
  <div className='p-5'><div className='flex flex-col gap-3 md:flex-row md:items-end md:justify-between'><div><div className='text-sm font-black'>State blueprint</div><p className='text-xs text-slate-500'>Auto-detect is the default. A teacher can correct it before drafting.</p></div><select value={state} onChange={e=>setState(e.target.value)} className='h-10 rounded-xl border bg-white px-3 text-sm'><option value='auto'>Auto-detect from records</option><option value='NV'>Nevada</option><option value='US'>Universal / state not confirmed</option></select></div>
  {resolved==='NV'&&<div className='mt-4 rounded-2xl border border-blue-100 bg-blue-50/60 p-4'><div className='font-black text-blue-950'>Nevada blueprint active</div><p className='mt-1 text-sm text-blue-900'>Built around the Nevada IEP sequence: Present Levels → strengths/concerns/interests → special factors → annual goals → progress reporting → SDI/supports/services → assessments → ESY → final review.</p></div>}
  <div className='mt-4 grid gap-3 sm:grid-cols-3'><div className='rounded-2xl border p-4'><div className='text-2xl font-black'>{processed.length}</div><div className='text-xs font-semibold text-slate-500'>Processed records</div></div><div className='rounded-2xl border p-4'><div className='text-2xl font-black'>{evals.length}</div><div className='text-xs font-semibold text-slate-500'>MDT / evaluation records</div></div><div className='rounded-2xl border p-4'><div className='text-2xl font-black'>{ieps.length}</div><div className='text-xs font-semibold text-slate-500'>IEP versions</div></div></div></div></Card>
  <Card className='p-5'><div className='flex items-center justify-between gap-3'><div><div className='font-black text-lg'>Guided IEP Flow</div><p className='text-sm text-slate-500'>Follow the state sequence without hunting through IEP Studio tabs.</p></div><ShieldCheck className='h-6 w-6 text-blue-700'/></div><div className='mt-5 space-y-2'>{steps.map(([key,label,desc],i)=>{const ready=key==='records'?processed.length>0:key==='present'?evals.length>0:false;return <button key={key} onClick={()=>go(key)} className='group flex w-full items-center gap-3 rounded-2xl border p-3.5 text-left hover:border-blue-300 hover:bg-blue-50/40'><div className='flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-slate-950 text-xs font-black text-white'>{i+1}</div>{ready?<CheckCircle2 className='h-5 w-5 shrink-0 text-emerald-600'/>:<Circle className='h-5 w-5 shrink-0 text-slate-300'/>}<div className='min-w-0 flex-1'><div className='font-bold'>{label}</div><div className='text-xs text-slate-500'>{desc}</div></div><ArrowRight className='h-4 w-4 text-slate-400 group-hover:text-blue-700'/></button>})}</div></Card>
  <Card className='p-5 border-amber-200 bg-amber-50/50'><div className='flex gap-3'><FileSearch className='h-5 w-5 shrink-0 text-amber-700'/><div><div className='font-black'>Blueprint ≠ student decision</div><p className='mt-1 text-sm text-slate-600'>State blueprints organize the workflow and review prompts. Student-specific present levels, goals, accommodations, services, placement, eligibility and other decisions must stay grounded in the student's records and educator/IEP-team review.</p></div></div></Card>
 </div>
}