import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { CASECUE_SYSTEM_PROMPT } from "../../shared/casecueContext.ts";
import { PRACTICE_MATERIAL_TYPES } from "../../shared/lessonPlanFormat.ts";

// Generates a completely ORIGINAL practice material aligned to the skills of
// an assignment — never copies the source's questions, passages, illustrations,
// branding, or proprietary layout.
export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const materialType = PRACTICE_MATERIAL_TYPES.includes(body.material_type) ? body.material_type : 'worksheet';
    const skills = typeof body.skills === 'string' ? body.skills.slice(0, 500) : '';
    const subject = typeof body.subject === 'string' ? body.subject.slice(0, 80) : '';
    const grade = typeof body.grade === 'string' ? body.grade.slice(0, 50) : '';
    const itemCount = Math.min(Math.max(Number(body.item_count) || 8, 1), 30);
    const includeAnswerKey = body.include_answer_key !== false;

    if (!skills) return Response.json({ error: 'Describe the skills the material should target.' }, { status: 400 });

    const prompt = `${CASECUE_SYSTEM_PROMPT}

Create a completely ORIGINAL ${materialType.replace(/_/g, ' ')} for a ${grade || 'K-12'} ${subject || 'resource'} lesson targeting: ${skills}.

STRICT ORIGINALITY RULES:
- Every question, passage, prompt, and layout must be newly written. Do NOT copy or closely paraphrase any existing worksheet, textbook, or publisher's material, branding, characters, or proprietary layout.
- You may align to the same skills, standards, and difficulty as an uploaded assignment, but the items must be your own original work.
- Content must be appropriate for the stated grade and skill level.

Format: a ready-to-print, clearly organized material with a title, student directions, and ${itemCount} items (or the natural equivalent for a ${materialType.replace(/_/g, ' ')}). Use plain text with clear numbering and section headers. Make it IEP-friendly: clean layout, generous spacing, reduced reading load where appropriate.

${includeAnswerKey ? 'Also produce a complete answer key (or rubric criteria if a rubric) with scoring guidance.' : 'Do not include an answer key.'}

Return JSON with keys: title, content, answer_key, note. The note must say: "Original material generated by CaseCue — teacher review required before student use."`;

    const schema = {
      type: "object",
      properties: {
        title: { type: "string" },
        content: { type: "string" },
        answer_key: { type: "string" },
        note: { type: "string" }
      },
      required: ["title", "content"]
    };

    const result = await base44.asServiceRole.integrations.Core.InvokeLLM({
      prompt,
      model: 'automatic',
      response_json_schema: schema
    });
    const material = typeof result === 'object' ? result : JSON.parse(result);
    return Response.json({ material });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}