import React,{useMemo}from'react';
import{Link}from'react-router-dom';
import{BookOpen,ClipboardCheck,Users,GraduationCap,ArrowRight,MessageSquare,TrendingUp,UploadCloud}from'lucide-react';
import{base44}from'@/api/base44Client';
import{useAsync}from'@/lib/useAsync';
import{Button}from'@/components/ui/button';
import{PremiumLineChart,PremiumDonutChart}from'@/components/shared/PremiumAnalytics';
import AnalyticsPdfButton from'@/components/shared/AnalyticsPdfButton';

const actions=[['Teach','Open lessons and classroom resources.','/w/gen_ed/lesson',BookOpen],['Grade My Class','Scan a stack or import classroom grades.','/w/gen_ed/grade',ClipboardCheck],['Groups & Reteach','Use verified performance to plan tomorrow.','/w/gen_ed/groups',Users],['Parent Contact','Create a clear classroom update.','/w/gen_ed/contact',MessageSquare]];
const pct=x=>x.current_grade_percent!=null?Number(x.current_grade_percent):(Number(x.score_possible)>0?Number(x.score_earned)/Number(x.score_possible)*100:null);

export default function GenEdHome(){
 const{data:assignments}=useAsync(()=>base44.entities.GradebookAssignment.list('-date',500),[]);
 const rows=assignments||[];
 const summary=useMemo(()=>{const scored=rows.filter(x=>pct(x)!=null);const vals=scored.map(pct).filter(Number.isFinite);return{students:new Set(rows.map(x=>x.student_id).filter(Boolean)).size,graded:rows.length,avg:vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0,reteach:new Set(scored.filter(x=>pct(x)<70).map(x=>x.student_id)).size}},[rows]);
 const trend=useMemo(()=>{const m={};[...rows].filter(x=>pct(x)!=null).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))).slice(-80).forEach(x=>{const k=String(x.date||'').slice(5)||'No date';const v=pct(x);m[k]??={name:k,total:0,count:0};m[k].total+=v;m[k].count++});return Object.values(m).map(x=>({name:x.name,average:Math.round(x.total/x.count)})).slice(-12)},[rows]);
 const bands=useMemo(()=>{const vals=rows.map(pct).filter(Number.isFinite);return[{name:'90–100',value:vals.filter(v=>v>=90).length},{name:'80–89',value:vals.filter(v=>v>=80&&v<90).length},{name:'70–79',value:vals.filter(v=>v>=70&&v<80).length},{name:'Below 70',value:vals.filter(v=>v<70).length}]},[rows]);

 return <div className="space-y-7">
  <section className="overflow-hidden rounded-[30px] bg-slate-950 p-7 text-white sm:p-9"><div className="text-xs font-black uppercase tracking-[.2em] text-sky-300">CaseCue Gen Ed</div><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Teach today. Know what to do tomorrow.</h1><p className="mt-3 max-w-2xl text-slate-300">Plan → Teach → Check → Grade → Group → Reteach. One classroom loop without replacing your SIS.</p><div className="mt-6 flex flex-wrap gap-2"><Link to="/w/gen_ed/grade"><Button className="bg-white text-slate-950 hover:bg-slate-100"><UploadCloud className="mr-2 h-4 w-4"/>Grade My Class</Button></Link><Link to="/instruction/lessons"><Button variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10">Open Lessons</Button></Link></div></section>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border bg-white p-5"><GraduationCap className="h-5 w-5 text-blue-600"/><div className="mt-3 text-2xl font-black">{summary.students}</div><div className="text-xs font-bold text-slate-500">Students with classroom data</div></div><div className="rounded-2xl border bg-white p-5"><ClipboardCheck className="h-5 w-5 text-emerald-600"/><div className="mt-3 text-2xl font-black">{summary.graded}</div><div className="text-xs font-bold text-slate-500">Grade records</div></div><div className="rounded-2xl border bg-white p-5"><TrendingUp className="h-5 w-5 text-violet-600"/><div className="mt-3 text-2xl font-black">{summary.avg}%</div><div className="text-xs font-bold text-slate-500">Average recorded performance</div></div><div className="rounded-2xl border bg-white p-5"><Users className="h-5 w-5 text-amber-600"/><div className="mt-3 text-2xl font-black">{summary.reteach}</div><div className="text-xs font-bold text-slate-500">Students to review for reteach</div></div></div>

  <div className="flex justify-end"><AnalyticsPdfButton title="CaseCue Gen Ed Classroom Analytics" subtitle="Classroom performance snapshot" filename="casecue-gen-ed-analytics" metrics={[{label:'Students with data',value:summary.students},{label:'Grade records',value:summary.graded},{label:'Average performance',value:`${summary.avg}%`},{label:'Review for reteach',value:summary.reteach}]} charts={[{type:'line',title:'Class Performance Trend',subtitle:'Average performance across saved grade records.',data:trend,series:[{key:'average',label:'Average %'}]},{type:'donut',title:'Performance Distribution',subtitle:'Saved grade records by performance band.',data:bands}]} notes={['Classroom analytics summarize saved records and do not replace the SIS or teacher judgment.']}/></div>
  <div className="grid gap-4 lg:grid-cols-2"><PremiumLineChart title="Class Performance Trend" subtitle="Average performance across real saved classroom grade records." data={trend} keys={[{key:'average',label:'Average %',color:'#2563eb'}]} area/><PremiumDonutChart title="Performance Distribution" subtitle="How saved grade records are distributed by performance band." data={bands} centerLabel={rows.filter(x=>pct(x)!=null).length}/></div>

  <div><div className="mb-3"><h2 className="text-xl font-black">Today’s classroom loop</h2><p className="text-sm text-slate-500">Move from instruction to action without digging through separate screens.</p></div><div className="grid gap-4 md:grid-cols-2">{actions.map(([title,desc,to,Icon],i)=><Link key={title} to={to} className="group rounded-2xl border bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-50 text-sky-700"><Icon className="h-5 w-5"/></div><span className="text-xs font-black text-slate-400">0{i+1}</span></div><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-1 text-sm text-slate-500">{desc}</p><div className="mt-5 inline-flex items-center text-sm font-bold text-blue-700">Open <ArrowRight className="ml-1 h-4 w-4 transition group-hover:translate-x-1"/></div></Link>)}</div></div>
 </div>;
}