import React, { useMemo, useState } from "react";
import { BookOpen, Loader2, Save, BadgeCheck, PlayCircle, Plus, AlertTriangle, SlidersHorizontal, Clock3, CheckCircle2 } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { useAsync } from "@/lib/useAsync";
import { useAuth } from "@/lib/AuthContext";
import { useToast } from "@/components/ui/use-toast";
import PageHeader from "@/components/PageHeader";
import { Card } from "@/components/ui/cards";
import { Button } from "@/components/ui/button";
import DayNavigator,{dayNameForDate} from "@/components/DayNavigator";
import AssignmentSource from "@/components/lessonStudio/AssignmentSource";
import AnalysisReview from "@/components/lessonStudio/AnalysisReview";
import PlanEditor from "@/components/lessonStudio/PlanEditor";
import VideoFinder from "@/components/lessonStudio/VideoFinder";
import ResourceFinder from "@/components/lessonStudio/ResourceFinder";
import OriginalPractice from "@/components/lessonStudio/OriginalPractice";
import LessonLibrary from "@/components/lessonStudio/LessonLibrary";
import { normalizePlan } from "@/lib/lessonPlanSchema";
import { cn } from "@/lib/utils";

function dateISO(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;}
function displayTime(v){if(!v)return"";const m=String(v).match(/^(\d{1,2}):(\d{2})$/);if(!m)return v;const h=Number(m[1]);return`${h%12||12}:${m[2]} ${h>=12?'PM':'AM'}`;}

export default function LessonStudio() {
  const { user } = useAuth(); const { toast } = useToast();
  const [tab,setTab]=useState("create"),[selectedDate,setSelectedDate]=useState(new Date()),[scheduleTarget,setScheduleTarget]=useState(null),[target,setTarget]=useState(null),[analysis,setAnalysis]=useState(null),[plan,setPlan]=useState(null);
  const [standards,setStandards]=useState([]),[goalIds,setGoalIds]=useState([]),[videos,setVideos]=useState([]),[resources,setResources]=useState([]),[practiceMaterials,setPracticeMaterials]=useState([]),[auditTrail,setAuditTrail]=useState([]),[editingId,setEditingId]=useState(null),[generating,setGenerating]=useState(false),[analyzing,setAnalyzing]=useState(false),[saving,setSaving]=useState(false),[libraryKey,setLibraryKey]=useState(0),[customize,setCustomize]=useState(false);
  const {data:students}=useAsync(()=>base44.entities.Student.list('-updated_date',200),[]); const {data:goals}=useAsync(()=>base44.entities.Goal.list(),[]); const {data:schedule}=useAsync(()=>base44.entities.ScheduleEntry.list('-day',500),[]); const {data:lessons}=useAsync(()=>base44.entities.Lesson.list('-date',300),[libraryKey]);

  const selectedDay=dayNameForDate(selectedDate),selectedISO=dateISO(selectedDate);
  const dayGroups=useMemo(()=>(schedule||[]).filter(e=>!e.archived&&e.day===selectedDay&&!String(e.notes||'').includes('NON-INSTRUCTIONAL / UNAVAILABLE')).sort((a,b)=>String(a.start_time||'').localeCompare(String(b.start_time||''))),[schedule,selectedDay]);
  const lessonsForDay=useMemo(()=>(lessons||[]).filter(l=>l.date===selectedISO),[lessons,selectedISO]);
  const lessonForEntry=e=>lessonsForDay.find(l=>l.group_label===e.group_name||((l.student_ids||[]).length&&(l.student_ids||[]).some(id=>(e.student_ids||[]).includes(id))));
  const selectedStudents=(students||[]).filter(s=>(target?.student_ids||[]).includes(s.id));
  const candidateGoals=(goals||[]).filter(g=>(target?.student_ids||[]).includes(g.student_id));
  const verifiedAccommodations=selectedStudents.filter(s=>s.accommodations).map(s=>({student:`${s.first_name} ${s.last_name}`,accommodations:s.accommodations}));
  const targetLabel=selectedStudents.length?selectedStudents.map(s=>`${s.first_name} ${s.last_name}`).join(", "):target?.group_label||"Instructional group";

  const makePlan=async(a,t,ids=null)=>{setGenerating(true);try{const studentIds=t?.student_ids||[];const matched=(goals||[]).filter(g=>studentIds.includes(g.student_id));const selectedGoalIds=ids||matched.map(g=>g.id);setGoalIds(selectedGoalIds);const selectedStudentsNow=(students||[]).filter(s=>studentIds.includes(s.id));const accommodations=selectedStudentsNow.filter(s=>s.accommodations).map(s=>({student:`${s.first_name} ${s.last_name}`,accommodations:s.accommodations}));const label=selectedStudentsNow.length?selectedStudentsNow.map(s=>`${s.first_name} ${s.last_name}`).join(", "):t?.group_label||"Instructional group";const std=a?.standards_alignment||[];setStandards(std);const res=await base44.functions.invoke("generateLessonFromAssignment",{analysis:a,goals:matched.filter(g=>selectedGoalIds.includes(g.id)).map(g=>({goal_area:g.goal_area,goal_text:g.goal_text,baseline:g.baseline,criterion:g.criterion,measurement_method:g.measurement_method})),verified_accommodations:accommodations,teacher_name:user?.full_name||"",date:selectedISO,grade:t?.grade||a?.grade_level||"",subject:a?.subject||"",target_label:label,standards:std,duration:t?.duration_minutes?`${t.duration_minutes} minutes`:undefined});const p=normalizePlan(res.data.plan);p.teacher=p.teacher||user?.full_name||"";p.date=selectedISO;p.grade_group=p.grade_group||t?.grade||a?.grade_level||"";p.subject_skill=p.subject_skill||a?.subject||"";setPlan(p);toast({title:"Full lesson ready",description:"The detailed plan is ready. Teach it now or customize anything you want."});}catch(e){toast({title:"Generation failed",description:e?.response?.data?.error||e.message,variant:"destructive"});}finally{setGenerating(false);}};
  const onAnalyzed=async({analysis:a,target:t})=>{setAnalysis(a);setTarget(t);setPlan(null);await makePlan(a,t);};
  const buildRecord=(status,isTemplate)=>({title:(plan.title||"").trim()||"Untitled lesson",date:selectedISO,source:"assignment",student_ids:target?.student_ids||[],subject:analysis?.subject||"",grade:target?.grade||analysis?.grade_level||"",group_label:target?.group_label||"",duration_minutes:target?.duration_minutes||undefined,goal_ids:goalIds,standards,analysis,plan,videos,resources,practice_materials:practiceMaterials,status,is_template:!!isTemplate,audit_trail:[...auditTrail,{action:editingId?(status==="approved"?"edited & approved":"edited"):(status==="approved"?"generated & approved":"generated"),user_name:user?.full_name||user?.email||"",timestamp:new Date().toISOString()}],objective:plan.iep_objective,essential_question:plan.essential_question,real_world_connection:plan.real_world_connection,mini_lecture:plan.mini_lecture,warm_up:plan.anticipatory_set,i_do:plan.i_do,we_do:plan.we_do,you_do:plan.you_do,accommodations:plan.accommodations_note,data_collection:plan.progress_monitoring,reflection:plan.teacher_reflection});
  const save=async(status,asTemplate=false)=>{if(!plan)return;setSaving(true);try{const record=buildRecord(status,asTemplate);if(editingId)await base44.entities.Lesson.update(editingId,record);else{const created=await base44.entities.Lesson.create(record);setEditingId(created.id);}setLibraryKey(k=>k+1);toast({title:status==="approved"?"Lesson approved and saved":asTemplate?"Reusable template saved":"Lesson saved to history"});}catch(e){toast({title:"Save failed",description:e.message,variant:"destructive"});}finally{setSaving(false);}};
  const loadLesson=l=>{setTab("create");setEditingId(l.id);setSelectedDate(new Date(`${l.date||selectedISO}T00:00:00`));setTarget({mode:(l.student_ids||[]).length?"students":"group",student_ids:l.student_ids||[],group_label:l.group_label||"",grade:l.grade||"",duration_minutes:l.duration_minutes});setScheduleTarget(null);setAnalysis(l.analysis||{});setStandards(l.standards||[]);setPlan(normalizePlan(l.plan||{}));setGoalIds(l.goal_ids||[]);setVideos(l.videos||[]);setResources(l.resources||[]);setPracticeMaterials(l.practice_materials||[]);setAuditTrail(l.audit_trail||[]);};
  const startSession=()=>{const p=new URLSearchParams();const sid=(target?.student_ids||[])[0];if(sid)p.set("student_id",sid);if(goalIds[0])p.set("goal_id",goalIds[0]);if(plan?.subject_skill)p.set("activity",plan.subject_skill);p.set("date",selectedISO);window.location.href=`/session-tracker?${p.toString()}`;};
  const chooseScheduleGroup=e=>{const existing=lessonForEntry(e);if(existing){loadLesson(existing);return;}setScheduleTarget({mode:"students",student_ids:e.student_ids||[],group_label:e.group_name||"",grade:"",duration_minutes:e.service_minutes||30});setTarget(null);setAnalysis(null);setPlan(null);window.scrollTo({top:0,behavior:"smooth"});};
  const reset=()=>{setScheduleTarget(null);setTarget(null);setAnalysis(null);setPlan(null);setStandards([]);setGoalIds([]);setVideos([]);setResources([]);setPracticeMaterials([]);setAuditTrail([]);setEditingId(null);setCustomize(false);};

  return <div><PageHeader title="Instruction" subtitle="Pick the day. Pick the group. Drop the work. CaseCue builds the full lesson." icon={BookOpen} actions={tab==="create"?<Button variant="outline" onClick={reset}><Plus className="h-4 w-4 mr-1"/>New lesson</Button>:null}/>
    <DayNavigator value={selectedDate} onChange={d=>{setSelectedDate(d);reset();}}/>
    <div className="flex gap-2 mt-4 mb-5">{[["create","Teach / Create"],["library","Lesson History"]].map(([k,label])=><button key={k} onClick={()=>setTab(k)} className={cn("rounded-full px-4 py-2 text-sm font-medium border",tab===k?"bg-primary text-white border-primary":"bg-card border-border")}>{label}</button>)}</div>
    {tab==="library"?<LessonLibrary students={students} goals={goals} onEdit={loadLesson} refreshKey={libraryKey}/>:!plan?<div className="space-y-5">
      {!scheduleTarget&&dayGroups.length>0&&<Card className="p-4 sm:p-5"><div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-wide text-blue-700">{selectedDay} instruction</div><h2 className="font-black text-lg mt-1">Pick a group</h2></div><div className="text-xs text-slate-500">{dayGroups.length} group{dayGroups.length===1?'':'s'}</div></div><div className="mt-4 space-y-2">{dayGroups.map(e=>{const existing=lessonForEntry(e);return <button key={e.id} onClick={()=>chooseScheduleGroup(e)} className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-left hover:border-blue-300 hover:shadow-sm transition"><div className="flex items-center gap-3"><div className={`h-10 w-10 rounded-xl flex items-center justify-center ${existing?'bg-emerald-100 text-emerald-700':'bg-blue-50 text-blue-700'}`}>{existing?<CheckCircle2 className="h-5 w-5"/>:<Clock3 className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><div className="font-bold truncate">{e.group_name}</div><div className="text-xs text-slate-500 mt-0.5">{displayTime(e.start_time)} · {e.service_minutes||30} min · {(e.student_ids||[]).length} student{(e.student_ids||[]).length===1?'':'s'}</div></div><span className={`text-xs font-bold ${existing?'text-emerald-700':'text-blue-700'}`}>{existing?'Lesson Ready':'Create Lesson'}</span></div></button>})}</div></Card>}
      {scheduleTarget&&<div className="flex items-center justify-between gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4"><div><div className="text-xs font-black uppercase tracking-wide text-blue-700">Selected group</div><div className="font-bold mt-1">{scheduleTarget.group_label}</div></div><Button size="sm" variant="outline" onClick={()=>setScheduleTarget(null)}>Change</Button></div>}
      <AssignmentSource key={`${selectedISO}-${scheduleTarget?.group_label||'manual'}`} students={students} initialTarget={scheduleTarget} onComplete={onAnalyzed} analyzing={analyzing||generating} onAnalyzing={setAnalyzing}/>{generating&&<Card className="p-8 text-center"><Loader2 className="h-8 w-8 animate-spin text-primary mx-auto"/><h3 className="font-semibold mt-3">Building the full lesson plan…</h3><p className="text-sm text-muted-foreground mt-1">Matching the work to verified goals and accommodations while writing the detailed admin-ready plan.</p></Card>}
      </div>:
      <div className="space-y-5"><Card className="p-5 sm:p-6"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Lesson ready</p><h2 className="text-xl font-bold mt-1">{plan.title||analysis?.detected_title||"Today's Lesson"}</h2><p className="text-sm text-muted-foreground mt-1">{targetLabel} · {plan.duration||target?.duration_minutes?`${target?.duration_minutes} minutes`:"30 minutes"} · {plan.subject_skill||analysis?.subject||"Instruction"}</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>save("approved")} disabled={saving} className="brand-gradient text-white"><BadgeCheck className="h-4 w-4 mr-2"/>Approve & Save</Button><Button variant="outline" onClick={startSession}><PlayCircle className="h-4 w-4 mr-2"/>Teach / Take Data</Button><Button variant="outline" onClick={()=>setCustomize(v=>!v)}><SlidersHorizontal className="h-4 w-4 mr-2"/>Customize</Button></div></div><div className="mt-4 flex items-start gap-2 rounded-xl bg-amber-50 border border-amber-200 px-4 py-3 text-sm text-amber-800"><AlertTriangle className="h-4 w-4 mt-0.5 shrink-0"/><span><strong>Educator review required.</strong> The full plan uses verified records where available; CaseCue does not change the IEP.</span></div></Card>
        <PlanEditor plan={plan} onChange={setPlan} verifiedAccommodations={verifiedAccommodations}/>
        {customize&&<div className="space-y-5"><Card className="p-5"><h3 className="font-semibold mb-3">Advanced lesson controls</h3><p className="text-sm text-muted-foreground mb-3">Goals are matched automatically. Change them only when this lesson addresses a different verified goal.</p><div className="flex flex-wrap gap-2">{candidateGoals.map(g=><button key={g.id} onClick={()=>setGoalIds(ids=>ids.includes(g.id)?ids.filter(x=>x!==g.id):[...ids,g.id])} className={cn("text-sm rounded-full border px-3 py-2",goalIds.includes(g.id)?"bg-primary text-white border-primary":"border-border")}>{g.goal_area||"Goal"}: {(g.goal_text||"").slice(0,60)}</button>)}</div><details className="mt-5"><summary className="cursor-pointer text-sm font-medium">View/correct assignment analysis</summary><div className="mt-4"><AnalysisReview analysis={analysis} onChange={setAnalysis}/></div></details></Card><VideoFinder analysis={analysis} plan={plan} grade={target?.grade||analysis?.grade_level} videos={videos} onChange={setVideos}/><ResourceFinder resources={resources} onChange={setResources}/><OriginalPractice analysis={analysis} plan={plan} grade={target?.grade||analysis?.grade_level} practiceMaterials={practiceMaterials} onChange={setPracticeMaterials}/></div>}
        <Card className="p-5"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>save("draft")} disabled={saving}><Save className="h-4 w-4 mr-2"/>Save to lesson history</Button><Button variant="outline" onClick={()=>save("draft",true)} disabled={saving}>Save as reusable template</Button></div><p className="text-xs text-muted-foreground mt-3">Regular lessons stay in Lesson History. Templates are opt-in. Sub Plans remain separate.</p></Card>
      </div>}
  </div>;
}