import React,{useMemo,useState}from'react';
import{Inbox,CheckCircle2,RotateCcw,UserRound,Clock3,Users}from'lucide-react';
import{base44}from'@/api/base44Client';import{useAsync}from'@/lib/useAsync';
import{Button}from'@/components/ui/button';import{Input}from'@/components/ui/input';import{useToast}from'@/components/ui/use-toast';

export default function ParaEvidenceInbox(){
 const{toast}=useToast();const[reviewNotes,setReviewNotes]=useState({});
 const{data:notes,refetch}=useAsync(()=>base44.entities.ParaNote.list('-submitted_at',500),[]);
 const{data:students}=useAsync(()=>base44.entities.Student.list('-last_name',500),[]);const{data:users}=useAsync(()=>base44.entities.User.list(),[]);const{data:assignments,refetch:refetchAssignments}=useAsync(()=>base44.entities.ParaAssignment.list('-assigned_at',500),[]);const[selectedPara,setSelectedPara]=useState('');
 const name=id=>{const s=(students||[]).find(x=>x.id===id);return s?((s.first_name||'')+' '+(s.last_name||'')).trim():'Student'};
 const submitted=useMemo(()=>(notes||[]).filter(n=>['submitted','reviewed','returned'].includes(n.review_status)),[notes]);
 const pending=submitted.filter(n=>n.review_status==='submitted'),history=submitted.filter(n=>n.review_status!=='submitted');
 const toggleAssignment=async studentId=>{if(!selectedPara)return toast({title:'Choose a para account first'});const st=(students||[]).find(x=>x.id===studentId),existing=(assignments||[]).find(x=>x.para_user_id===selectedPara&&x.student_id===studentId);let active=true,assignment=existing;if(existing){active=existing.active===false;assignment=await base44.entities.ParaAssignment.update(existing.id,{active})}else assignment=await base44.entities.ParaAssignment.create({para_user_id:selectedPara,student_id:studentId,active:true,assigned_at:new Date().toISOString()});const found=await base44.entities.ParaStudentAccess.filter({para_user_id:selectedPara,student_id:studentId}),access=found?.[0],payload={para_user_id:selectedPara,student_id:studentId,first_name:st?.first_name||'',last_name:st?.last_name||'',grade:st?.grade||'',support_summary:assignment?.support_summary||'',approved_supports:assignment?.approved_supports||[],active,source_assignment_id:assignment?.id||existing?.id||'',updated_at:new Date().toISOString()};if(access)await base44.entities.ParaStudentAccess.update(access.id,payload);else await base44.entities.ParaStudentAccess.create(payload);await refetchAssignments();};const review=async(n,status)=>{await base44.entities.ParaNote.update(n.id,{review_status:status,review_note:reviewNotes[n.id]||'',reviewed_at:new Date().toISOString()});await refetch();toast({title:status==='reviewed'?'Para observation accepted as reviewed evidence':'Observation returned for follow-up'});};
 const Card=({n})=><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-black"><UserRound className="h-4 w-4 text-blue-600"/>{name(n.student_id)}</div><div className="mt-1 text-xs text-slate-500">{n.date} {n.time||''} · {(n.context||'').replaceAll('_',' ')} · {(n.support_level||'').replaceAll('_',' ')}</div></div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-black text-amber-700">{n.review_status==='submitted'?'Needs review':n.review_status==='reviewed'?'Reviewed':'Returned'}</span></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">Objective observation</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{n.objective_observation}</p></div>{n.activity&&<div className="mt-3 text-sm"><b>Activity:</b> {n.activity}</div>}{(n.frequency!=null||n.duration_minutes!=null)&&<div className="mt-2 text-sm"><b>Data:</b> {n.frequency!=null?' Count '+n.frequency:''}{n.duration_minutes!=null?' · '+n.duration_minutes+' min':''}</div>}{n.student_response&&<div className="mt-2 text-sm"><b>Student response:</b> {n.student_response}</div>}{n.follow_up&&<div className="mt-2 text-sm"><b>Para follow-up:</b> {n.follow_up}</div>}{n.review_status==='submitted'?<div className="mt-4"><Input placeholder="Optional review note to para…" value={reviewNotes[n.id]||''} onChange={e=>setReviewNotes({...reviewNotes,[n.id]:e.target.value})}/><div className="mt-3 flex flex-wrap gap-2"><Button onClick={()=>review(n,'reviewed')} className="bg-emerald-700 hover:bg-emerald-800"><CheckCircle2 className="mr-2 h-4 w-4"/>Accept as Evidence</Button><Button variant="outline" onClick={()=>review(n,'returned')}><RotateCcw className="mr-2 h-4 w-4"/>Return for Follow-up</Button></div></div>:n.review_note&&<div className="mt-4 rounded-xl border p-3 text-sm"><b>Review note:</b> {n.review_note}</div>}</div>;
 return <div className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-blue-600"/><h3 className="font-black">Para Student Access</h3></div><p className="mt-1 text-xs text-slate-500">Assign only the students this para is authorized to support. Student details stay hidden in the Para workspace until assigned.</p><select className="mt-4 w-full max-w-md rounded-lg border p-2 text-sm" value={selectedPara} onChange={e=>setSelectedPara(e.target.value)}><option value="">Choose para account…</option>{(users||[]).filter(u=>u.role!=='admin').map(u=><option key={u.id} value={u.id}>{u.full_name||u.name||u.email}</option>)}</select>{selectedPara&&<div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(students||[]).map(st=>{const x=(assignments||[]).find(a=>a.para_user_id===selectedPara&&a.student_id===st.id),on=x&&x.active!==false;return <button key={st.id} onClick={()=>toggleAssignment(st.id)} className={'rounded-xl border p-3 text-left text-sm '+(on?'border-emerald-300 bg-emerald-50':'bg-white')}><div className="font-bold">{name(st.id)}</div><div className="mt-1 text-xs">{on?'Assigned':'Not assigned'}</div></button>})}</div>}</section><div className="rounded-[28px] bg-slate-950 p-7 text-white"><div className="text-xs font-black uppercase tracking-[.2em] text-sky-300">SPED Evidence Inbox</div><div className="mt-3 flex items-end justify-between gap-4"><div><h2 className="text-3xl font-black">Para observations ready for you.</h2><p className="mt-2 max-w-2xl text-slate-300">Review objective support data before deciding whether it belongs in the student's formal progress evidence.</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 text-center"><div className="text-3xl font-black">{pending.length}</div><div className="text-xs text-slate-300">need review</div></div></div></div><section><div className="mb-3 flex items-center gap-2"><Inbox className="h-5 w-5"/><h3 className="font-black">Needs Review</h3></div><div className="space-y-3">{pending.map(n=><Card key={n.id} n={n}/>)}{!pending.length&&<div className="rounded-2xl border border-dashed bg-white p-9 text-center text-sm text-slate-500">You're caught up. No para observations are waiting for review.</div>}</div></section>{history.length>0&&<section><div className="mb-3 flex items-center gap-2"><Clock3 className="h-5 w-5"/><h3 className="font-black">Review History</h3></div><div className="space-y-3">{history.slice(0,30).map(n=><Card key={n.id} n={n}/>)}</div></section>}</div>;
}