import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { ShieldCheck, TrendingUp, Target, BookOpen, CalendarDays, LockKeyhole, Send, CheckCircle2 } from 'lucide-react';

export default function ParentPortal(){
  const [params]=useSearchParams(); const [data,setData]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [requestType,setRequestType]=useState('question'); const [sending,setSending]=useState(false); const [sent,setSent]=useState('');
  useEffect(()=>{ const token=params.get('token'); if(!token){setError('This shared link is incomplete.');setLoading(false);return;} base44.functions.invoke('parentPortalView',{token}).then(r=>setData(r?.data||r)).catch(()=>setError('This link is invalid, expired, or has been revoked.')).finally(()=>setLoading(false)); },[params]);
  if(loading) return <div className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Opening secure CaseCue view…</div>;
  if(error||!data) return <div className="min-h-screen grid place-items-center bg-slate-50 p-6"><div className="max-w-md rounded-2xl bg-white border p-8 text-center"><LockKeyhole className="h-10 w-10 mx-auto text-slate-400"/><h1 className="font-bold text-xl mt-3">Shared view unavailable</h1><p className="text-sm text-slate-500 mt-2">{error}</p></div></div>;
  const submit=async(type=requestType)=>{const token=params.get('token');setSending(true);setSent('');try{await base44.functions.invoke('parentPortalRequest',{token,request_type:type,message});setSent(type==='acknowledgment'?'Acknowledgment sent':'Request sent securely');if(type!=='acknowledgment')setMessage('');}catch(e){setSent(e?.response?.data?.error||e.message||'Could not send request.');}finally{setSending(false)}};
  return <div className="min-h-screen bg-slate-50"><header className="bg-white border-b"><div className="max-w-5xl mx-auto px-5 py-4 flex items-center justify-between"><div className="font-extrabold text-xl text-blue-950">CaseCue <span className="text-slate-400 font-medium">Family View</span></div><div className="flex items-center gap-2 text-xs text-emerald-700"><ShieldCheck className="h-4 w-4"/>Read-only shared view</div></div></header><main className="max-w-5xl mx-auto p-5 space-y-5"><section><h1 className="text-2xl font-extrabold">{data.student?.first_name} {data.student?.last_initial}</h1><p className="text-slate-500 text-sm">Grade {data.student?.grade||'—'} · Information selected and shared by the education team</p></section>
  {data.goals&&<section className="rounded-2xl bg-white border p-5"><h2 className="font-bold flex gap-2 items-center"><Target className="h-5 w-5 text-blue-600"/>Goals</h2><div className="mt-3 space-y-3">{data.goals.map(g=><div key={g.id} className="rounded-xl bg-slate-50 p-4"><div className="font-semibold">{g.goal_area}</div><div className="text-sm text-slate-600 mt-1">{g.goal_text}</div>{g.target&&<div className="text-xs text-slate-500 mt-2">Target: {g.target}</div>}</div>)}</div></section>}
  {data.progress&&<section className="rounded-2xl bg-white border p-5"><h2 className="font-bold flex gap-2 items-center"><TrendingUp className="h-5 w-5 text-emerald-600"/>Progress</h2><div className="mt-3 space-y-4">{data.progress.map(g=>{const latest=g.points?.[g.points.length-1];return <div key={g.goal_id} className="rounded-xl border p-4"><div className="flex justify-between"><span className="font-semibold">{g.goal_area}</span><span className="font-bold text-emerald-700">{latest?.percentage==null?'No data yet':`${latest.percentage}%`}</span></div><div className="mt-3 flex items-end gap-1 h-20">{g.points?.length?g.points.map((p,i)=><div key={i} className="flex-1 bg-emerald-400 rounded-t" title={`${p.date}: ${p.percentage}%`} style={{height:`${Math.max(4,Math.min(100,Number(p.percentage||0)))}%`}}/>):<div className="text-sm text-slate-500">Progress data has not been shared yet.</div>}</div></div>})}</div></section>}
  {data.resources&&<section className="rounded-2xl bg-white border p-5"><h2 className="font-bold flex gap-2 items-center"><BookOpen className="h-5 w-5 text-sky-600"/>Resources</h2><div className="mt-3 grid md:grid-cols-2 gap-3">{data.resources.length?data.resources.map((r,i)=><div key={i} className="rounded-xl border p-4"><div className="text-xs text-sky-600 font-semibold">{r.category}</div><div className="font-semibold mt-1">{r.title}</div><p className="text-sm text-slate-500 mt-1">{r.description}</p>{r.url&&<a href={r.url} target="_blank" rel="noopener noreferrer" className="text-sm text-blue-600 font-semibold mt-2 inline-block">Open resource</a>}</div>):<div className="text-sm text-slate-500">No resources have been shared yet.</div>}</div></section>}
  {data.meetings&&<section className="rounded-2xl bg-white border p-5"><h2 className="font-bold flex gap-2 items-center"><CalendarDays className="h-5 w-5 text-amber-600"/>Upcoming Meetings</h2><div className="mt-3 space-y-2">{data.meetings.length?data.meetings.map((m,i)=><div key={i} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="font-semibold">{m.title}</span> · {m.date}{m.time?` · ${m.time}`:''}</div>):<div className="text-sm text-slate-500">No upcoming meetings shared.</div>}</div></section>}
  <section className="rounded-2xl bg-white border p-5"><h2 className="font-bold">Family acknowledgment & secure requests</h2><p className="text-sm text-slate-500 mt-1">Acknowledge that you reviewed this view, ask a question, request a meeting, or request an update. Messages go back into the educator's CaseCue workspace.</p><div className="flex flex-wrap gap-2 mt-4"><button disabled={sending} onClick={()=>submit('acknowledgment')} className="rounded-xl border px-3 py-2 text-sm font-semibold flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-600"/>I reviewed this update</button><select value={requestType} onChange={e=>setRequestType(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="question">Question</option><option value="meeting_request">Request a meeting</option><option value="resource_request">Request a resource</option><option value="update_request">Request an update</option></select></div><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} maxLength={2000} className="mt-3 w-full rounded-xl border p-3 text-sm" placeholder="Type a secure message to the education team…"/><button disabled={sending||!message.trim()} onClick={()=>submit()} className="mt-3 rounded-xl bg-blue-700 px-4 py-2 text-white text-sm font-semibold flex items-center gap-2"><Send className="h-4 w-4"/>{sending?'Sending…':'Send securely'}</button>{sent&&<div className="mt-3 text-sm text-emerald-700 font-semibold">{sent}</div>}</section>
  <footer className="text-center text-xs text-slate-400 py-4">This link is view-only and expires {new Date(data.expires_at).toLocaleDateString()}. Contact the school or educator if information appears incorrect.</footer></main></div>;
}