import React,{useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ClipboardCheck,Target,FolderOpen,ShieldCheck,TrendingUp,AlertTriangle,ExternalLink,FileStack,CheckCircle2} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {useAsync} from '@/lib/useAsync';
import PageHeader from '@/components/PageHeader';
import {Card} from '@/components/ui/cards';
import {Button} from '@/components/ui/button';
import {useToast} from '@/components/ui/use-toast';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar,Legend} from 'recharts';

const COLORS=['#2563eb','#7c3aed','#059669','#ea580c','#db2777','#0891b2','#65a30d','#dc2626'];
const full=s=>s?`${s.first_name||''} ${s.last_name||''}`.trim():'Student';
const strengthLabel=v=>({strong:'Strong Evidence',supporting:'Supporting Evidence',classroom_only:'Classroom Work',needs_review:'Needs Review'}[v]||'Evidence');

export default function ProgressMonitoringDay(){
 const navigate=useNavigate(),{toast}=useToast();
 const {data:students}=useAsync(()=>base44.entities.Student.list('-last_name',500),[]);
 const {data:goals}=useAsync(()=>base44.entities.Goal.list('-updated_date',1000),[]);
 const {data:progress}=useAsync(()=>base44.entities.ProgressData.list('date',2000),[]);
 const {data:evidence}=useAsync(()=>base44.entities.WorkEvidence.list('-date',2000),[]);
 const {data:sessions}=useAsync(()=>base44.entities.SessionRecord.list('-date',2000),[]);
 const [studentId,setStudentId]=useState('all');
 const sm=useMemo(()=>new Map((students||[]).map(s=>[s.id,s])),[students]);
 const filteredStudents=useMemo(()=>studentId==='all'?(students||[]):(students||[]).filter(s=>s.id===studentId),[students,studentId]);
 const visibleIds=useMemo(()=>new Set(filteredStudents.map(s=>s.id)),[filteredStudents]);
 const visibleGoals=useMemo(()=>(goals||[]).filter(g=>g.status==='active'&&visibleIds.has(g.student_id)),[goals,visibleIds]);
 const visibleEvidence=useMemo(()=>(evidence||[]).filter(e=>visibleIds.has(e.student_id)&&e.review_status!=='duplicate'),[evidence,visibleIds]);
 const duplicateProgress=useMemo(()=>(progress||[]).filter(p=>visibleIds.has(p.student_id)&&p.record_status==='duplicate'),[progress,visibleIds]);
 const visibleProgress=useMemo(()=>(progress||[]).filter(p=>visibleIds.has(p.student_id)&&p.record_status!=='duplicate'),[progress,visibleIds]);
 const visibleSessions=useMemo(()=>(sessions||[]).filter(s=>visibleIds.has(s.student_id)),[sessions,visibleIds]);
 const pending=visibleEvidence.filter(e=>!e.teacher_confirmed||e.review_status==='needs_review'||e.review_status==='auto_filed');
 const approved=visibleEvidence.filter(e=>e.teacher_confirmed||e.review_status==='approved');
 const linked=approved.filter(e=>e.goal_id);
 const chartRows=useMemo(()=>{
   const byDate=new Map();
   for(const p of visibleProgress){if(!p.date||p.percentage==null)continue;const g=(goals||[]).find(x=>x.id===p.goal_id),key=g?.goal_area||'Goal';const row=byDate.get(p.date)||{date:p.date};row[key]=Number(p.percentage);byDate.set(p.date,row)}
   return [...byDate.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)));
 },[visibleProgress,goals]);
 const goalSeries=useMemo(()=>[...new Set(visibleProgress.map(p=>(goals||[]).find(g=>g.id===p.goal_id)?.goal_area||'Goal'))],[visibleProgress,goals]);
 const studentBars=useMemo(()=>filteredStudents.map(s=>{const ev=visibleEvidence.filter(e=>e.student_id===s.id&&Number(e.score_possible)>0);const avg=ev.length?Math.round(ev.reduce((n,e)=>n+Number(e.percentage||0),0)/ev.length):0;return{name:full(s),average:avg,samples:ev.length}}).filter(x=>x.samples>0),[filteredStudents,visibleEvidence]);
 const openEvidence=async e=>{try{const r=await base44.functions.invoke('openEvidenceUrl',{evidence_id:e.id});const url=r.data?.signed_url||r.signed_url;if(!url)throw new Error(r.data?.error||r.error||'No viewable worksheet URL was returned.');if(r.data?.repaired||r.repaired)toast({title:'Worksheet recovered',description:'CaseCue restored this worksheet from the original SmartStack scan and linked it back to the evidence record.'});window.open(url,'_blank','noopener,noreferrer')}catch(err){toast({title:'Could not open worksheet',description:err?.response?.data?.error||err.message,variant:'destructive'})}};
 const auditText=`${approved.length} teacher-approved work sample${approved.length===1?'':'s'}, ${pending.length} awaiting review, ${linked.length} linked to IEP goal evidence, ${visibleSessions.length} session record${visibleSessions.length===1?'':'s'}. ${duplicateProgress.length} duplicate progress point${duplicateProgress.length===1?'':'s'} excluded from trends.`;
 return <div className='space-y-6'>
  <PageHeader title='Progress Monitoring Day' subtitle='Your evidence command center — scanned work, goal data, sessions, trends, and source worksheets in one place.' icon={ClipboardCheck}/>
  <section className='relative overflow-hidden rounded-[30px] bg-gradient-to-br from-slate-950 via-blue-950 to-violet-950 p-6 text-white shadow-2xl'>
   <div className='absolute -right-16 -top-16 h-56 w-56 rounded-full bg-fuchsia-400/20 blur-3xl'/><div className='absolute -bottom-20 left-20 h-64 w-64 rounded-full bg-cyan-400/15 blur-3xl'/>
   <div className='relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between'><div><div className='text-[10px] font-black uppercase tracking-[.2em] text-cyan-300'>CaseCue Proof Engine</div><h2 className='mt-2 text-3xl font-black'>Every approved data point should trace back to evidence.</h2><p className='mt-2 max-w-3xl text-sm text-slate-300'>SmartGrade work, manual probes, sessions, and IEP goals roll into one view. Classroom work stays visible even when it is not appropriate as formal IEP progress evidence.</p></div><select value={studentId} onChange={e=>setStudentId(e.target.value)} className='h-11 min-w-64 rounded-xl border border-white/20 bg-white/10 px-3 text-sm font-bold text-white'><option className='text-slate-900' value='all'>All students</option>{(students||[]).map(s=><option className='text-slate-900' key={s.id} value={s.id}>{full(s)}</option>)}</select></div>
  </section>
  <div className='grid grid-cols-2 lg:grid-cols-5 gap-3'>
   {[[FileStack,'Work samples',visibleEvidence.length,'All filed scans'],[CheckCircle2,'Approved',approved.length,'Teacher confirmed'],[Target,'Goal-linked',linked.length,'Counts toward goal evidence'],[AlertTriangle,'Needs review',pending.length,'Not final yet'],[ShieldCheck,'Sessions',visibleSessions.length,'Service documentation']].map(([I,l,v,s],i)=><Card key={l} className='p-4 overflow-hidden relative'><div className={`absolute inset-x-0 top-0 h-1 ${['bg-blue-500','bg-emerald-500','bg-violet-500','bg-amber-500','bg-cyan-500'][i]}`}/><I className='h-5 w-5 text-slate-700'/><div className='mt-3 text-3xl font-black'>{v}</div><div className='text-sm font-bold'>{l}</div><div className='text-xs text-slate-500'>{s}</div></Card>)}
  </div>
  <div className='grid xl:grid-cols-[1.25fr_.75fr] gap-5'>
   <Card className='p-5'><div className='flex items-center justify-between gap-3'><div><div className='text-xs font-black uppercase tracking-wider text-blue-700'>IEP Progress Trends</div><h3 className='text-xl font-black'>Goal performance over time</h3></div><TrendingUp className='h-5 w-5 text-blue-600'/></div>{chartRows.length?<div className='mt-5 h-80'><ResponsiveContainer width='100%' height='100%'><LineChart data={chartRows} margin={{top:8,right:18,left:-15,bottom:8}}><CartesianGrid strokeDasharray='3 3' stroke='#e2e8f0'/><XAxis dataKey='date' tick={{fontSize:11}}/><YAxis domain={[0,100]} unit='%' tick={{fontSize:11}}/><Tooltip/><Legend/>{goalSeries.map((s,i)=><Line key={s} type='monotone' dataKey={s} stroke={COLORS[i%COLORS.length]} strokeWidth={3} dot={{r:5}} activeDot={{r:7}} connectNulls={false}/>)}</LineChart></ResponsiveContainer></div>:<div className='py-20 text-center text-sm text-slate-500'>No goal-linked percentage data yet for this view.</div>}</Card>
   <Card className='p-5'><div className='text-xs font-black uppercase tracking-wider text-violet-700'>Classroom Evidence Snapshot</div><h3 className='text-xl font-black'>Average scored work</h3><p className='text-xs text-slate-500 mt-1'>Visual only. Classroom averages do not automatically equal IEP mastery.</p>{studentBars.length?<div className='mt-5 h-80'><ResponsiveContainer width='100%' height='100%'><BarChart data={studentBars} layout='vertical' margin={{left:30,right:10}}><CartesianGrid strokeDasharray='3 3' stroke='#f1f5f9'/><XAxis type='number' domain={[0,100]} unit='%'/><YAxis type='category' dataKey='name' width={110} tick={{fontSize:10}}/><Tooltip/><Bar dataKey='average' fill='#7c3aed' radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div>:<div className='py-20 text-center text-sm text-slate-500'>No scored work samples yet.</div>}</Card>
  </div>
  <Card className='p-5 border-emerald-200 bg-emerald-50/40'><div className='flex items-start gap-3'><ShieldCheck className='h-5 w-5 text-emerald-700 mt-0.5'/><div><div className='font-black'>Documentation trail</div><p className='text-sm text-slate-700 mt-1'>{auditText}</p><p className='text-xs text-slate-500 mt-2'>CaseCue keeps classroom evidence visible, but only teacher-approved goal matches should become formal IEP progress points. Prompting, accommodations, minutes, and setting should be confirmed by the educator instead of inferred from a worksheet.</p></div></div></Card>
  <div className='grid xl:grid-cols-[.9fr_1.1fr] gap-5'>
   <Card className='p-5'><div className='flex items-center gap-2'><Target className='h-5 w-5 text-blue-600'/><h3 className='text-lg font-black'>Active goals</h3></div><div className='mt-4 space-y-3 max-h-[650px] overflow-y-auto'>{visibleGoals.map((g,i)=>{const s=sm.get(g.student_id),pts=visibleProgress.filter(p=>p.goal_id===g.id),last=pts.at(-1),ev=visibleEvidence.filter(e=>e.goal_id===g.id);return <button key={g.id} onClick={()=>navigate(`/students/${g.student_id}`)} className='w-full rounded-2xl border p-4 text-left hover:bg-slate-50'><div className='flex items-center justify-between gap-2'><div><div className='text-[10px] font-black uppercase tracking-wider' style={{color:COLORS[i%COLORS.length]}}>{full(s)} · {g.goal_area||'IEP Goal'}</div><div className='mt-1 text-sm font-semibold line-clamp-2'>{g.goal_text}</div></div><div className='text-right'><div className='text-2xl font-black'>{last?.percentage!=null?`${last.percentage}%`:'—'}</div><div className='text-[10px] text-slate-500'>{pts.length} points · {ev.length} work samples</div></div></div></button>})}{!visibleGoals.length&&<div className='py-10 text-center text-sm text-slate-500'>No active goals in this view.</div>}</div></Card>
   <Card className='p-5'><div className='flex items-center justify-between gap-3'><div><div className='text-xs font-black uppercase tracking-wider text-fuchsia-700'>Student Work Folder</div><h3 className='text-lg font-black'>Recently filed scanned work</h3></div><FolderOpen className='h-5 w-5 text-fuchsia-600'/></div><div className='mt-4 space-y-2 max-h-[650px] overflow-y-auto'>{visibleEvidence.slice(0,100).map(e=>{const s=sm.get(e.student_id),a=e.analysis||{};return <div key={e.id} className='rounded-2xl border p-4'><div className='flex items-start justify-between gap-3'><div className='min-w-0'><div className='font-black truncate'>{full(s)}</div><div className='text-sm font-semibold truncate'>{e.title}</div><div className='mt-1 flex flex-wrap gap-1'>{e.score_possible>0&&<span className='rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black text-blue-800'>{e.score_earned}/{e.score_possible} · {e.percentage}%</span>}<span className={`rounded-full px-2 py-1 text-[10px] font-black ${e.teacher_confirmed?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-800'}`}>{e.teacher_confirmed?'APPROVED':'REVIEW'}</span>{e.evidence_strength&&<span className='rounded-full bg-violet-50 px-2 py-1 text-[10px] font-black text-violet-800'>{strengthLabel(e.evidence_strength)}</span>}</div>{(e.source_pages||a.source_pages||[]).length>0&&<div className='mt-2 text-xs text-slate-500'>Source page{(e.source_pages||a.source_pages).length===1?'':'s'} {(e.source_pages||a.source_pages).join(', ')}</div>}<div className='mt-2 text-xs text-slate-600 line-clamp-2'>{e.qualitative_notes||a.qualitative_notes||'Work sample filed.'}</div></div><div className='flex flex-col gap-2'><Button size='sm' variant='outline' onClick={()=>navigate(`/students/${e.student_id}`)}>Student 360</Button><Button size='sm' onClick={()=>openEvidence(e)}><ExternalLink className='h-3.5 w-3.5 mr-1'/>{e.file_url?'View work':'Recover & view'}</Button></div></div></div>})}{!visibleEvidence.length&&<div className='py-10 text-center text-sm text-slate-500'>No scanned work filed yet.</div>}</div></Card>
  </div>
 </div>;
}
