import React,{useMemo,useState} from 'react';
import { ClipboardCheck,CheckCircle2,Plus,Target } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useAsync } from '@/lib/useAsync';
import PageHeader from '@/components/PageHeader';
import { Card } from '@/components/ui/cards';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/components/ui/use-toast';

export default function ProgressMonitoringDay(){
 const {toast}=useToast(); const {data:students}=useAsync(()=>base44.entities.Student.list('-updated_date',300),[]); const {data:goals}=useAsync(()=>base44.entities.Goal.list('-updated_date',500),[]); const {data:progress,refetch}=useAsync(()=>base44.entities.ProgressData.list('-date',1000),[]); const [editing,setEditing]=useState(null); const [form,setForm]=useState({correct:'',total:'',notes:''});
 const sm=useMemo(()=>new Map((students||[]).map(s=>[s.id,s])),[students]);
 const rows=useMemo(()=>{const today=new Date();return (goals||[]).filter(g=>g.status==='active').map(g=>{const pts=(progress||[]).filter(p=>p.goal_id===g.id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const last=pts[0];const days=last?.date?Math.floor((today-new Date(`${last.date}T00:00:00`))/86400000):999;return{g,s:sm.get(g.student_id),last,days,due:days>=7}}).sort((a,b)=>Number(b.due)-Number(a.due)||b.days-a.days)},[goals,progress,sm]);
 const save=async r=>{const correct=Number(form.correct),total=Number(form.total);if(!Number.isFinite(correct)||!Number.isFinite(total)||total<=0){toast({title:'Enter correct and total',variant:'destructive'});return;}const pct=Math.round(correct/total*1000)/10;await base44.entities.ProgressData.create({student_id:r.g.student_id,goal_id:r.g.id,date:new Date().toISOString().slice(0,10),correct,total,percentage:pct,decimal:pct/100,qualitative_notes:form.notes,prompting_level:'independent'});setEditing(null);setForm({correct:'',total:'',notes:''});refetch();toast({title:'Progress data saved'});};
 return <div><PageHeader title='Progress Monitoring Day' subtitle='One queue for goals that need fresh data. CaseCue prioritizes active goals with no data in the last 7 days.' icon={ClipboardCheck}/><div className='grid sm:grid-cols-3 gap-3 mb-5'><Card className='p-4'><div className='text-2xl font-black'>{rows.filter(r=>r.due).length}</div><div className='text-xs text-slate-500'>Due for data</div></Card><Card className='p-4'><div className='text-2xl font-black'>{rows.filter(r=>!r.due).length}</div><div className='text-xs text-slate-500'>Recently monitored</div></Card><Card className='p-4'><div className='text-2xl font-black'>{rows.length}</div><div className='text-xs text-slate-500'>Active goals</div></Card></div><div className='space-y-3'>{rows.map(r=><Card key={r.g.id} className={`p-4 ${r.due?'border-amber-200':'border-emerald-100'}`}><div className='flex flex-col lg:flex-row lg:items-start gap-3'><div className='flex-1'><div className='flex items-center gap-2'><Target className='h-4 w-4 text-blue-600'/><div className='font-black'>{r.s?`${r.s.first_name} ${r.s.last_name}`:'Student'} · {r.g.goal_area||'Goal'}</div>{r.due?<span className='text-[10px] rounded-full bg-amber-100 text-amber-800 px-2 py-1 font-bold'>DATA DUE</span>:<span className='text-[10px] rounded-full bg-emerald-100 text-emerald-800 px-2 py-1 font-bold'>CURRENT</span>}</div><div className='text-sm text-slate-600 mt-1'>{r.g.goal_text}</div><div className='text-xs text-slate-400 mt-2'>{r.last?`Last data: ${r.last.date} · ${r.last.percentage??'—'}%`:'No progress data on file'}</div></div><Button variant='outline' onClick={()=>setEditing(editing===r.g.id?null:r.g.id)}><Plus className='h-4 w-4 mr-1'/>Log data</Button></div>{editing===r.g.id&&<div className='mt-4 grid sm:grid-cols-3 gap-3 rounded-xl bg-slate-50 p-4'><Input type='number' placeholder='Correct' value={form.correct} onChange={e=>setForm({...form,correct:e.target.value})}/><Input type='number' placeholder='Total' value={form.total} onChange={e=>setForm({...form,total:e.target.value})}/><Button onClick={()=>save(r)}><CheckCircle2 className='h-4 w-4 mr-1'/>Save</Button><Textarea className='sm:col-span-3' rows={2} placeholder='Qualitative observation (optional)' value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>}</Card>)}{!rows.length&&<Card className='p-10 text-center text-slate-500'>No active goals found.</Card>}</div></div>;
}
