import React,{useState}from'react';
import{CalendarClock,Upload,Sparkles,Plus,UserPlus,Pencil,Trash2,Coffee}from'lucide-react';
import{base44}from'@/api/base44Client';
import{useAsync}from'@/lib/useAsync';
import{Card}from'@/components/ui/cards';
import PageHeader from'@/components/PageHeader';
import{Button}from'@/components/ui/button';
import{Tabs,TabsList,TabsTrigger,TabsContent}from'@/components/ui/tabs';
import{useToast}from'@/components/ui/use-toast';
import UploadScheduleDialog from'@/components/schedule/UploadScheduleDialog';
import AddGroupDialog from'@/components/schedule/AddGroupDialog';
import AddStudentDialog from'@/components/schedule/AddStudentDialog';
import EditEntryDialog from'@/components/schedule/EditEntryDialog';
import GroupsTab from'@/components/schedule/GroupsTab';
import MinutesPanel from'@/components/schedule/MinutesPanel';
import ScheduleExportPanel from'@/components/schedule/ScheduleExportPanel';
import OptimizeDialog from'@/components/schedule/OptimizeDialog';
import ScheduleAlertsPanel from'@/components/schedule/ScheduleAlertsPanel';
import PullSourceList from'@/components/schedule/PullSourceList';
import{DAYS,DELIVERY_LABEL,studentName,sortStudentIdsAlpha}from'@/lib/scheduleUtils';
const displayTime=(v,f='12h')=>{if(!v)return'?';const m=String(v).match(/^(\d{1,2}):(\d{2})$/);if(!m)return v;const h=Number(m[1]);if(f==='24h')return`${String(h).padStart(2,'0')}:${m[2]}`;return`${h%12||12}:${m[2]} ${h>=12?'PM':'AM'}`};
export default function Schedule(){
 const{toast}=useToast();const{data:students}=useAsync(()=>base44.entities.Student.list('-updated_date',200),[]);const{data:goals}=useAsync(()=>base44.entities.Goal.list('-created_date',1000),[]);const{data:sessionLogs}=useAsync(()=>base44.entities.SessionLog.list('-date',500),[]);const{data:entries,refetch}=useAsync(()=>base44.entities.ScheduleEntry.list('-day',500),[]);const[dialog,setDialog]=useState(null),[optimizeOpen,setOptimizeOpen]=useState(false),[editing,setEditing]=useState(null);const timeFormat='12h';const active=(entries||[]).filter(e=>!e.archived);const isBlocked=e=>String(e.notes||'').includes('NON-INSTRUCTIONAL / UNAVAILABLE');
 const clearSchedule=async()=>{if(!active.length||!window.confirm(`Clear the current schedule? This archives ${active.length} blocks so you can replace it.`))return;try{await Promise.all(active.map(e=>base44.entities.ScheduleEntry.update(e.id,{archived:true})));await refetch();toast({title:'Schedule cleared',description:'Previous blocks were archived.'})}catch(e){toast({title:'Could not clear schedule',description:e.message,variant:'destructive'})}};
 const remove=async id=>{try{await base44.entities.ScheduleEntry.delete(id);refetch();toast({title:'Schedule block deleted'})}catch(e){toast({title:'Delete failed',description:e.message,variant:'destructive'})}};
 return <div><PageHeader title='Instruction & Schedule' subtitle='Bell schedule + student schedules + IEP goals → clean groups, daily instruction, minutes, and alerts.' icon={CalendarClock} actions={<><Button onClick={()=>setDialog('upload')} className='brand-gradient text-white'><Upload className='h-4 w-4'/>Build My Schedule</Button><Button variant='outline' onClick={()=>setOptimizeOpen(true)}><Sparkles className='h-4 w-4 text-primary'/>Optimize Groups</Button><Button variant='outline' onClick={()=>setDialog('group')}><Plus className='h-4 w-4'/>Add Group</Button><Button variant='outline' onClick={()=>setDialog('student')}><UserPlus className='h-4 w-4'/>Add Student</Button><Button variant='outline' onClick={clearSchedule} className='border-rose-300 text-rose-700'><Trash2 className='h-4 w-4'/>Clear / Replace</Button></>} />
 <ScheduleAlertsPanel students={students||[]} entries={entries||[]} goals={goals||[]} onRefresh={refetch}/>
 <Tabs defaultValue='weekly' className='w-full mt-6'><TabsList className='mb-4'><TabsTrigger value='weekly'>Daily / Weekly Schedule</TabsTrigger><TabsTrigger value='groups'>IEP Goal Groups</TabsTrigger><TabsTrigger value='minutes'>Minutes & Planning</TabsTrigger></TabsList><TabsContent value='weekly' className='space-y-6'>{active.length===0&&<Card className='p-8 text-center'><CalendarClock className='h-10 w-10 text-primary mx-auto'/><p className='font-semibold mt-3'>Build your SPED schedule</p><p className='text-sm text-muted-foreground mt-1 max-w-xl mx-auto'>Upload the school bell schedule and student/SPED schedules together. CaseCue can use rules such as “last 30 minutes of class,” group students by IEP goal area, and flag problems before you publish the plan.</p><Button onClick={()=>setDialog('upload')} className='brand-gradient text-white mt-4'><Upload className='h-4 w-4'/>Build My Schedule</Button></Card>}
 <div className='grid lg:grid-cols-5 gap-4'>{DAYS.map(day=><Card key={day} className='p-4'><h3 className='font-semibold text-sm mb-3 text-primary'>{day}</h3><div className='space-y-2'>{active.filter(e=>e.day===day).sort((a,b)=>String(a.start_time||'').localeCompare(String(b.start_time||''))).map(e=><div key={e.id} className={`rounded-lg border p-3 group relative ${isBlocked(e)?'border-sky-200 bg-sky-50/70':'border-border'}`}><div className='absolute top-2 right-2 flex gap-1 opacity-0 group-hover:opacity-100'><button onClick={()=>setEditing(e)} className='rounded p-1 text-muted-foreground hover:bg-accent'><Pencil className='h-3.5 w-3.5'/></button><button onClick={()=>remove(e.id)} className='rounded p-1 text-muted-foreground hover:text-rose-500'><Trash2 className='h-3.5 w-3.5'/></button></div><div className='font-medium text-sm pr-10 flex items-center gap-1.5'>{isBlocked(e)&&<Coffee className='h-3.5 w-3.5 text-sky-700'/>}{e.group_name}</div><div className='text-xs text-muted-foreground'>{displayTime(e.start_time,timeFormat)}–{displayTime(e.end_time,timeFormat)} · {DELIVERY_LABEL[e.delivery]||e.delivery}{e.period?` · ${e.period}`:''}</div><div className='text-xs text-muted-foreground'>{e.service_minutes||0} min · {e.teacher_classroom||'—'}</div>{e.student_ids?.length>0&&<div className='text-xs text-muted-foreground mt-1'>{sortStudentIdsAlpha(e.student_ids,students).map(id=>studentName(students,id)).join(', ')}</div>}{!isBlocked(e)&&<PullSourceList entry={e} students={students||[]}/>} {e.notes&&!isBlocked(e)&&!/^Imported from Mr\. D Resource Schedule PDF; recurrence expanded by weekday\.?$/i.test(String(e.notes).trim())&&<div className='mt-2 rounded-md bg-slate-50 px-2 py-1 text-[11px] text-slate-600'>{e.notes}</div>}</div>)}{active.filter(e=>e.day===day).length===0&&<p className='text-xs text-muted-foreground'>No sessions</p>}</div></Card>)}</div><ScheduleExportPanel entries={entries||[]} students={students||[]} timeFormat={timeFormat}/></TabsContent><TabsContent value='groups'><GroupsTab entries={entries||[]} students={students||[]} onRefresh={refetch}/></TabsContent><TabsContent value='minutes'><MinutesPanel students={students||[]} entries={entries||[]} sessionLogs={sessionLogs||[]}/></TabsContent></Tabs>
 <UploadScheduleDialog open={dialog==='upload'} onOpenChange={o=>setDialog(o?'upload':null)} students={students||[]} onSaved={refetch}/><AddGroupDialog open={dialog==='group'} onOpenChange={o=>setDialog(o?'group':null)} students={students||[]} onSaved={refetch}/><AddStudentDialog open={dialog==='student'} onOpenChange={o=>setDialog(o?'student':null)} students={students||[]} entries={entries||[]} onSaved={refetch}/><OptimizeDialog open={optimizeOpen} onOpenChange={setOptimizeOpen}/>{editing&&<EditEntryDialog entry={editing} students={students||[]} onClose={()=>setEditing(null)} onSaved={refetch}/>}</div>;
}
