import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, FileEdit, ShieldCheck, Activity, Brain, FileSearch, Stethoscope, HeartHandshake, Users, GraduationCap, ClipboardList, Timer, BookOpen, Building2, DollarSign, Languages, CheckCircle2 } from 'lucide-react';
import { Card } from '@/components/ui/cards';
import { Button } from '@/components/ui/button';

const CONFIG={
 '504':{title:'504 Studio',sub:'Access, accommodations, eligibility evidence, review dates and implementation tracking.',icon:ShieldCheck,actions:[['Open student records','/students'],['Review accommodations','/iep-studio'],['Prepare team meeting','/meetings']]},
 bip:{title:'BIP Studio',sub:'Behavior support planning from documented data, interventions and progress evidence.',icon:Activity,actions:[['Open BIP & FBA workspace','/iep-studio'],['Review evidence','/evidence-vault'],['Track behavior data','/data-center']]},
 fba:{title:'FBA Studio',sub:'Organize ABC evidence, patterns, hypotheses and team-review drafts without inventing behavioral function.',icon:Brain,actions:[['Open behavior workspace','/iep-studio'],['Review evidence','/evidence-vault'],['Prepare meeting','/meetings']]},
 mdt:{title:'MDT Studio',sub:'Evaluation and multidisciplinary evidence organized into a source-grounded student picture.',icon:FileSearch,actions:[['Upload evaluations','/iep-studio'],['Review student summary','/iep-studio'],['Run meeting mode','/meeting-navigator']]},
 evaluation:{title:'Evaluation Center',sub:'Manage evaluation records, assessment evidence, questions, timelines and team preparation.',icon:Stethoscope,actions:[['Upload evaluation records','/iep-studio'],['Compliance review','/iep-review'],['Schedule meeting','/meetings']]},
 parent:{title:'Parent Experience',sub:'Plain-language summaries, progress information and family-ready communication.',icon:HeartHandshake,actions:[['Open family portal','/family'],['Create parent summary','/iep-studio'],['Progress reports','/progress-reports']]},
 teacher:{title:'Teacher Portal',sub:'Daily caseload actions, documentation, instruction, progress and meeting preparation.',icon:Users,actions:[['Today','/app'],['Students','/students'],['Lesson Studio','/lesson-studio']]},
 success:{title:'Student Success Dashboard',sub:'Goals, progress, evidence, attendance and services connected in one student-centered view.',icon:GraduationCap,actions:[['Data Center','/data-center'],['Progress monitoring','/progress-monitoring-day'],['Evidence Vault','/evidence-vault']]},
 audit:{title:'Audit Center',sub:'Review missing evidence, deadlines, services and documentation before they become bigger problems.',icon:FileSearch,actions:[['Run compliance review','/iep-review'],['Reports','/reports'],['Evidence Vault','/evidence-vault']]},
 forms:{title:'Forms Generator',sub:'Build reusable parent, teacher, observation, meeting and documentation workflows.',icon:FileEdit,actions:[['Reports & exports','/reports'],['Meeting Center','/meetings'],['Configuration','/configuration']]},
 training:{title:'Training Academy',sub:'Role-based practice and workflow guidance for special education teams.',icon:BookOpen,actions:[['Practice Lab','/practice-lab'],['Help Center','/help'],['Resource Hub','/resource-hub']]},
 district:{title:'District Command Center',sub:'School and district visibility for caseloads, services, documentation and audit readiness.',icon:Building2,actions:[['Administration','/admin'],['Reports','/reports'],['Compliance Center','/iep-review']]},
 funding:{title:'Funding & Reimbursement Center',sub:'Organize service evidence and reimbursement-supporting documentation. Estimates require verified local program rules and records.',icon:DollarSign,actions:[['Service records','/session-tracker'],['Reports','/reports'],['Administration','/admin']]},
 language:{title:'Family Language Center',sub:'Prepare family-facing explanations for translation and accessible communication while preserving the verified record.',icon:Languages,actions:[['Parent summary','/iep-studio'],['Family portal','/family'],['Ask CaseCue','/ask-casecue']]},
 service:{title:'Service Delivery Center',sub:'Track specialized instruction and related-service delivery, missed minutes and documentation.',icon:Timer,actions:[['Session Tracker','/session-tracker'],['Progress reports','/progress-reports'],['Reports','/reports']]},
 meeting:{title:'Meeting Facilitator',sub:'Prepare and run a human, page-by-page meeting flow grounded in the uploaded IEP.',icon:ClipboardList,actions:[['Run Meeting Navigator','/meeting-navigator'],['Generate page-by-page script','/iep-studio'],['Meeting Center','/meetings']]},
};

export default function StudioWorkspace(){const nav=useNavigate();const key=new URLSearchParams(useLocation().search).get('module')||'audit';const c=CONFIG[key]||CONFIG.audit;const Icon=c.icon;return <div className="space-y-6"><section className="rounded-[26px] bg-gradient-to-br from-slate-950 via-blue-950 to-blue-700 text-white p-8"><div className="h-12 w-12 rounded-2xl bg-white/10 flex items-center justify-center"><Icon className="h-6 w-6"/></div><h1 className="text-3xl font-black mt-4">{c.title}</h1><p className="text-slate-200 mt-2 max-w-3xl">{c.sub}</p></section><Card className="p-6"><div className="text-xs font-black uppercase tracking-wider text-blue-700">Start here</div><h2 className="text-xl font-black mt-1">Connected workflow</h2><p className="text-sm text-slate-600 mt-1">This workspace connects to the records and tools already in IEP Suite Studio AI™ instead of creating a disconnected second copy of student data.</p><div className="grid md:grid-cols-3 gap-3 mt-5">{c.actions.map(([label,path],i)=><button key={label} onClick={()=>nav(path)} className="text-left rounded-xl border p-4 hover:border-blue-300 hover:shadow-md transition"><div className="flex items-center justify-between"><span className="h-7 w-7 rounded-full bg-blue-50 text-blue-700 flex items-center justify-center text-xs font-black">{i+1}</span><ArrowRight className="h-4 w-4 text-slate-400"/></div><div className="font-bold mt-3">{label}</div></button>)}</div></Card><Card className="p-6"><h2 className="font-black">Professional review guardrails</h2><div className="grid md:grid-cols-3 gap-3 mt-4">{['Verified records stay separate from drafts','Missing information is stated instead of invented','Team decisions remain with qualified educators and the IEP/504 team'].map(x=><div key={x} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-sm"><CheckCircle2 className="h-4 w-4 text-emerald-600 mt-0.5 shrink-0"/>{x}</div>)}</div></Card><Button variant="outline" onClick={()=>nav('/command-center')}>Back to Command Center</Button></div>}
