import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { CASECUE_SYSTEM_PROMPT } from '../../shared/casecueContext.ts';

const SECTION={type:'object',properties:{draft:{type:'string'},sources:{type:'array',items:{type:'string'}},gaps:{type:'array',items:{type:'string'}}},required:['draft','sources','gaps']};
const GOAL={type:'object',properties:{goal_area:{type:'string'},goal_text:{type:'string'},baseline:{type:'string'},target:{type:'string'},condition:{type:'string'},criterion:{type:'string'},measurement_method:{type:'string'},progress_monitoring_method:{type:'string'},benchmarks:{type:'array',items:{type:'string'}},source_evidence:{type:'array',items:{type:'string'}},rationale:{type:'string'},confidence:{type:'string',enum:['high','medium','low']}},required:['goal_area','goal_text','baseline','target','criterion','measurement_method','benchmarks','source_evidence','rationale','confidence']};
const SCHEMA={type:'object',properties:{meeting_type:{type:'string'},student_snapshot:SECTION,evaluation_findings:SECTION,strengths:SECTION,areas_of_need:SECTION,present_levels:SECTION,reading_present_level:SECTION,writing_present_level:SECTION,math_present_level:SECTION,social_emotional_present_level:SECTION,functional_present_level:SECTION,health_present_level:SECTION,disability_impact:SECTION,parent_teacher_input:SECTION,eligibility_discussion:SECTION,assessment_plan_discussion:SECTION,accommodations:SECTION,sdi:SECTION,services_review:SECTION,progress_measurement:SECTION,lre_discussion:SECTION,placement_rationale:SECTION,transition:SECTION,goals:{type:'array',items:GOAL},data_gaps:{type:'array',items:{type:'string'}},meeting_talking_points:{type:'array',items:{type:'string'}},source_inventory:{type:'array',items:{type:'string'}}},required:['meeting_type','student_snapshot','evaluation_findings','strengths','areas_of_need','present_levels','reading_present_level','writing_present_level','math_present_level','social_emotional_present_level','functional_present_level','health_present_level','disability_impact','parent_teacher_input','eligibility_discussion','assessment_plan_discussion','accommodations','sdi','services_review','progress_measurement','lre_discussion','placement_rationale','transition','goals','data_gaps','meeting_talking_points','source_inventory']};

export default async function(req){
 try{
  const base44=createClientFromRequest(req); const user=await base44.auth.me(); if(!user)return Response.json({error:'Unauthorized'},{status:401});
  const body=await req.json().catch(()=>({})); const studentId=String(body.student_id||''); const mode=String(body.mode||'met2').toLowerCase();
  if(!studentId)return Response.json({error:'A student is required.'},{status:400});
  if(!['met1','met2'].includes(mode))return Response.json({error:'Meeting type must be MET 1 or MET 2.'},{status:400});
  const student=await base44.entities.Student.get(studentId);
  const [docs,goals,progress,evidence,sessions]=await Promise.all([
   base44.entities.Document.filter({student_id:studentId},'-date_uploaded',100),
   base44.entities.Goal.filter({student_id:studentId},'-updated_date',100),
   base44.entities.ProgressData.filter({student_id:studentId},'-date',300),
   base44.entities.WorkEvidence.filter({student_id:studentId},'-date',300),
   base44.entities.SessionRecord.filter({student_id:studentId},'-date',300)
  ]);
  const processed=(docs||[]).filter(d=>d.extraction_status==='processed'&&d.processing_results);
  const sourceInventory=processed.map(d=>`${d.document_type} — ${d.filename}`);
  if(!processed.length)return Response.json({error:'No processed MDT/evaluation/student records are available yet. Upload and process the MDT/MET/evaluation report in IEP Studio first.'},{status:400});
  const documentContext=processed.map(d=>`===== ${d.document_type}: ${d.filename} =====\n${JSON.stringify(d.processing_results).slice(0,30000)}`).join('\n\n').slice(0,150000);
  const structured={student:{id:student.id,name:`${student.first_name||''} ${student.last_name||''}`.trim(),grade:student.grade||'',eligibility:student.eligibility_category||'',strengths:student.strengths||'',areas_of_need:student.areas_of_need||'',present_levels:student.present_levels||'',accommodations:student.accommodations||'',services:student.services||[]},existing_goals:(goals||[]).map(g=>({id:g.id,area:g.goal_area||'',text:g.goal_text||'',baseline:g.baseline||'',target:g.target||'',criterion:g.criterion||'',measurement_method:g.measurement_method||'',status:g.status||''})),recent_progress:(progress||[]).slice(0,50).map(p=>({date:p.date,goal_id:p.goal_id||'',correct:p.correct,total:p.total,percentage:p.percentage,notes:p.qualitative_notes||p.observation_notes||''})),recent_work:(evidence||[]).slice(0,50).map(e=>({date:e.date,title:e.title,goal_id:e.goal_id||'',score_earned:e.score_earned,score_possible:e.score_possible,percentage:e.percentage,evidence_strength:e.evidence_strength||'',notes:e.qualitative_notes||''})),recent_sessions:(sessions||[]).slice(0,50).map(s=>({date:s.date,goal_id:s.goal_id||'',activity:s.activity||'',quantitative:s.quantitative||{},qualitative:s.qualitative||'',status:s.status||''}))};
  const modeGuide=mode==='met1'
   ? `MET 1 / review-of-existing-data workflow. Organize what is already known, current performance, strengths, needs, prior interventions/services, existing evaluation evidence, parent/teacher input, and CLEAR DATA GAPS. assessment_plan_discussion should identify questions or areas the team may need to consider for additional evaluation; do not state that testing is required unless the team/source already decided it. Draft present levels only to the extent current evidence supports them. Goal drafts may be returned only when a measurable need and baseline are already sufficiently documented; otherwise leave goals empty and explain the missing baseline/data in data_gaps.`
   : `MET 2 / evaluation-results-and-IEP-preparation workflow. Synthesize evaluation/MDT findings, current classroom/work/session/progress evidence, strengths, needs, educational impact, parent/teacher input, and source-grounded present levels. eligibility_discussion should summarize evidence relevant to eligibility WITHOUT deciding eligibility. Draft measurable annual goals only for clearly documented needs with measurable baselines. Draft accommodations, SDI, progress measurement, services review, LRE discussion, and transition considerations only when evidence supports them; final eligibility, placement, services, minutes, LRE, and IEP decisions remain team decisions.`;
  const prompt=`${CASECUE_SYSTEM_PROMPT}\n\nYou are CaseCue's MET/MDT-to-IEP Draft Engine. Build a source-grounded educator-review packet for ${mode.toUpperCase()}.\n\nWORKFLOW: ${modeGuide}\n\nSTRICT RULES:\n- Use ONLY the uploaded/processed records and structured CaseCue data supplied below. Never invent test scores, diagnoses, observations, parent statements, services, dates, baselines, eligibility, placement, or supports.\n- A diagnosis is not automatically an IDEA eligibility category.\n- Recommendations in an MDT/evaluation remain recommendations, not team decisions.\n- For every section, list supporting sources using document type + filename and page when the extraction includes a page number. If support is absent, leave the draft concise and put the missing information in gaps.\n- Present levels should be usable for direct copy/paste into an IEP. Match the professional style of a strong completed Nevada IEP: name the assessment/data source and date when available, summarize the actual measurable result, then explain the effect on access/progress in the general education curriculum. Keep separate domain drafts for Reading, Writing, Math, Social-Emotional/Behavior, Functional/Adaptive, and Health when supported. Do not create a need where the data says the area is age-appropriate or not adversely affecting education.
- For Nevada-style domain present levels, use this writing flow when supported: Assessment/Data Source → measurable results/current performance → strengths → areas of need → educational impact/need for SDI. Write in polished school-based language that a teacher can copy and paste with minimal editing.\n- Goals must directly connect to a documented need and measurable baseline. Each goal should include condition, observable skill, baseline, target/criterion, measurement method, progress-monitoring method, rationale, confidence, and source evidence. Do not create a goal simply because a disability or low score exists.\n- Perform a DOMAIN-BY-DOMAIN goal review every time: Reading (decoding/phonics, fluency, vocabulary, comprehension), Writing (sentence/paragraph composition, conventions, spelling, written expression), Math (calculation, number sense, fact fluency, problem solving), Social-Emotional/Behavior (self-regulation, coping, social interaction, behavior/replacement skills), Executive Function/Study Skills (organization, task initiation, attention, completion), Communication (receptive/expressive/pragmatic when supported), Functional/Adaptive skills, and Transition when age-appropriate.\n- For EACH domain with a documented educational need AND measurable baseline/current performance, create a separate measurable annual goal draft. A student may therefore receive multiple goal drafts across Reading, Writing, Math, Social-Emotional, etc. Do not stop after generating one goal.
- Goal wording should follow the copy/paste style shown in strong Nevada IEPs: "By the annual review date, given [condition/material], [student] will [observable skill] with [criterion] across [number] consecutive progress-monitoring/data-collection opportunities, as measured by [specific method]." Include 2-4 progressive benchmark/short-term objective drafts when the evidence supports them. Benchmarks must build logically from baseline toward the annual target and must not invent unsupported baseline numbers.\n- If a domain has a documented need but the record does not contain enough measurable baseline data to write a defensible goal, DO NOT invent numbers. Put that domain in data_gaps and explain the specific baseline/data needed before the goal can be completed.\n- Do not generate a goal in a domain where the records do not establish an individualized educational need.\n- Existing goals are context; do not silently copy an old goal as a new goal unless current evidence still supports it.\n- Classroom work and progress data may strengthen current performance, but do not override standardized/evaluation findings or become eligibility decisions.\n- services_review, lre_discussion, eligibility_discussion and assessment_plan_discussion are DISCUSSION DRAFTS, not decisions.
- placement_rationale must be written only when current records contain enough information about services/settings/time or existing placement. When supported, use copy/paste-ready school language that explains: why the goals cannot be fully implemented in general education alone, why a less restrictive option would not provide sufficient intensity, the educational benefit of the proposed/current setting, percentage/time in general education only if explicitly documented or safely derived from an explicit source, and potential harmful effects. Never invent a placement percentage or make the placement decision for the team.
- accommodations and supplementary aids should be phrased as implementable IEP language with condition/frequency/location only when documented. Do not add a support merely because it is commonly used.\n- End-user review is required before anything is copied to an official IEP or district system.\n\nSTRUCTURED CASECUE DATA:\n${JSON.stringify(structured)}\n\nPROCESSED DOCUMENT CONTENT:\n${documentContext}\n\nReturn JSON matching the schema.`;
  const result=await base44.asServiceRole.integrations.Core.InvokeLLM({prompt,model:'automatic',response_json_schema:SCHEMA});
  const packet=typeof result==='object'?result:JSON.parse(result);
  packet.meeting_type=mode.toUpperCase(); packet.source_inventory=sourceInventory;
  return Response.json({packet});
 }catch(error){console.error('generateMetMdtPacket failed',error);return Response.json({error:error.message||'Unable to build MET/MDT packet.'},{status:500});}
}
