import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { CASECUE_SYSTEM_PROMPT } from '../../shared/casecueContext.ts';

const DOMAIN_SUMMARY={type:'object',properties:{domain:{type:'string'},earned:{type:'number'},possible:{type:'number'},percentage:{type:'number'},strengths:{type:'array',items:{type:'string'}},needs:{type:'array',items:{type:'string'}},present_level:{type:'string'},educational_impact:{type:'string'},data_limitations:{type:'array',items:{type:'string'}}},required:['domain','earned','possible','percentage','strengths','needs','present_level','educational_impact','data_limitations']};
const GOAL={type:'object',properties:{goal_area:{type:'string'},goal_text:{type:'string'},baseline:{type:'string'},target:{type:'string'},condition:{type:'string'},criterion:{type:'string'},measurement_method:{type:'string'},progress_monitoring_method:{type:'string'},rationale:{type:'string'},confidence:{type:'string',enum:['high','medium','low']},source_evidence:{type:'array',items:{type:'string'}}},required:['goal_area','goal_text','baseline','target','condition','criterion','measurement_method','progress_monitoring_method','rationale','confidence','source_evidence']};
const SCHEMA={type:'object',properties:{overall_summary:{type:'string'},present_levels_draft:{type:'string'},areas_of_need:{type:'array',items:{type:'string'}},strengths:{type:'array',items:{type:'string'}},domain_results:{type:'array',items:DOMAIN_SUMMARY},goal_drafts:{type:'array',items:GOAL},recommended_follow_up:{type:'array',items:{type:'string'}},cautions:{type:'array',items:{type:'string'}}},required:['overall_summary','present_levels_draft','areas_of_need','strengths','domain_results','goal_drafts','recommended_follow_up','cautions']};

export default async function(req){
  try{
    const base44=createClientFromRequest(req); const user=await base44.auth.me(); if(!user)return Response.json({error:'Unauthorized'},{status:401});
    const body=await req.json().catch(()=>({})); const assessmentId=String(body.assessment_id||'');
    if(!assessmentId)return Response.json({error:'An assessment is required.'},{status:400});
    const record=await base44.entities.BaselineAssessment.get(assessmentId);
    if(!record?.student_id)return Response.json({error:'Assessment record is missing its student.'},{status:400});
    const student=await base44.entities.Student.get(record.student_id);
    const assessment=record.assessment||{}; const results=record.results||{};
    const scored=Array.isArray(results.items)?results.items:[];
    if(!scored.length)return Response.json({error:'Enter and save scored item results before evaluating the baseline.'},{status:400});
    const itemIndex={}; for(const d of assessment.domains||[])for(const i of d.items||[])itemIndex[i.id]={...i,domain:d.domain};
    const rows=scored.filter(r=>itemIndex[r.item_id]).map(r=>{const max=Math.max(0,Number(itemIndex[r.item_id].max_points||0));const raw=Number(r.earned_points);const earned=Number.isFinite(raw)?Math.max(0,Math.min(max,raw)):NaN;return {item_id:r.item_id,domain:itemIndex[r.item_id].domain,skill:itemIndex[r.item_id].skill,prompt:itemIndex[r.item_id].prompt,max_points:max,earned_points:earned,teacher_note:String(r.teacher_note||'')};}).filter(r=>Number.isFinite(r.earned_points));
    if(!rows.length)return Response.json({error:'No valid scored items matched this generated assessment.'},{status:400});
    const totalExpected=Object.values(itemIndex).length;
    if(rows.length!==totalExpected)return Response.json({error:`Complete all baseline items before evaluation. ${rows.length} of ${totalExpected} items are scored.`},{status:400});
    const totals={}; for(const r of rows){if(!totals[r.domain])totals[r.domain]={earned:0,possible:0};totals[r.domain].earned+=r.earned_points;totals[r.domain].possible+=r.max_points;}
    const deterministic=Object.entries(totals).map(([domain,t]:any)=>({domain,earned:t.earned,possible:t.possible,percentage:t.possible>0?Math.round((t.earned/t.possible)*1000)/10:0}));
    const [goals,progress,docs]=await Promise.all([
      base44.entities.Goal.filter({student_id:student.id},'-updated_date',100),
      base44.entities.ProgressData.filter({student_id:student.id},'-date',100),
      base44.entities.Document.filter({student_id:student.id},'-date_uploaded',30)
    ]);
    const context={student:{name:`${student.first_name||''} ${student.last_name||''}`.trim(),grade:student.grade||'',strengths:student.strengths||'',areas_of_need:student.areas_of_need||'',present_levels:student.present_levels||''},assessment:{title:record.title||assessment.title||'Baseline Assessment',administered_date:record.administered_date||'',domain_totals:deterministic,scored_items:rows},existing_goals:(goals||[]).map(g=>({area:g.goal_area,text:g.goal_text,baseline:g.baseline,target:g.target,status:g.status})),recent_progress:(progress||[]).filter(p=>p.record_status!=='duplicate'&&p.record_status!=='superseded').slice(0,30).map(p=>({date:p.date,goal_id:p.goal_id,percentage:p.percentage,correct:p.correct,total:p.total,notes:p.qualitative_notes||''})),verified_sources:(docs||[]).filter(d=>d.extraction_status==='processed').slice(0,8).map(d=>`${d.document_type}: ${d.filename}`)};
    const prompt=`${CASECUE_SYSTEM_PROMPT}\n\nYou are CaseCue's Baseline Evaluation Engine. Analyze ONLY the educator-scored baseline assessment data supplied below, using existing verified student information only as context. Draft present levels and goal OPTIONS for educator/IEP-team review.\n\nSTRICT RULES:\n- The teacher's item scores are the source of truth. Never rescore an item, infer an unrecorded response, change earned points, or invent performance.\n- Use the deterministic domain totals exactly as supplied.\n- This baseline is an instructional probe, not a standardized evaluation, diagnosis, or eligibility determination. State limitations when a domain has few items, unclear scoring, or a narrow skill sample.\n- Present levels must name the assessment title/date when available, state measurable performance (earned/possible and percentage), identify specific demonstrated strengths and needs from scored skills/teacher notes, and explain educational impact cautiously.\n- Do not claim a disability caused a weakness unless a verified source explicitly establishes that link.\n- Create a goal draft only when the scored baseline establishes a clear educational need and a measurable starting point. If more baseline data is needed, put it in recommended_follow_up instead of inventing a goal.\n- Goal baseline must come directly from this scored assessment or other supplied verified data. Do not invent baseline numbers.\n- Goal target/criterion is a suggested educator-review target, not a legal or team decision. Use observable, measurable wording and a specific progress-monitoring method.\n- Prefer goals that measure the actual underlying skill, not merely 'score X percent on CaseCue'. The baseline statement can cite the probe score, but the annual goal should target the skill.\n- Do not automatically create goals for every low item or domain. Distinguish a limited sample from a defensible need.\n- Existing goals are context only; do not silently replace them.\n- Return a polished combined present_levels_draft plus separate domain results.\n\nDATA:\n${JSON.stringify(context).slice(0,150000)}\n\nReturn JSON matching the schema.`;
    const result=await base44.asServiceRole.integrations.Core.InvokeLLM({prompt,model:'automatic',response_json_schema:SCHEMA});
    const analysis=typeof result==='object'?result:JSON.parse(result);
    // Enforce deterministic scores after generation so AI cannot alter them.
    const byDomain=new Map((analysis.domain_results||[]).map((d:any)=>[d.domain,d]));
    analysis.domain_results=deterministic.map((t:any)=>{const d:any=byDomain.get(t.domain)||{domain:t.domain,strengths:[],needs:[],present_level:'',educational_impact:'',data_limitations:['CaseCue did not return narrative detail for this domain; educator review is required.']};return {...d,domain:t.domain,earned:t.earned,possible:t.possible,percentage:t.percentage};});
    return Response.json({analysis,domain_totals:deterministic});
  }catch(error){console.error('evaluateBaselineAssessment failed',error);return Response.json({error:error.message||'Unable to evaluate baseline assessment.'},{status:500});}
}