import React,{useState}from'react';
import{BellRing,Smartphone,CheckCircle2}from'lucide-react';
import{Button}from'@/components/ui/button';
import{Switch}from'@/components/ui/switch';
import{ensureNotificationPermission,getPhoneAlertPrefs,savePhoneAlertPrefs,showCaseCueNotification}from'@/lib/phoneAlerts';
import{useToast}from'@/components/ui/use-toast';
export default function PhoneAlertsSetup({compact=false}){
 const{toast}=useToast();const[prefs,setPrefs]=useState(()=>getPhoneAlertPrefs());const[busy,setBusy]=useState(false);const supported=typeof window!=='undefined'&&'Notification'in window;const permission=supported?Notification.permission:'unsupported';
 const enable=async()=>{setBusy(true);try{await ensureNotificationPermission();const next={...prefs,enabled:true};setPrefs(next);savePhoneAlertPrefs(next);await showCaseCueNotification('CaseCue phone alerts are on','You can now receive CaseCue reminders on this device.','/app','casecue-test');toast({title:'Phone alerts enabled'});}catch(e){toast({title:'Could not enable phone alerts',description:e.message,variant:'destructive'});}finally{setBusy(false)}};
 const set=(key,v)=>{const next={...prefs,[key]:v};setPrefs(next);savePhoneAlertPrefs(next)};
 if(compact)return <div className="rounded-xl border border-blue-100 bg-blue-50/60 p-3"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-xl bg-blue-600 text-white flex items-center justify-center"><Smartphone className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="text-sm font-bold">Phone alerts</div><div className="text-xs text-slate-500">{permission==='granted'&&prefs.enabled?'On for this device':'Get CaseCue reminders on your phone'}</div></div>{permission==='granted'&&prefs.enabled?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<Button size="sm" onClick={enable} disabled={busy||!supported}>{busy?'Enabling…':'Enable'}</Button>}</div></div>;
 return <div className="space-y-4"><div className="flex items-start gap-3"><div className="h-11 w-11 rounded-2xl bg-blue-600 text-white flex items-center justify-center"><BellRing className="h-5 w-5"/></div><div className="flex-1"><h3 className="font-black">CaseCue phone alerts</h3><p className="text-sm text-muted-foreground">Use system notifications for teaching-day reminders instead of relying only on email.</p></div></div>{permission!=='granted'||!prefs.enabled?<Button onClick={enable} disabled={busy||!supported} className="bg-slate-950 text-white">{busy?'Enabling…':'Enable alerts on this device'}</Button>:<div className="text-sm font-semibold text-emerald-700 flex items-center gap-2"><CheckCircle2 className="h-4 w-4"/>Phone alerts are enabled on this device</div>}
 {prefs.enabled&&<div className="space-y-2">{[['group_reminders','Upcoming groups','Alert me before a scheduled group'],['meeting_reminders','IEP / MET meetings','Remind me about upcoming meetings'],['tomorrow_ready','Tomorrow Ready','Evening summary of tomorrow’s teaching day'],['progress_reminders','Progress monitoring','Remind me when data still needs attention']].map(([key,title,sub])=><div key={key} className="flex items-center justify-between gap-4 rounded-xl border p-3"><div><div className="text-sm font-semibold">{title}</div><div className="text-xs text-muted-foreground">{sub}</div></div><Switch checked={!!prefs[key]} onCheckedChange={v=>set(key,v)}/></div>)}</div>}
 <p className="text-xs text-muted-foreground">Alerts depend on notification permission for this browser/device. Background delivery when CaseCue is fully closed requires the server push delivery service to be configured.</p></div>;
}