import React,{useEffect,useState} from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/cards';
import { Link2, ShieldCheck, Trash2 } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';

export default function ParentSharePanel({student}){
 const {toast}=useToast(); const [shares,setShares]=useState([]); const [busy,setBusy]=useState(false); const [sections,setSections]=useState(['academic_snapshot','progress','goals','resources']);
 const load=async()=>{try{const r=await base44.functions.invoke('parentPortalShare',{action:'list'});setShares((r.data?.shares||r.shares||[]).filter(s=>s.student_id===student.id));}catch{}};
 useEffect(()=>{load()},[student.id]);
 const toggle=s=>setSections(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);
 const create=async()=>{setBusy(true);try{const r=await base44.functions.invoke('parentPortalShare',{action:'create',student_id:student.id,allowed_sections:sections,expires_in_days:30});const d=r.data||r;const url=`${window.location.origin}/family?token=${encodeURIComponent(d.token)}`;await navigator.clipboard.writeText(url);toast({title:'Secure parent link copied',description:'View-only link expires in 30 days. You can revoke it anytime.'});load();}catch(e){toast({title:'Could not create link',description:e.message,variant:'destructive'})}finally{setBusy(false)}};
 const revoke=async id=>{await base44.functions.invoke('parentPortalShare',{action:'revoke',share_id:id});toast({title:'Parent link revoked'});load()};
 return <Card className="p-6"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center"><ShieldCheck className="h-5 w-5"/></div><div><h3 className="font-bold text-lg">CaseCue Family View</h3><p className="text-sm text-muted-foreground">Create an expiring, revocable, view-only link. Parents see only the sections you select—never teacher notes, private documents, IEP drafts, internal reviews, or other students.</p></div></div><div className="mt-5"><div className="text-sm font-semibold mb-2">Share these sections</div><div className="flex flex-wrap gap-2">{[['academic_snapshot','All Gen Ed grades'],['progress','SPED progress'],['goals','IEP goals'],['resources','Resources'],['upcoming_meetings','Upcoming meetings']].map(([key,label])=><button key={key} onClick={()=>toggle(key)} className={`px-3 py-2 rounded-xl border text-sm ${sections.includes(key)?'border-blue-500 bg-blue-50 text-blue-700':'border-slate-200 text-slate-500'}`}>{label}</button>)}</div><div className="mt-3 rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs text-sky-900"><b>Academic snapshot rule:</b> CaseCue can show every uploaded Gen Ed class for the student so families get the whole-school picture. Classes tied to the student's SPED service/goal areas are highlighted, but Gen Ed grades are never counted as IEP progress by themselves.</div><Button className="mt-4 brand-gradient text-white" disabled={busy||!sections.length} onClick={create}><Link2 className="h-4 w-4 mr-2"/>{busy?'Creating…':'Create & Copy Secure Link'}</Button><p className="text-xs text-muted-foreground mt-2">Default expiration: 30 days. The share token itself is not stored in CaseCue; only its SHA-256 hash is retained.</p></div>{shares.length>0&&<div className="mt-6 border-t pt-4"><div className="text-sm font-semibold mb-2">Active/recent links</div><div className="space-y-2">{shares.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><div className="text-sm font-medium">{s.status==='active'?'Active parent view':'Revoked parent view'}</div><div className="text-xs text-muted-foreground">Expires {new Date(s.expires_at).toLocaleDateString()} · Viewed {s.access_count||0} times</div></div>{s.status==='active'&&<Button variant="outline" size="sm" onClick={()=>revoke(s.id)}><Trash2 className="h-3.5 w-3.5 mr-1"/>Revoke</Button>}</div>)}</div></div>}</Card>;
}