import React,{useEffect,useState}from'react';
import{base44}from'@/api/base44Client';
import{Button}from'@/components/ui/button';
import{Card}from'@/components/ui/cards';
import{Link2,ShieldCheck,Trash2,KeyRound,Copy}from'lucide-react';
import{useToast}from'@/components/ui/use-toast';

export default function ParentSharePanel({student}){
 const{toast}=useToast();const[shares,setShares]=useState([]),[busy,setBusy]=useState(false),[sections,setSections]=useState(['academic_snapshot','progress','goals','resources']),[newShare,setNewShare]=useState(null);
 const load=async()=>{try{const r=await base44.functions.invoke('parentPortalShare',{action:'list'});setShares((r.data?.shares||r.shares||[]).filter(s=>s.student_id===student.id))}catch{}};
 useEffect(()=>{load()},[student.id]);
 const toggle=s=>setSections(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);
 const create=async()=>{setBusy(true);try{const r=await base44.functions.invoke('parentPortalShare',{action:'create',student_id:student.id,allowed_sections:sections,expires_in_days:7});const d=r.data||r,url=`${window.location.origin}/family?token=${encodeURIComponent(d.token)}`;await navigator.clipboard.writeText(url);setNewShare({url,code:d.access_code,expires:d.share?.expires_at});toast({title:'Family link copied',description:'Give the family the 6-digit access code separately.'});load()}catch(e){toast({title:'Could not create link',description:e.message,variant:'destructive'})}finally{setBusy(false)}};
 const revoke=async id=>{await base44.functions.invoke('parentPortalShare',{action:'revoke',share_id:id});toast({title:'Family link revoked'});load()};
 return <Card className="p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck className="h-5 w-5"/></div><div><h3 className="text-lg font-bold">CaseCue Family View</h3><p className="text-sm text-muted-foreground">Share only what the family needs to see. The link expires, can be revoked, and now requires a separate 6-digit access code.</p></div></div>
 <div className="mt-5"><div className="mb-2 text-sm font-semibold">Share these sections</div><div className="flex flex-wrap gap-2">{[['academic_snapshot','Class grades'],['progress','Goal progress'],['goals','IEP goals'],['resources','Home resources'],['upcoming_meetings','Upcoming meetings']].map(([key,label])=><button key={key} onClick={()=>toggle(key)} className={'rounded-xl border px-3 py-2 text-sm '+(sections.includes(key)?'border-blue-500 bg-blue-50 text-blue-700':'border-slate-200 text-slate-500')}>{label}</button>)}</div><div className="mt-3 rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs text-sky-900"><b>Keep it family-facing:</b> share the minimum information needed for the update. Internal notes, drafts, source documents, reviews, and other students are never included in Family View.</div><Button className="mt-4 brand-gradient text-white" disabled={busy||!sections.length} onClick={create}><Link2 className="mr-2 h-4 w-4"/>{busy?'Creating…':'Create Family Link + Code'}</Button><p className="mt-2 text-xs text-muted-foreground">Default expiration: 7 days. Send the link and access code through separate channels when practical. The raw link token and access code are not retained after creation; CaseCue stores hashes.</p></div>
 {newShare&&<div className="mt-5 rounded-2xl border-2 border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 text-sm font-black text-emerald-900"><KeyRound className="h-4 w-4"/>New family access code</div><div className="mt-2 font-mono text-3xl font-black tracking-[.25em] text-emerald-950">{newShare.code}</div><p className="mt-2 text-xs leading-5 text-emerald-900">This code is shown only now. Give it to the family separately from the copied link.</p><Button size="sm" variant="outline" className="mt-3 bg-white" onClick={()=>navigator.clipboard.writeText(newShare.code)}><Copy className="mr-1 h-3.5 w-3.5"/>Copy code</Button></div>}
 {shares.length>0&&<div className="mt-6 border-t pt-4"><div className="mb-2 text-sm font-semibold">Active/recent links</div><div className="space-y-2">{shares.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><div className="text-sm font-medium">{s.status==='active'?'Active family view':'Revoked family view'}</div><div className="text-xs text-muted-foreground">Expires {new Date(s.expires_at).toLocaleDateString()} · Opened {s.access_count||0} times{s.locked_until?' · temporarily locked':''}</div></div>{s.status==='active'&&<Button variant="outline" size="sm" onClick={()=>revoke(s.id)}><Trash2 className="mr-1 h-3.5 w-3.5"/>Revoke</Button>}</div>)}</div></div>}</Card>
}