import React,{useMemo,useState} from 'react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { base44 } from '@/api/base44Client';
import { useToast } from '@/components/ui/use-toast';
import { ArrowRightLeft } from 'lucide-react';

function nextGrade(g){const s=String(g||'').trim().toUpperCase();if(s==='K'||s==='KG'||s==='KINDERGARTEN')return'1';const n=Number(s);if(Number.isInteger(n)&&n>=1&&n<12)return String(n+1);if(n===12)return'Graduated';return s||'—';}
export default function RolloverDialog({open,onOpenChange,students=[],onDone}){
 const {toast}=useToast();const active=useMemo(()=>students.filter(s=>s.status==='active'),[students]);const [selected,setSelected]=useState(()=>new Set());const [busy,setBusy]=useState(false);const toggle=id=>setSelected(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);return n});const all=()=>setSelected(new Set(active.map(s=>s.id)));
 const run=async()=>{if(!selected.size){toast({title:'Select at least one student',variant:'destructive'});return;}if(!window.confirm(`Roll ${selected.size} selected student(s) into the next school-year grade? IEP dates, goals, documents, and evidence will be preserved.`))return;setBusy(true);try{const updates=active.filter(s=>selected.has(s.id)).map(s=>({id:s.id,grade:nextGrade(s.grade)==='Graduated'?s.grade:nextGrade(s.grade),status:nextGrade(s.grade)==='Graduated'?'exited':s.status,notes:[s.notes,`School-year rollover completed ${new Date().toISOString().slice(0,10)}${nextGrade(s.grade)==='Graduated'?' — marked exited after grade 12':''}.`].filter(Boolean).join('\n')}));await base44.entities.Student.bulkUpdate(updates);toast({title:'School-year rollover complete',description:`${updates.length} student records updated. Historical IEP, goals, sessions, and evidence were preserved.`});setSelected(new Set());onDone?.();onOpenChange(false);}catch(e){toast({title:'Rollover failed',description:e.message,variant:'destructive'})}finally{setBusy(false)}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className='max-w-2xl max-h-[80vh] overflow-y-auto'><DialogHeader><DialogTitle>School-Year Rollover</DialogTitle></DialogHeader><div className='rounded-xl bg-blue-50 border border-blue-100 p-3 text-sm text-blue-900'>Preview only until you confirm. CaseCue advances grade levels and preserves historical records. Grade 12 students are marked exited; nothing is deleted.</div><div className='flex justify-between items-center mt-3'><div className='text-sm font-semibold'>{selected.size} selected</div><Button variant='outline' size='sm' onClick={all}>Select all active</Button></div><div className='mt-3 space-y-2'>{active.map(s=><label key={s.id} className='flex items-center gap-3 rounded-xl border p-3 cursor-pointer'><input type='checkbox' checked={selected.has(s.id)} onChange={()=>toggle(s.id)}/><div className='flex-1'><div className='font-semibold'>{s.first_name} {s.last_name}</div><div className='text-xs text-slate-500'>Grade {s.grade||'—'} → {nextGrade(s.grade)}</div></div><ArrowRightLeft className='h-4 w-4 text-blue-600'/></label>)}</div><DialogFooter><Button variant='outline' onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={run} disabled={busy}>{busy?'Rolling over…':'Confirm rollover'}</Button></DialogFooter></DialogContent></Dialog>;
}
