import React,{useState} from 'react';
import {Archive,Trash2} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {useToast} from '@/components/ui/use-toast';

export default function RosterStatusDialog({student,open,onOpenChange,onDone}){
 const {toast}=useToast(); const [busy,setBusy]=useState(false); const [reason,setReason]=useState('transferred'); const [exitDate,setExitDate]=useState(new Date().toISOString().slice(0,10)); const [confirmName,setConfirmName]=useState('');
 if(!student)return null; const full=`${student.first_name} ${student.last_name}`.trim();
 const archive=async()=>{setBusy(true);try{await base44.entities.Student.update(student.id,{status:'exited',roster_status:'archived',exit_date:exitDate,exit_reason:reason});toast({title:'Student archived',description:`${full} was removed from the active caseload while historical records were preserved.`});onOpenChange(false);onDone?.();}catch(e){toast({title:'Could not archive student',description:e.message,variant:'destructive'});}finally{setBusy(false)}};
 const remove=async()=>{if(confirmName.trim().toLowerCase()!==full.toLowerCase())return toast({title:'Type the student’s full name to confirm permanent deletion',variant:'destructive'});setBusy(true);try{await base44.entities.Student.delete(student.id);toast({title:'Student permanently deleted',description:`${full} was removed from the roster.`});onOpenChange(false);onDone?.();}catch(e){toast({title:'Could not delete student',description:e.message,variant:'destructive'});}finally{setBusy(false)}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className='sm:max-w-xl'><DialogHeader><DialogTitle>Roster status · {full}</DialogTitle></DialogHeader><div className='space-y-5'><div className='rounded-2xl bg-blue-50 p-4'><div className='font-bold flex items-center gap-2'><Archive className='h-4 w-4'/>Archive / Student left school</div><p className='text-sm text-slate-600 mt-1'>Recommended. Removes the student from the active caseload and future scheduling while preserving historical CaseCue records.</p><div className='grid sm:grid-cols-2 gap-3 mt-4'><div><Label>Exit date</Label><Input type='date' value={exitDate} onChange={e=>setExitDate(e.target.value)}/></div><div><Label>Reason</Label><select className='w-full rounded-lg border px-3 py-2 text-sm' value={reason} onChange={e=>setReason(e.target.value)}><option value='transferred'>Transferred / moved</option><option value='graduated'>Graduated</option><option value='no_longer_eligible'>No longer eligible</option><option value='inactive'>Inactive</option><option value='other'>Other</option></select></div></div><Button className='mt-4' disabled={busy} onClick={archive}>Archive student</Button></div><div className='rounded-2xl border border-rose-200 p-4'><div className='font-bold text-rose-700 flex items-center gap-2'><Trash2 className='h-4 w-4'/>Delete permanently</div><p className='text-sm text-slate-600 mt-1'>Use for duplicate/test records or when permanent deletion is truly intended. This action cannot be undone.</p><Label className='mt-3 block'>Type “{full}” to confirm</Label><Input value={confirmName} onChange={e=>setConfirmName(e.target.value)} placeholder={full}/><Button variant='destructive' className='mt-3' disabled={busy||confirmName.trim().toLowerCase()!==full.toLowerCase()} onClick={remove}>Delete permanently</Button></div></div><DialogFooter><Button variant='outline' onClick={()=>onOpenChange(false)}>Cancel</Button></DialogFooter></DialogContent></Dialog>;
}
