import React,{useMemo} from 'react';
import {Card} from '@/components/ui/cards';
import {CheckCircle2,AlertTriangle,CalendarCheck2} from 'lucide-react';
import {formatDate,todayISO} from '@/lib/dateUtils';

const dateOf=r=>String(r?.date||r?.created_date||r?.updated_date||'').slice(0,10);
const hasStudent=(r,id)=>r?.student_id===id||(r?.student_ids||[]).includes(id);
function week(){const n=new Date();const d=n.getDay();const m=new Date(n);m.setHours(0,0,0,0);m.setDate(n.getDate()-((d+6)%7));const f=new Date(m);f.setDate(m.getDate()+4);return {start:todayISOFrom(m),end:todayISOFrom(f)}}
function todayISOFrom(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export default function CaseloadFridayDashboard({students=[],progress=[],sessions=[],assignments=[]}){
 const rows=useMemo(()=>{const w=week(),today=todayISO();return [...students].sort((a,b)=>`${a.first_name||''} ${a.last_name||''}`.localeCompare(`${b.first_name||''} ${b.last_name||''}`,undefined,{sensitivity:'base'})).map(st=>{const all=[...progress.filter(x=>x.student_id===st.id),...sessions.filter(x=>hasStudent(x,st.id)),...assignments.filter(x=>x.student_id===st.id)].filter(x=>{const d=dateOf(x);return d>=w.start&&d<=w.end});const dates=[...new Set(all.map(dateOf).filter(Boolean))].sort();const last=dates.at(-1)||'';const age=last?Math.floor((new Date(`${today}T12:00:00`)-new Date(`${last}T12:00:00`))/86400000):99;const ready=dates.length>=2&&age<=2;return {st,dates,last,ready}})},[students,progress,sessions,assignments]);
 const ready=rows.filter(r=>r.ready).length;
 return <Card className='p-6'><div className='flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3'><div><div className='flex items-center gap-2'><CalendarCheck2 className='h-5 w-5 text-blue-700'/><h2 className='text-xl font-black'>Friday Ready Board</h2></div><p className='text-sm text-slate-500 mt-1'>Your caseload at a glance. Add work, IXL/progress data, or session notes every 1–2 school days so Friday family updates are ready to review.</p></div><div className='rounded-xl bg-slate-950 text-white px-4 py-3 text-center'><div className='text-2xl font-black'>{ready}/{rows.length}</div><div className='text-xs text-slate-300'>ready</div></div></div><div className='mt-5 overflow-x-auto'><table className='w-full text-sm'><thead><tr className='border-b text-left text-xs uppercase tracking-wide text-slate-500'><th className='py-3'>Student</th><th>Data days</th><th>Last update</th><th>Friday status</th></tr></thead><tbody>{rows.map(r=><tr key={r.st.id} className='border-b last:border-0'><td className='py-3 font-bold'>{r.st.first_name} {r.st.last_name}</td><td>{r.dates.length}</td><td>{r.last?formatDate(r.last):'No data this week'}</td><td><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${r.ready?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{r.ready?<CheckCircle2 className='h-3.5 w-3.5'/>:<AlertTriangle className='h-3.5 w-3.5'/>}{r.ready?'Ready to review':'Needs data'}</span></td></tr>)}</tbody></table></div></Card>
}